### ISSUE TITLE
MacOS Mojave: OSERROR: -1743 (reopen #1073)

### ISSUE THREAD

**Issue by deltahedgetech** [xlwings/xlwings#1074]
OS (e.g. Windows 10 or macOS Sierra)

macOS Mojave

Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings(0.13.0), Excel Version 16.19 (Office 365 subscription), Python 3.7

#### Describe your issue (incl. Traceback!)

Followed the steps in #967 apart from reverting to previous version.
Running xw.Book() opens up a new Excel instance but still get this error. When attempting to open an existing Excel file, it opens up the file in question but don't get the object in python e.g. wb = xw.Book('/Users/stuartclark/Desktop/xlwings_test.xlsx')
```python
# Your traceback here

>>> xw.Book()
Traceback (most recent call last):
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/aeosa/appscript/reference.py", line 460, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: OS error (-1743)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/xlwings/main.py", line 499, in __init__
    impl = app.books[0].impl
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/xlwings/main.py", line 67, in __getitem__
    l = len(self)
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/xlwings/main.py", line 52, in __len__
    return len(self.impl)
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/xlwings/_xlmac.py", line 185, in __len__
    return self.app.xl.count(each=kw.workbook)
  File "/Users/stuartclark/anaconda3/lib/python3.6/site-packages/aeosa/appscript/reference.py", line 496, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: OS error
		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 426088)).count(each=k.workbook)

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
can you paste a screenshot of Privacy > Automation?

**Comment by deltahedgetech** [comment]
Many apologies Felix for wasting your time. I didn't enable Excel in Automation. Will close ticket

**Comment by Gaomojiang** [comment]
can u teach me how to fix this problem？

**Comment by fzumstein** [comment]
see: https://github.com/xlwings/xlwings/issues/1146
