### ISSUE TITLE
pywintypes.com_error : connection to workbook broken, can not reconnect 

### ISSUE THREAD

**Issue by hakimbounoua** [xlwings/xlwings#1088]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Version 1607 (14393.2848) 
and Windows Server 2012 R2 Version 6.3
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.6.6 (32 bits)
Excel 2016 (32 bits)
and Excel (32 bits)
Xlwings 0.15.1

Trust access to VBA project is enabled.

#### Describe your issue (incl. Traceback!)
Triying to execute 400 SQL queries that takes between 0.01 seconde and 2 minutes on a SQLite data base.

The error appears randomly, sometimes on the 100th query, sometimes on the 130th query etc. But always on a query that takes time (betwen 1 and 2 minutes).

Whene there is only the fast queries, it works fine.

When I run th python script with the command line there is no problem. 

It's like the connection to the workbook is broken. When I try to do wb = xw.Book(jdd_Donnees) or wb.api.RefreshAll() at every iteration, I have the same error (but after more iterations).
 
```python
# Your traceback here
# in logs :
# 1
Traceback (most recent call last):
  File "C:\ref-local\v2.7\dev_v2.7\refscript.py", line 1134, in reinit_ref
    if sheet.name.startswith("Contexte_"):
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\main.py", line 62, in __iter__
    for impl in self.impl:
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 528, in __iter__
    for xl in self.xl:
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 174, in __iter__
    for v in self._inner:
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\win32com\client\dynamic.py", line 252, in __getitem__
    return self._get_good_object_(self._enum_.__getitem__(index))
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\win32com\client\util.py", line 37, in __getitem__
    return self.__GetIndex(index)
  File "C:\ref-local\virtuaref-local\virtualenvlenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\win32com\client\util.py", line 53, in __GetIndex
    result = self._oleobj_.Next(1)
pywintypes.com_error: (-2147417856, 'Échec d’un appel système.', None, None)


# 2
Traceback (most recent call last):
File "C:\ref-local\v2.7\dev_v2.7\refscript.py", line 452, in reinit_ref
    wb.api.RefreshAll()
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 63, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in RefreshAll
pywintypes.com_error: (-2147417856, 'Échec d’un appel système.', None, None)

# When I connect to the workbook at every iteration. (Error occurs on long queries) 
Traceback (most recent call last):
  File "C:\ref-local\v2.7\dev_v2.7\refscript.py", line 441, in reinit_ref
    wb = xw.Book(jdd_Donnees)
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\main.py", line 480, in __init__
    for wb in app.books:
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\main.py", line 366, in books
    return Books(impl=self.impl.books)
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 385, in books
    return Books(xl=self.xl.Workbooks)
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 310, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 220, in get_xl_app_from_hwnd
    ptr = accessible_object_from_window(child_hwnd)
  File "C:\ref-local\virtualenv\virtualenv_32bits\virtualenv\WinPythonZero\python-3.6.6\lib\site-packages\xlwings\_xlwindows.py", line 190, in accessible_object_from_window
    byref(IDispatch._iid_), byref(ptr))
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147467259] Erreur non spécifiée



```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

Excel code
Py.CallUDF "pythonscript", "pythonfunction", Array(param1, param2, ...), ThisWorkbook, Application.Caller
# RunPython don't work 

Python code

(...)
wb = xw.Book(pathToWorkbook) # I don't use xw.Book.caller because I connect to another workbook. Workbook 1 contains the macros and workbook 2 contains data.

for sheet in wb.sheets:
    # Get data from Excel workbook
    for query in queries:
        (...)
        try:
            wb.api.RefreshAll()  #1
            df = pd.read_sql_query(query, conn)
        except Exception as e:
            wb = xw.Book(jdd_Donnees) #2
        (...)
    
# Copie data to Excel workbook 
```

Thank you.

**Comment by fzumstein** [comment]
How did you solve your issue?

**Comment by hakimbounoua** [comment]
Hello,

I found a workaround.

I changed my code to interact with Excel at the beginning of the script, before the part of the code that was causing the bug. To copy the final results to Excel, I moved the code that was copying the results into a new python function and I added a vba msgbox between the calls to the python functions.

Py.CallUDF 1 : get all the data from excel, do the long job, can't interact with Excel anymore
vba msgbox pou up : you have to click on it
Py.CallUDF 2 to another function : and now it's possible to connect to Excel.

**Comment by fzumstein** [comment]
Great, thanks for sharing!
