### ISSUE TITLE
 @xw.sub causes error with async_mode

### ISSUE THREAD

**Issue by heury** [xlwings/xlwings#1109]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.15.8
#### Describe your issue (incl. Traceback!)

@xw.sub causes error with async_mode.
Is it normal?

============ Python  Code ==================================

```
@xw.sub(async_mode='threading')
def asyncTest():
    print('async test')

```

============ Error ==================================

```
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\server.py", line 198, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\udfs.py", line 285, in call_udf
    cache_key = get_cache_key(func, args, caller)
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\udfs.py", line 250, in get_cache_key
    xw_caller.sheet.book.name + xw_caller.sheet.name + xw_caller.address.split(':')[0])
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\main.py", line 1094, in sheet
    return Sheet(impl=self.impl.sheet)
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\_xlwindows.py", line 697, in sheet
    return Sheet(xl=self.coords[0])
  File "C:\dev\Anaconda3\envs\py37_32\lib\site-packages\xlwings\_xlwindows.py", line 683, in coords
    self.xl.Worksheet,
AttributeError: 'str' object has no attribute 'Worksheet'

```

**Comment by fzumstein** [comment]
yes, `async_mode` is currently only available for cell functions. And they are still early stage, see e.g. #1010

**Comment by sdementen** [comment]
hi  @heury, @fzumstein 

Would this be useful to implement such a feature?

```
def sub_async(f):
    """equivalent to a xw.sub but running in a thread and injecting the activesheet as first argument"""

    @xw.sub
    @xw.arg('sh', vba='ActiveSheet')
    @wraps(f)
    def helper(sh):
        wb = sh.Parent
        thread = threading.Thread(target=f_, args=(wb.Application.Hwnd, wb.FullName, sh.Name))
        thread.daemon = True
        thread.start()

    def f_(app_hwnd, wb_fullname, sh_name):
        pythoncom.CoInitialize()
        # get back xlwings objects
        app, = (app for app in xw.apps if app.api.Hwnd == app_hwnd)
        wb, = (wb for wb in app.books if wb.api.FullName == wb_fullname)
        sh, = (sh for sh in wb.sheets if sh.name == sh_name)
        # run the original function
        f(sh)

    return helper


@sub_async
def long_running_process(sh: xw.Sheet):
    """Example of async syb writing the status of a long running process in cell A1 and in Excel status bar"""
    status_cell = sh.range("A1")
    app: xw.App = sh.book.app

    class ExcelStatus(TextIOBase):
        def __init__(self, on_status_bar=True, on_cell=False):
            self._on_status_bar = on_status_bar
            self._on_cell = on_cell

        def write(self, txt):
            if self._on_cell:
                self._on_cell.value = txt
            if self._on_status_bar:
                app.status_bar = txt[1:]

        def flush(self):
            pass

    # write something to a cell to tell the user the process is running
    status_cell.value = "start processing"

    # simulate long running process
    for i in tqdm(range(10), file=ExcelStatus(on_cell=status_cell), dynamic_ncols=False):
        time.sleep(1)

    # write the final results
    status_cell.value = f"done with processing on {datetime.now()}"
```

**Comment by fzumstein** [comment]
Won't this hit the COM timeout if you replace your for loop with time.sleep(300)?

**Comment by sdementen** [comment]
I tried and got no issues.
The sub is not blocking so excel does not trigger the "excel is waiting for ..."

**Comment by fzumstein** [comment]
Right, I was actually meant to ask if it shows the same garbage collection issue that's happening sometimes in the sync case (way after the suppressed timeout popup). Anyhow, I'll give this a try when I got a minute and let you know!

**Comment by sdementen** [comment]
Hi @fzumstein 
Did you have time to try it? It could be a nice addition for long running sub where you want the user to continue viewing the workbook

**Comment by fzumstein** [comment]
I haven't, but I agree, it's a great idea and neat way of how you get back the xlwings object, which was one of the issues that always threw me off. I'll create a new issue out of it.
