### ISSUE TITLE
Fail to import Pandas and Numpy

### ISSUE THREAD

**Issue by Shihao-Bob-Sun** [xlwings/xlwings#1115]
#### Describe your issue (Fail to import Pandas and Numpy)

I want to run pyhton function in excel. However, when I import the Pandas in my py file. It prompts:

xlwings server running, clsid={58D33331-AF4F-436D-9C87-8699EB223B73}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\udfs.py", line 456, in import_udfs
    module = get_udf_module(module_name)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\udfs.py", line 228, in get_udf_module
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3_New\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\bsun\desktop\try\Try_Code.py", line 8, in <module>
    import pandas as pd
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

After I include "import numpy as np" statement before "import pandas as pd", it prompts:

xlwings server running, clsid={58D33331-AF4F-436D-9C87-8699EB223B73}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\udfs.py", line 456, in import_udfs
    module = get_udf_module(module_name)
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\xlwings\udfs.py", line 228, in get_udf_module
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3_New\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\bsun\desktop\try\Try_Code.py", line 8, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\ProgramData\Anaconda3_New\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

#### My code here:

import xlwings as xw
import pandas as pd

@xw.func
def hello(name):
    return 'Hello {0}'.format(name)

@xw.func
@xw.arg('x', pd.DataFrame)
def sum(x):
    return x['value'].sum()

Note: hello function works perfectly fine.

Can anyone help me with that? Thank you very much.

**Comment by fzumstein** [comment]
is this using your anaconda base installation?

**Comment by Shihao-Bob-Sun** [comment]
Thank you for your reply. 
Yes, I think so, because the xlwings, pandas, and numpy packages are all installed along with my installation of anaconda.

**Comment by fzumstein** [comment]
When you `import pandas` on your command prompt, does it work without error?

**Comment by Shihao-Bob-Sun** [comment]
I can successfully import pandas in Jupyter notebook. But when I import pandas in Anaconda command prompt, it says:

(base) C:\Users\bsun>import pandas
'import' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\bsun>

**Comment by fzumstein** [comment]
you'd need to run `python` first before running the import command.

**Comment by Shihao-Bob-Sun** [comment]
Thank you. Do you mean run python in the windows terminal? Could you clarify how I can run python before the import command? Thank you.

**Comment by fzumstein** [comment]
I think that's solved via the Conda settings in the add-in.
