### ISSUE TITLE
Application is closed after closing workbook despite other workbook objects

### ISSUE THREAD

**Issue by sojourner-c** [xlwings/xlwings#1128]
#### OS
Windows Server 2016 Datacenter

#### Versions
xlwings 0.15.8, Excel 2013, and Python 3.7.1

#### Describe your issue
`xlwings.app` is closed after adding a workbook to the application and closing the original workbook. This occurs unless a reference to the `xlwings.app` is made in the method closing the workbook.

#### Minimal Code Sample
I have the script below named `example.py`:

```python
import xlwings


class Parent:

	def __init__(self):
		app = xlwings.App(visible=False, add_book=False)
		self.workbook = app.books.add()


class Child(Parent):

	def my_method(self):
		self.new_workbook = self.workbook.app.books.add()
		self.workbook.close()
		print(self.new_workbook.name)


if __name__ == "__main__":
	Child().my_method()
```
Calling the script results in the following traceback:

```python-traceback
(venv) C:\example_folder>python example.py
Traceback (most recent call last):
  File "C:\example_folder\venv\lib\site-packages\xlwings\_xlwindows.py", line 117, in __getattr__
    v = getattr(self._inner, item)
  File "C:\example_folder\venv\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: Add.Name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 20, in <module>
    Child().my_method()
  File "example.py", line 16, in my_method
    print(self.new_workbook.name)
  File "C:\example_folder\venv\lib\site-packages\xlwings\main.py", line 656, in name
    return self.impl.name
  File "C:\example_folder\venv\lib\site-packages\xlwings\_xlwindows.py", line 461, in name
    return self.xl.Name
  File "C:\example_folder\venv\lib\site-packages\xlwings\_xlwindows.py", line 137, in __getattr__
    self._oleobj_.GetIDsOfNames(0, item)
pywintypes.com_error: (-2147023179, 'The interface is unknown.', None, None)
```
Changing `print(self.new_workbook.name)` to `print(xlwings.apps)` results in `Apps([])`.

Changing `example.Child.my_method` by adding a reference to the application fixes the issue:

```python
	def my_method(self):
		self.new_workbook = self.workbook.app.books.add()
		app = self.workbook.app # add reference to app
		self.workbook.close()
		print(self.new_workbook.name)
```

**Comment by fzumstein** [comment]
I think you're just missing a self in the parent class:

```
class Parent:

	def __init__(self):
		self.app = xlwings.App(visible=False, add_book=False)
		self.workbook = self.app.books.add()
```

**Comment by sojourner-c** [comment]
I agree that binding `app` to the class instance also fixes the problem. I thought it was odd that I can use `self.workbook` in child classes without a bound reference to the application without issue. But when I close any workbook object belonging to the application, even if its not the only workbook object, the application is cleaned up. I think my expectation was all workbook objects would contain a reference to the application preventing cleanup. If this is expected behavior then the issue should be closed.

**Comment by fzumstein** [comment]
yeah, you're right and it's not an expected behaviour (it works correctly on mac).
I am not sure yet though if the issue is with pywin32 or with what we do in xlwings.
