### ISSUE TITLE
Problem of finding numpy DLL using xlwings Add-in

### ISSUE THREAD

**Issue by rodrigo101032** [xlwings/xlwings#1139]
#### Problem of finding numpy DLL using xlwings Add-in -  Traceback!

Here is the error:

pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\xlwings\udfs.py", line 456, in import_udfs
    module = get_udf_module(module_name)
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\xlwings\udfs.py", line 228, in get_udf_module
    module = import_module(module_name)
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\rodrigo.oliveira\pycharmprojects\teste1\Book5.py", line 2, in <module>
    import numpy as np
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\rodrigo.oliveira\AppData\Local\Continuum\anaconda3\envs\teste1\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

#### I'm trying to use numpy on excel using the xlwings add-in and i'm having this problem. Here is my python code:

import xlwings as xw
import numpy as np

@xw.func
@xw.arg('x', np.array, ndim=2)
@xw.arg('y', np.array, ndim=2)
def matrix_mult(x, y):
    return x @ y

```

**Comment by fzumstein** [comment]
What does your config look like? do you use the conda settings?

**Comment by fzumstein** [comment]
see: https://github.com/xlwings/xlwings/issues/1110
