### ISSUE TITLE
xlwings unspecified error

### ISSUE THREAD

**Issue by ghost** [xlwings/xlwings#1143]
Hi, An excel sheet which was previously working fine gives an error now.

The xlwings logfile is as follow:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "s:\james\historicalvol.py", line 358, in final_minute_tick_vols
    xw.Book("S:\James\Vol monitor\Vol monitor.xlsm").set_mock_caller()
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 480, in __init__
    for wb in app.books:
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 366, in books
    return Books(impl=self.impl.books)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 385, in books
    return Books(xl=self.xl.Workbooks)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 310, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 220, in get_xl_app_from_hwnd
    ptr = accessible_object_from_window(child_hwnd)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 190, in accessible_object_from_window
    byref(IDispatch._iid_), byref(ptr))
  File "_ctypes/callproc.c", line 911, in GetResult
OSError: [WinError -2147467259] Unspecified error

Any ideas on how to solve this?

**Comment by fzumstein** [comment]
Have you tried after a reboot? If you call it from Excel, then you should not use `set_mock_caller`.

**Comment by James-B1** [comment]
Changed that back to normal. Error is now:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "s:\james\historicalvol.py", line 294, in final_bb_vols
    start_dt = wb.sheets[sheet].range('Date2').value - BDay(offset)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 78, in __getitem__
    return self(key)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 2816, in __call__
    return Sheet(impl=self.impl(name_or_index))
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 522, in __call__
    return Sheet(xl=self.xl(name_or_index))
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 152, in __call__
    v = self._inner(*args, **kwargs)
  File "C:\Users\james\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

**Comment by fzumstein** [comment]
You can get a more meaningful error like this: 

>>> import win32api
>>> win32api.FormatMessage(-2147352565)
'Invalid index.\r\n'

So you must be accessing a sheet index or sth that doesn't exist.

**Comment by James-B1** [comment]
Thanks for you help. What about the exception occurred error? (2147352567)

Nothing has changed on the line:
>> start_dt = wb.sheets[sheet].range('Date2').value - BDay(offset)
But this is giving the error

**Comment by njwhite** [comment]
Excel is busy. #1395 should fix -
