### ISSUE TITLE
Multiprocessing error in _xlwindows.py

### ISSUE THREAD

**Issue by qandour** [xlwings/xlwings#1150]
#### Versions of xlwings, Excel and Python (e.g. 0.15.10, Office Professional Plus 2013, Python 3.7)

Setting range value to dataframe then calling autofit(). Works fine when single threaded but fails randomly with multi-processing. Reproducible with stress testing. NOTE: Git does not allow me to attach xlsm files so I've attached a macro-free version of my standalone workbook (I was using xlwings as an embedded VBA module)

``` python
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\....\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\....\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\....\multiprocessing_stress_test.py", line 14, in do_work
    rng.autofit()
  File "C:\....\lib\site-packages\xlwings\main.py", line 1428, in autofit
    return self.impl.autofit()
  File "C:\....\lib\site-packages\xlwings\_xlwindows.py", line 855, in autofit
    self.xl.Rows.AutoFit()
TypeError: 'bool' object is not callable

```

[Test.xlsx](https://github.com/xlwings/xlwings/files/3615257/Test.xlsx)

```python
import xlwings as xw
import pandas as pd
import numpy as np
import multiprocessing as mp


def do_work(sheet_name, value):
    sheet = xw.Book('Test.xlsm').sheets[sheet_name]

    rng = sheet.range('A1')
    rng.options(pd.DataFrame, header=True, index=False).value = value

    for i in range(20):  # Stress test
        rng.autofit()  # Exception happens here


if __name__ == '__main__':
    X = 'SheetX'
    Y = 'SheetY'
    Z = 'SheetZ'
    df = pd.DataFrame(np.arange(100).reshape(10, 10), columns=list('ABCDEFGHIJ'))

    # Works with 1 thread but not with 3 threads
    with mp.Pool(3) as p:  # Stress test
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])
        p.starmap(do_work, [(X, df), (Y, df), (Z, df)])

```

**Comment by fzumstein** [comment]
My best guess is that there need to be some rules added to the docs...you're manipulating the same cell here so the different processes are probably conflicting with each other. Try if you get the same issue if use `autofit` on non-conflicting cells, probably most easily tried out with ranges on different sheets.

**Comment by qandour** [comment]
I believe they are different cells because the sheets are different (X, Y and Z) with a process per sheet.

But having failed to reproduce the problem today, I thought hard about what else was happening a week ago when I saw the error. The answer is: I had another book open, which happened to have **`#NAME? `** errors in it.

I've edited my original comment, the attached book and code to reflect this.

Any idea how **`#NAME? `** errors relate to conflicts in multiprocessing?

If we understand what's going on we can either put in a fix or describe the caveat in the docs.

**Comment by fzumstein** [comment]
right, sorry, must have been late yesterday. No idea really, but I'll try to replicate.

**Comment by blwy10** [comment]
Hi there, I've also got this error. I didn't use multiprocessing, and got this error when calling clear_contents on a cell range. It works on one laptop but not the other. One laptop has a later version of office which supports some new functions. The other laptop where there's an error, on excel it shows #NAME for missing functions that are not supported. Maybe this is what's causing the issue?

I can't really share screenshots of the files as it's confidential material, but let me know what's helpful to produce so you can diagnose the bug? Of course understand this is open source, so bugs don't get fixed immediately, but I use this package a lot, so want to be helpful :)
