### ISSUE TITLE
Can't open a book with xw.Book(path), but can with xw.books.open(path)

### ISSUE THREAD

**Issue by ClayMDMI** [xlwings/xlwings#1171]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.16.0
Excel: Office 365 MSO (16.0.12026.30334) 64-bit
Python: Python 3.6.5 :: Anaconda custom (64-bit)

#### Describe your issue (incl. Traceback!)
When opening a book, I can only use xw.books.open(path). When I use xw.Book(path) it fails.

```python
Traceback (most recent call last):
  File "C:/Users/Clay.MDMI/PycharmProjects/testingGrounds/testingGrounds2.py", line 5, in <module>
    xw.Book(templateFilePath)
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\main.py", line 481, in __init__
    for wb in app.books:
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\main.py", line 366, in books
    return Books(impl=self.impl.books)
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\_xlwindows.py", line 385, in books
    return Books(xl=self.xl.Workbooks)
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\_xlwindows.py", line 310, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\_xlwindows.py", line 220, in get_xl_app_from_hwnd
    ptr = accessible_object_from_window(child_hwnd)
  File "C:\Users\Clay.MDMI\PycharmProjects\testingGrounds\venv\lib\site-packages\xlwings\_xlwindows.py", line 190, in accessible_object_from_window
    byref(IDispatch._iid_), byref(ptr))
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147467259] Unspecified error
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
Uncommenting the 4th line will throw the above error, but currently it would run fine.
```python
import xlwings as xw
app = xw.App()
templateFilePath = r'C:\Users\Clay.MDMI\source\repos\Schema Tool\SchemaTool/Schema Mapping Template.xlsx'
# xw.Book(templateFilePath)
xw.books.open(templateFilePath)
```

I had xlwings in a virtual environment and it was working just fine. Recently, I deleted the venv and made a new one the same way, downloaded all the same modules, and ran it the same way, but got errors. And if I run it without the venv and on the base Anaconda I still get errors. Let me know if I can provide anything else to help.

**Comment by ClayMDMI** [comment]
pywin32                   223              py36hfa6e2cd_1

**Comment by fzumstein** [comment]
closing this as I can't replicate. feel free to reopen if the error persists.
