### ISSUE TITLE
Crash with "Use UDF Server" as True

### ISSUE THREAD

**Issue by luokar** [xlwings/xlwings#1175]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Office 365, Windows 10, Python 3.7
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):

  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\xlwings\server.py", line 287, in Exec
    exec(stmt, globals, locals)
  File "<string>", line 1, in <module>
  File "D:\code\xlwings-demo\demo.py", line 33, in hello_xlwings
    wb.app.range("A1").value = "test"
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\xlwings\main.py", line 674, in app
    return App(impl=self.impl.app)
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\xlwings\_xlwindows.py", line 469, in app
    return App(xl=self.xl.Application)
  File "C:\Users\luo\Miniconda3\envs\test\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
pywintypes.com_error: (-2147417856, 'System call failed.', None, None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

def hello_xlwings():
    second = 0
    while True:
        time.sleep(1)
        second += 1
        print(second)
        wb = xw.Book.caller()
        wb.app.range("A1").value = "test"

```

```VBA
Sub SampleCall()
    Application.DisplayAlerts = False
    RunPython ("from demo import hello_xlwings; hello_xlwings()")
End Sub
```

The same code work with "Use UDF Server" as False

**Comment by luokar** [comment]
Looks like it is related to _xlwindows.BOOK_CALLER got garbage collected. :/ or something similar

**Comment by luokar** [comment]
If I put
```Python
    from xlwings import _xlwindows
    a = _xlwindows.BOOK_CALLER
```
in my code, I don't crash, but is there any side effect for doing this?

**Comment by fzumstein** [comment]
I can't replicate the issue, works fine for me with both options. Maybe try to move out `wb = xw.Book.caller()` of the function and see if that has the  same effect as your hack. However, how are you going to stop the process again?

**Comment by luokar** [comment]
The infinite loop is just for demo purpose. Usually when a call last for longer than 130 seconds, it will run into the exception.
Putting wb = xw.Book.caller() in global state can also solve the problem.

**Comment by fzumstein** [comment]
Isn't this a duplicate then from https://github.com/xlwings/xlwings/issues/120 ? Use UDF Server used to be called OPTIMIZED_CONNECTION in older releases. Try some of the solutions described there.

**Comment by luokar** [comment]
@fzumstein The workaround is "xl.Application(wkb=my_wb).xl_app.DisplayAlerts = False" by Juanlu001 ?
I believe I have included that already in form of VBA.

**Comment by fzumstein** [comment]
well, nowadays it's `wb.app.display_alerts = False`. Try it on the python side.

**Comment by luokar** [comment]
@fzumstein 
I finally find the reliable way to reproduce this problem. 
I only try this in conda mode, don't know whether it is the same as in non conda
First, run RunPython ("raise Exception('demo')"), let it crash.
Then run 
Application.DisplayAlerts = False
RunPython ("from demo import hello_xlwings; hello_xlwings()")
And wait for 130 seconds
