### ISSUE TITLE
Error Automation 440

### ISSUE THREAD

**Issue by nrollet** [xlwings/xlwings#1191]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

- 0.16.0,
- Excel 2013 32b, 
- Python 3.6.8 

#### Describe your issue (incl. Traceback!)
I'm using the standard configuration provided with the Add-in.
.xlwings\xlwings.conf
*"LOG FILE",""*
*"DEBUG UDFS","Faux"*
*"CONDA BASE",""*
*"UDF MODULES",""*
*"USE UDF SERVER","Faux"*
*"INTERPRETER","python"*

* The spreadsheet has been created with the xlwings quickstart command
* Macro settings are enabled
* Run-Main button works as expected
* With Add-in, lauching "Import functions" raises the following error message :
"Error Automation 440"

```python
xlwings server running, clsid={3BB4F1C1-6EF3-4855-8137-A735C7BDDB48}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\udfs.py", line 456, in import_udfs
    xl_workbook.VBProject.VBComponents.Import(tf.name)
  File "C:\Users\nicolas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
pywintypes.com_error: (-2147352567, 'Une exception s’est produite.', (0, 'Microsoft Excel', "L'accès par programme au projet Visual Basic n'est pas fiable\n", 'xlmain11.chm', 0, -2146827284), None)



```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

@xw.func
def double_sum(x, y):
    """Returns twice the sum of the two arguments"""
    return 2 * (x + y)

```

**Comment by nrollet** [comment]
Sorted...
Had to enable "Trust access to the VBA project object model"
