### ISSUE TITLE
xlwings and conda env don't seem to play nice (pywintypes issue?)

### ISSUE THREAD

**Issue by GrantPayneDenver** [xlwings/xlwings#1270]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.18.0, Excel 16.0, Python 3.7
#### Describe your issue (incl. Traceback!)

Just trying to run the xlwings python module via excel.

Added Conda Base and Conda Env paths in the xlwings ribbon, got an exception that seems to stem from a strange pywintypes error.

Conda Base: C:\Users\gpayne\AppData\Local\Continuum\miniconda3
Conda Env: C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37

```python

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\_xlwindows.py", line 431, in __call__

    return Book(xl=self.xl(name_or_index))

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\_xlwindows.py", line 151, in __call__

    v = self._inner(*args, **kwargs)

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__

    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\gpayne\documents\_fastsim_numba\fsim_testing\fsim_testing.py", line 6, in hello_xlwings

    wb = xw.Book.caller()

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\main.py", line 586, in caller

    return cls(impl=app.books[name].impl)

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\main.py", line 77, in __getitem__

    return self(key)

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\main.py", line 48, in __call__

    return self._wrap(impl=self.impl(name_or_index))

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\_xlwindows.py", line 433, in __call__

    raise KeyError(name_or_index)

KeyError: 'c:\\users\\gpayne\\documents\\_fastsim_numba\\fsim_testing\\fsim_testing.xlsm'




```

#### Include a minimal code sample to reproduce the issue 

Doesn't get to this point, but it's the simple demo code.
```python
import xlwings as xw
import numba as nb
import sys

def hello_xlwings():
    wb = xw.Book.caller()
    wb.sheets[0].range("A1").value = sys.executable


@xw.func
def hello(name):
    return "hello {0}".format(name)

```

**Comment by fzumstein** [comment]
The env is only the name of the env not the full path: `fastsim_py37`

**Comment by GrantPayneDenver** [comment]
I changed the env value to just ```fastsim_py37``` and I still get the same exception.

> 

```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\_xlwindows.py", line 431, in __call__

    return Book(xl=self.xl(name_or_index))

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\xlwings\_xlwindows.py", line 151, in __call__

    v = self._inner(*args, **kwargs)

  File "C:\Users\gpayne\AppData\Local\Continuum\miniconda3\envs\fastsim_py37\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__

    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)



```

**Comment by fzumstein** [comment]
What happens if you run this from a Python interpreter:

```
import xlwings as xw
xw.Book('c:\\users\\gpayne\\documents\\_fastsim_numba\\fsim_testing\\fsim_testing.xlsm')
```

**Comment by GrantPayneDenver** [comment]
Book opens correctly. But running the ```hello_xlwings()``` code from the book that is opened still fails with same message.
```
>>> import xlwings as xw
>>> xw.Book('c:\\users\\gpayne\\documents\\_fastsim_numba\\fsim_testing\\fsim_testing.xlsm')
<Book [fsim_testing.xlsm]>
```

**Comment by FinancialRADDeveloper** [comment]
I see the exact same issue with an Anaconda virtual ennvironment

**Comment by fzumstein** [comment]
closing this as I can't replicated it.
