### ISSUE TITLE
xw.Book.caller().sheets.active stopped working from 0.17.1 to 0.18.0

### ISSUE THREAD

**Issue by xinxilas** [xlwings/xlwings#1272]
Windows 10

Versions of xlwings 0.18.0 , Excel 2016 - 
Simple stoped working, i have no tracebak messages 

```python
s = xw.Book.caller().sheets.active
```

I called .py file from RunPython inside vba excel
The script doesnt run after this line, im runing from an thread inside the code so no traceback right now

**Comment by fzumstein** [comment]
Can't replicate this. Using quickstart and this code works for me: 

```python
def main():
    wb = xw.Book.caller()
    s = xw.Book.caller().sheets.active
    wb.sheets[0].range("A1").value = s.name
    wb.sheets[0].range("A2").value = xw.__version__
```

**Comment by juliuscrn** [comment]
Same here. Win 7, office 2010 pro. Downgrade from 0.18.0 to 0.17.1 fixed the issue.

**Comment by juliuscrn** [comment]
Btw, its not just xw.Book.caller().sheets.active. A call to xw.Book.caller() triggers the same error.

**Comment by fzumstein** [comment]
have you also made sure that the add-in is the same version, i.e. 0.18.0?

**Comment by xinxilas** [comment]
Installed 0.18

Tried your function:
```
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\_xlwindows.py", line 431, in __call__
    return Book(xl=self.xl(name_or_index))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\_xlwindows.py", line 151, in __call__
    v = self._inner(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)
pywintypes.com_error: (-2147352567, 'Exceção.', (0, None, None, None, 0, -2147352565), None)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "m:\onedrive\ame\mlivre.py", line 3, in main
    wb = xw.Book.caller()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\main.py", line 586, in caller
    return cls(impl=app.books[name].impl)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\main.py", line 77, in __getitem__
    return self(key)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\main.py", line 48, in __call__
    return self._wrap(impl=self.impl(name_or_index))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\xlwings\_xlwindows.py", line 433, in __call__
    raise KeyError(name_or_index)
KeyError: 'm:\\dropbox\\opencart\\controleanuncios.xlsm'


Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```


Returned to 0.17.1, it runs ok

**Comment by fzumstein** [comment]
how did you update the addin?

**Comment by xinxilas** [comment]
Man i completely forgot the windows/excel addin file

Now it worked:
```
C:\Program Files (x86)\Python37-32\Scripts>xlwings addin install
xlwings 0.18.0
Successfully installed the xlwings add-in! Please restart Excel.
```
