### ISSUE TITLE
Setting a cell to a formula hangs forever or crashes with COM error

### ISSUE THREAD

**Issue by padelt** [xlwings/xlwings#1273]
#### OS
Windows 10 Version 1909 Build 18363.657

#### Versions of xlwings, Excel and Python
xlwings 0.16.0 and 0.18.0 behave identically.
Excel 2016 (16.0.4966.1000) MSO (16.0.4939.1000) 64-Bit
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Windows locale is German.

#### Describe your issue (incl. Traceback!)

```python
0.18.0
Step 1
Step 2
Step 3
Step 4
Traceback (most recent call last):
  File "t.py", line 21, in <module>
    sheet.range((1, 1)).value = [1, '=IF(A2=1;"A";"B")']  # hangs or (with reduced N_COM_ATTEMPTS) crashes
  File "D:\dev\test\venv\lib\site-packages\xlwings\main.py", line 1526, in value
    conversion.write(data, self, self._options)
  File "D:\dev\test\venv\lib\site-packages\xlwings\conversion\__init__.py", line 42, in write
    pipeline(ctx)
  File "D:\dev\test\venv\lib\site-packages\xlwings\conversion\framework.py", line 63, in __call__
    stage(*args, **kwargs)
  File "D:\dev\test\venv\lib\site-packages\xlwings\conversion\standard.py", line 61, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "D:\dev\test\venv\lib\site-packages\xlwings\conversion\standard.py", line 49, in _write_value
    rng.raw_value = value
  File "D:\dev\test\venv\lib\site-packages\xlwings\main.py", line 1147, in raw_value
    self.impl.raw_value = data
  File "D:\dev\test\venv\lib\site-packages\xlwings\_xlwindows.py", line 732, in raw_value
    self.xl.Value = data
  File "D:\dev\test\venv\lib\site-packages\xlwings\_xlwindows.py", line 97, in __setattr__
    return setattr(self._inner, key, value)
  File "D:\dev\test\venv\lib\site-packages\win32com\client\dynamic.py", line 549, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146827284), None)
>>>

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import platform

import xlwings
print(xlwings.__version__)

if platform.system() == 'Windows':
    # This replaces the infinite loop in the last line with an error after several seconds.
    import xlwings._xlwindows
    if xlwings._xlwindows.N_COM_ATTEMPTS == 0:
        xlwings._xlwindows.N_COM_ATTEMPTS = 20

book = xlwings.Book()
sheet = book.sheets[0]
print("Step 1")
sheet.range((1, 1)).value = [1, 2]  # works fine
print("Step 2")
sheet.range((1, 1)).value = [1, "ABC"]  # works fine
print("Step 3")
sheet.range((1, 1)).value = [1, "=ABC"]  # works fine and excel shows "#NAME?"
print("Step 4")
sheet.range((1, 1)).value = [1, '=IF(A2=1;"A";"B")']  # hangs or (with reduced N_COM_ATTEMPTS) crashes

```
Without setting `N_COM_ATTEMPTS` to a value >0, the last line hangs forever.
With the setting (as shown above), it crashes with the stacktrace above.

Also note that using the german version of the formula (`'=WENN(A2=1;"A";"B")'`) does the same.

**Comment by padelt** [comment]
Turns out it was a syntax error. Formula syntax for english Excel ist `=IF(A1=1,"A","B")` (note the comma instead of colon). In my tests, it needs to be the english syntax including english function names (`IF`) instead of the localized ones (`WENN`) even when the running excel is localized to german.
