### ISSUE TITLE
Failed to install xlwings on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by xhzhou1234** [xlwings/xlwings#1279]
#### OS (e.g. Windows 10 or macOS Sierra)
Ubuntu 18.04.4 LTS
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.18.0, Python: 3.7.3
#### Describe your issue (incl. Traceback!)
Failed to install or run code on Ubuntu 18.04.4 LTS

```python
# Your traceback here
[Step1] Failed to install on Ubuntu 18.04.4 LTS: sudo pip install xlwings
$ sudo pip install xlwings
Error log >>>>
Collecting xlwings
  Downloading xlwings-0.18.0.tar.gz (595 kB)
     |████████████████████████████████| 595 kB 18 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cbtbtifj/xlwings/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cbtbtifj/xlwings/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-cbtbtifj/xlwings/pip-egg-info
         cwd: /tmp/pip-install-cbtbtifj/xlwings/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cbtbtifj/xlwings/setup.py", line 32, in <module>
        raise OSError("xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings")
    OSError: xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

[Step2] Failed to install on Ubuntu 18.04.4 LTS: export INSTALL_ON_LINUX=1; sudo pip installxlwings
$ export INSTALL_ON_LINUX=1; sudo pip installxlwings
Error log >>>>
Collecting xlwings
  Downloading xlwings-0.18.0.tar.gz (595 kB)
     |████████████████████████████████| 595 kB 36 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b442ai0w/xlwings/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b442ai0w/xlwings/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-b442ai0w/xlwings/pip-egg-info
         cwd: /tmp/pip-install-b442ai0w/xlwings/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b442ai0w/xlwings/setup.py", line 32, in <module>
        raise OSError("xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings")
    OSError: xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

[Step3] Failed from pip, then try to from source code
$ tar -zxvf  xlwings-0.18.0.tar.gz
$ sudo python setup.py install
Error log >>>
Traceback (most recent call last):
  File "setup_old.py", line 32, in <module>
    raise OSError("xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings")
OSError: xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings

[Step4] Set INSTALL_ON_LINUX to 1 in setup.py
$ vim setup.py
Add below line to line 7:
os.environ['INSTALL_ON_LINUX'] = '1'
Try again:
$  sudo python setup.py install
log >>>
/usr/local/lib/python3.7/site-packages/setuptools/dist.py:484: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing xlwings.egg-info/PKG-INFO
writing dependency_links to xlwings.egg-info/dependency_links.txt
....
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing xlwings-dev-py3.7.egg
removing '/usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg' (and everything under it)
creating /usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg
Extracting xlwings-dev-py3.7.egg to /usr/local/lib/python3.7/site-packages
xlwings dev is already the active version in easy-install.pth
Installing xlwings script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg
Processing dependencies for xlwings===dev
Finished processing dependencies for xlwings===dev

Seems works, goon to run my python code
[Step5] Run python code
$ python ./diskdiffu/storage/excel.py
Traceback (most recent call last):
  File "./diskdiffu/storage/excel.py", line 21, in <module>
    import xlwings as xw
  File "/usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg/xlwings/__init__.py", line 11,in <module>
    from . import _xlmac as xlplatform
  File "/usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg/xlwings/_xlmac.py", line 9, in<module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
[Step6] Install psutil
$ sudo pip install psutil
Run code to test:
$ python ./diskdiffu/storage/excel.py
$ python ./diskdiffu/storage/excel.py
Traceback (most recent call last):
  File "./diskdiffu/storage/excel.py", line 21, in <module>
    import xlwings as xw
  File "/usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg/xlwings/__init__.py", line 11,in <module>
    from . import _xlmac as xlplatform
  File "/usr/local/lib/python3.7/site-packages/xlwings-dev-py3.7.egg/xlwings/_xlmac.py", line 10, in <module>
    import aem
ModuleNotFoundError: No module named 'aem'
'aem' is not a distribution, unable to go on.

How can I fix this issue, or xlwings unable to be used on Linux actually?

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Yes, xlwings only works on Windows and macOS as the error says: `OSError: xlwings requires an installation of Excel and therefore only works on Windows and macOS.`
