### ISSUE TITLE
error while using SQL queries on Excel ranges (with add-in)

### ISSUE THREAD

**Issue by fspwf** [xlwings/xlwings#1287]
OS: Windows 10

xlwings: 0.18.0, Excel: 2016, Python: 3.6.10

Issue:
I have install xlwings $ its add-in successfully, but failed to run sql query with the error message: ImportError: DLL load failed: The specified module could not be found. from _sqlite3 import * File... (details see the below attached png).
I have tried different version of xlwings (such as 0.17.1, 0.16.6), Excel 2016 (32 or 64-bit) and Python (3.7 or 3.8), the same errors. I also confirmed that sqlite has been installed in python.  
![1](https://user-images.githubusercontent.com/17793486/78359346-8061a700-75e7-11ea-9795-d37564a3309a.PNG)
![2](https://user-images.githubusercontent.com/17793486/78360105-da16a100-75e8-11ea-8ecf-bffedaab6568.PNG)

python trace back as below:
xlwings server running, clsid={AC2DD31B-95CD-4D23-BAB4-C05478DEEA88}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\xlwings\server.py", line 195, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\xlwings\udfs.py", line 239, in call_udf
    module = get_udf_module(module_name)
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\xlwings\udfs.py", line 212, in get_udf_module
    module = import_module(module_name)
  File "C:\Users\wpan1\.conda\envs\test\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\xlwings\ext\__init__.py", line 1, in <module>
    from .sql import sql, sql_dynamic
  File "C:\Users\wpan1\.conda\envs\test\lib\site-packages\xlwings\ext\sql.py", line 2, in <module>
    import sqlite3
  File "C:\Users\wpan1\.conda\envs\test\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\wpan1\.conda\envs\test\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by fzumstein** [comment]
You will need to leave the interpreter empty and point `Conda Base` to the path of your Anaconda/miniconda installation, see: https://docs.xlwings.org/en/stable/addin.html#global-settings

**Comment by fspwf** [comment]
thanks, it works now.
