### ISSUE TITLE
pywintypes.com_error

### ISSUE THREAD

**Issue by srinivasaai** [xlwings/xlwings#1291]
Windows 10
xlwings version 0.18.0  Python version  3.7.6

I am trying to capture live feed of data from an excel cell where data updates every second and write the captured data to a fresh sheet with time stamp every second and append the new record
in the last row.
code is running fine for some time but it stops and gives me the following error.
i am new to coding. request to help me in solving the issue. 
as an when i rerun the code it starts from first row and write on the old data .

```python
# Your traceback here
Traceback (most recent call last):
  File "C:/Users/srini/PycharmProjects/stockdatayahoo/importfmexcel.py", line 24, in <module>
    wb = xw.Book('pi_streamed_data.xlsx')
  File "C:\Users\srini\PycharmProjects\stockdatayahoo\venv\lib\site-packages\xlwings\main.py", line 511, in __init__
    for wb in app.books:
  File "C:\Users\srini\PycharmProjects\stockdatayahoo\venv\lib\site-packages\xlwings\main.py", line 61, in __iter__
    for impl in self.impl:
  File "C:\Users\srini\PycharmProjects\stockdatayahoo\venv\lib\site-packages\xlwings\_xlwindows.py", line 454, in __iter__
    for xl in self.xl:
  File "C:\Users\srini\PycharmProjects\stockdatayahoo\venv\lib\site-packages\xlwings\_xlwindows.py", line 173, in __iter__
    for v in self._inner:
  File "C:\Users\srini\PycharmProjects\stockdatayahoo\venv\lib\site-packages\win32com\client\dynamic.py", line 256, in __getitem__
    return self._get_good_object_(self._oleobj_.Invoke(dispid, LCID, invkind, 1, index))

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

**Comment by srinivasaai** [comment]
CLOSE
