### ISSUE TITLE
Installation: VBA "Error 62" by running my project.py file

### ISSUE THREAD

**Issue by sjcapferrat** [xlwings/xlwings#1321]
macOS 10.15.4 (Catalina)
xlwings 0.19.4, Office 365 w/ Excel 2016, Python 3.7

"Error 62" occurred trying to run "myproject.xlsm" downloaded via "xlwings quickstart myproject" command. 

https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/input-past-end-of-file-error-62

FYI, I confirmed my Excel add-in seems properly enabled (both in Excel>Tools>add-inselection and VBA library file). I have upgraded xlwings to 0.19.4 from Anaconda-preinstalled 0.17.1 via "pip install --upgrade xlwings" 

Can you see what went wrong here?

**Comment by fzumstein** [comment]
Looks similar to this one: https://github.com/xlwings/xlwings/issues/850 Can you check your `~/.xlwings/xlwings.conf` file and fix it so that there is one `"",""` pair per line?

**Comment by sjcapferrat** [comment]
Thank you for your advice. Error62 looks now gone for good but I hit another VBA error below.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "(~)/myproject.py", line 1, in <module>
    import xlwings as xw
ImportError: No module named xlwings

This looks a bit odd as I made sure both myproject.xlsm and myproject.py file are exactly in the same folder.

My xlwings.conf file has one line code as below (after addressing what you advised);
"PYTHONPATH","/Uses/(my name ID)/Documents/test_xlwings/myproject.py"
Also, I found my xlwings.conf file in "~/Library/Containers/com.microsoft.Excel/Data/xlwings.conf" as exactly mentioned in "https://docs.xlwings.org/en/stable/addin.html#xlwings-addin"

Lastly, should this code start with "INTERPRETER" instead as I do not wish to change the PYTHONPATH every time I run both (same name).xlms and (same name).py files which are in the same folder going forward.

**Comment by fzumstein** [comment]
Sorry about the wrong config location. the one from the docs is obviously the correct one as you found out. I am planning to add an auto configuration for the settings with the next release to get rid of these kind of issues once and for all:

* you won't need to set a pythonpath if your python file is next to the excel file
* Interpreter has to point to the python interpreter you're using, so something like `/.../python`

**Comment by sjcapferrat** [comment]
Wonderful - it looks like you have done already by 0.19.5!
