### ISSUE TITLE
Command Error (-1743) when calling a new book

### ISSUE THREAD

**Issue by etesei** [xlwings/xlwings#1323]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Catalina
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
(0.19.4, Office 365, 3.7)
#### Describe your issue (incl. Traceback!)
Simply trying to access a workbook, or create a workbook using xw.Book()
```python
# Your traceback here
Traceback (most recent call last):

  File "<ipython-input-68-d2cd48402785>", line 1, in <module>
    wb = xw.Book()

  File "/Users/evantesei/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 532, in __init__
    wb.sheets[0].range('A1').value = 1

  File "/Users/evantesei/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 2747, in add
    return Book(impl=self.impl.add())

  File "/Users/evantesei/anaconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 189, in add
    xl = self.app.xl.make(new=kw.workbook)

  File "/Users/evantesei/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 496, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e

CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: OS error
		COMMAND: app(pid=26491).make(new=k.workbook)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

import xlwings as xw
wb = xw.Book()

```

**Comment by fzumstein** [comment]
This means, that your application doesn't have the required access rights on macOS, see: #967 and also #1073, #1074, #1262, #1266. Please reopen if you cant solve the issue with the instructions on these issues.
