### ISSUE TITLE
OSError: [WinError -2147467259] Unspecified error

### ISSUE THREAD

**Issue by mchen22** [xlwings/xlwings#1327]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.19.4; Microsoft Excel 2016 and Python 3.6

#### Describe your issue (incl. Traceback!)
The code has always been working fine until earlier today. It seems that xlwings are not able to activate Excel windows anymore, but I couldn't think of anything that I've done to make it stop working all of sudden. 

**Traceback**
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2020.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "H:/Project/BBG/email_script/Main", line 86, in <module>
    test = get_file()
  File "H:/Project/BBG/email_script/Main", line 68, in get_file
    xw.Book(r'C:\blp\API\Office Tools\BloombergUI.xla')
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\main.py", line 514, in __init__
    for wb in app.books:
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\main.py", line 368, in books
    return Books(impl=self.impl.books)
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\_xlwindows.py", line 392, in books
    return Books(xl=self.xl.Workbooks)
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\_xlwindows.py", line 313, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\_xlwindows.py", line 223, in get_xl_app_from_hwnd
    ptr = accessible_object_from_window(child_hwnd)
  File "C:\ProgramData\Anaconda3\envs\mc2\lib\site-packages\xlwings\_xlwindows.py", line 193, in accessible_object_from_window
    byref(IDispatch._iid_), byref(ptr))
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147467259] Unspecified error
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```
import win32com.client
from win32com.client.gencache import EnsureDispatch as Dispatch
import xlwings as xw
import pandas as pd
import os
import sys

file_save_at = 'N:\T'
mapi = win32com.client.gencache.EnsureDispatch("Outlook.Application").GetNamespace("MAPI")

def get_file():
    files_toprocess = set()
    paths = [file_save_at]
    for p in paths:
        if os.path.isfile(p) and p.endswith('.xlsx'):
            files_toprocess.add(p)
        elif os.path.isdir(p):
            for root, dirs, files in os.walk(p):
                files_toprocess.update([os.path.join(root, f) for f in files if f.endswith('.xlsx')])

    axes_df = pd.DataFrame()

    for file in files_toprocess:
        xw.Book(r'C:\blp\API\Office Tools\BloombergUI.xla')
        wb = xw.Book(file)
        sht = wb.sheets(1)
        sht.activate()
        df = sht.cells(1, 1).current_region.options(pd.DataFrame, index=False, header=1).value
        df = df.dropna(axis = 0, thresh = 1)
        df['dlr'] = file.split('_')[3]
        df2 = pd.concat([df2, df])
        wb.close()
        print(df2)

    df2.sort_values(['S','B','A'])
    df2.to_csv(file_save_at + 'file.csv')
    return df2

```

**Comment by fzumstein** [comment]
using `activate()` is almost never necessary and should be avoided. Can't you just take it out?

**Comment by mchen22** [comment]
> using `activate()` is almost never necessary and should be avoided. Can't you just take it out?

I can but I don’t think that was the cause. The code broke at xw.Book(...). It couldn’t launch an excel instance.

**Comment by mchen22** [comment]
The issue seemed solved after I rebooted my PC. Thanks anyway!

**Comment by fzumstein** [comment]
gotcha, yeah that always helps on Windows ;)

**Comment by awa5114** [comment]
Rebooting doesn't fix it for me.

**Comment by jy247** [comment]
I'm getting the same issue, it always happens when I try and close a file and then open a second file within a process.  I don't see this problem when running python in debug mode so it might be about timings.

I have started to see the error after moving on to Excel 2016, so it might be connected to the single session environment.  

After some experimentation I found that moving from App.Quit() to wb.Close(), solved the problem.

**Comment by 1504168** [comment]
I get the same error when I am recording my screen using Camtasia 2021.

Here is the error message.
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "excel.py", line 7, in solve_model
  File "xlwings\main.py", line 913, in __init__
  File "xlwings\main.py", line 519, in books
  File "xlwings\_xlwindows.py", line 691, in books
  File "xlwings\_xlwindows.py", line 578, in xl
  File "xlwings\_xlwindows.py", line 321, in get_xl_app_from_hwnd
  File "xlwings\_xlwindows.py", line 294, in accessible_object_from_window
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2147467259] Unspecified error
```
