### ISSUE TITLE
TypeError: Don't know what to do with that image object

### ISSUE THREAD

**Issue by ikeepgettingerrors** [xlwings/xlwings#1330]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.19.4
python 3.8.3
matplotlib 3.1.3
#### Describe your issue (incl. Traceback!)
I am following your web course on xlwings and tried to replicate the code you have in Jupyter in PyCharm. The below code is pulled directly from the video course. Seems like I'm getting a TypeError. Any advice?
```python
# Your traceback here
Traceback (most recent call last):
  File "<input>", line 14, in <module>
  File "C:\Users\me\Anaconda3\envs\Standard\lib\site-packages\xlwings\main.py", line 2630, in add
    filename, width, height = utils.process_image(image, width, height)
  File "C:\Users\me\Anaconda3\envs\Standard\lib\site-packages\xlwings\utils.py", line 202, in process_image
    raise TypeError("Don't know what to do with that image object")
TypeError: Don't know what to do with that image object
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
```python
# Your code here
mfc_wb = xl.Book(mfc_model_path)
graph = mfc_wb.sheets['Charts']

years = [1, 2, 3, 4, 5, 7, 10]
swap_rate = [0.0079, 0.0094, 0.0107, 0.0119, 0.013, 0.0151, 0.0174]
years_new = np.linspace(1, 10, num=10)
interpolate = interp1d(years, swap_rate, kind='quadratic')

fig = plt.figure(figsize=(6, 4))
swaprate_plot = plt.plot(years, swap_rate, 'o', years_new, interpolate(years_new), '-')

plot = graph.pictures.add(fig, name='SwapRate', update=True)
```

**Comment by fzumstein** [comment]
Unfortunately, I can't reproduce this issue. I ran the following code (slightly adjusted from your version to be self contained) in PyCharm with the versions you state and it works fine for me:

```
import xlwings as xl
import numpy as np
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt


mfc_wb = xl.Book()
graph = mfc_wb.sheets[0]

years = [1, 2, 3, 4, 5, 7, 10]
swap_rate = [0.0079, 0.0094, 0.0107, 0.0119, 0.013, 0.0151, 0.0174]
years_new = np.linspace(1, 10, num=10)
interpolate = interp1d(years, swap_rate, kind='quadratic')

fig = plt.figure(figsize=(6, 4))
swaprate_plot = plt.plot(years, swap_rate, 'o', years_new, interpolate(years_new), '-')

plot = graph.pictures.add(fig, name='SwapRate', update=True)
```

**Comment by ikeepgettingerrors** [comment]
Thanks Felix, for your quick reply. After a couple restarts, the code above works for me now too. Wonder what the issue was. 

Vielen Dank!
