### ISSUE TITLE
would you please send me chinese .po file for updating translation

### ISSUE THREAD

**Issue by efreeway** [xlwings/xlwings#1354]
while trying to update chinese translation, using "sphinx-build -b gettext . _build/gettext", I got the error messages as bellow, :

_D:\@temp\xlwings2\docs>sphinx-build -b gettext . _build/gettext
Running Sphinx v2.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\config.py", line 361,
in eval_config_file
    execfile_(filename, namespace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx\util\pycompat.py", lin
e 81, in execfile_
    exec(code, _globals)
  File "D:\@temp\xlwings2\docs\conf.py", line 104, in <module>
    import xlwings
  File "D:\@temp\xlwings2\xlwings\__init__.py", line 31, in <module>
    from . import pro
  File "D:\@temp\xlwings2\xlwings\pro\__init__.py", line 9, in <module>
    from .embedded_code import runpython_embedded_code
  File "D:\@temp\xlwings2\xlwings\pro\embedded_code.py", line 11, in <module>
    LicenseHandler.validate_license('pro')
  File "D:\@temp\xlwings2\xlwings\pro\utils.py", line 50, in validate_license
    cipher_suite = LicenseHandler.get_cipher()
  File "D:\@temp\xlwings2\xlwings\pro\utils.py", line 19, in get_cipher
    return Fernet(os.getenv('XLWINGS_LICENSE_KEY_SECRET'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\cryptography\fernet.py", line
 35, in __init__
    key = base64.urlsafe_b64decode(key)
  File "C:\ProgramData\Anaconda3\lib\base64.py", line 131, in urlsafe_b64decode
    s = _bytes_from_decode_data(s)
  File "C:\ProgramData\Anaconda3\lib\base64.py", line 46, in _bytes_from_decode_
data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType_
'

would you please send me the updated .po files generated using follow motheds:
sphinx-build -b gettext . _build/gettext
sphinx-intl update -p _build/gettext -l zh_CN

thanks a lot.
```

**Comment by fzumstein** [comment]
Can you please pull again from master? this should be fixed now
