### ISSUE TITLE
'Call was rejected by callee.'

### ISSUE THREAD

**Issue by acollins782** [xlwings/xlwings#1359]
OS Windows 8.1

Versions of xlwings 0.17.1, Excel 2013 Python 3.7.6

With the Excel running and the sheet open, almost every time on startup I get the following error. Restarting the python app  again doesn't lead to the error, i.e. it is not reliably reproducible.

```python
Traceback (most recent call last):
  File "C:\Users\smtpGateway80\anaconda3\lib\runpy.py", line 193, in _run_module
_as_main
    "__main__", mod_spec)
  File "C:\Users\smtpGateway80\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\prod\pace\ovTest.py", line 3593, in <module>
    _excel_open = init_excel(excel_data_filepath)
  File "F:\prod\pace\ovTest.py", line 485, in init_excel
    dwb = xw.Book(excel_data_filepath)
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\xlwings\main.py", lin
e 511, in __init__
    for wb in app.books:
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\xlwings\main.py", lin
e 61, in __iter__
    for impl in self.impl:
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\xlwings\_xlwindows.py
", line 454, in __iter__
    for xl in self.xl:
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\xlwings\_xlwindows.py
", line 173, in __iter__
    for v in self._inner:
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\win32com\client\dynam
ic.py", line 252, in __getitem__
    return self._get_good_object_(self._enum_.__getitem__(index))
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\win32com\client\util.
py", line 37, in __getitem__
    return self.__GetIndex(index)
  File "C:\Users\smtpGateway80\anaconda3\lib\site-packages\win32com\client\util.
py", line 53, in __GetIndex
    result = self._oleobj_.Next(1)
pywintypes.com_error: (-2147418111, 'Call was rejected by callee.', None, None)

```

**Comment by fzumstein** [comment]
Can you add the sample code please?

**Comment by acollins782** [comment]
I didn't add any sample code because it fails on such a simple statement and also because it is not reproducible. I posted the issue in case somebody else can reproduce it. A few days ago it gave that error two or three times in a row on startup. Today it worked immediately. Only other thing that might be causing this is the fact that the spreadsheet is on a imDisk RamDisk. FWIW the code where the error occurs is as follows:

    try:
        dwb = xw.Book(excel_data_filepath)
        excel_data_sheet = dwb.sheets[excel_sheet_name]
        _excel_open = True
    except OSError as e:
        print("xlWings error: ",e)
        return False

The values for the two parameters are as follows:
excel_data_filepath = r'X:\D1 Spreadsheet.xls'
excel_sheet_name = 'Sheet1'

**Comment by acollins782** [comment]
Another reason why this might be happening is that my spreadsheet has a heavy backend component where it goes out and fetches data from the web and via DDE. Is it possible that the call to xlwings is timing out? Not really sure, just throwing it out there as a suggestion. Thanks.

**Comment by fzumstein** [comment]
yes, that can happen - try to set `dwb.app.display_alerts = False`

**Comment by acollins782** [comment]
xlwings fails on the very first line:

dwb = xw.Book(excel_data_filepath)

The suggested code relies on a value for dwb so I can't see that working when it doesn't even get beyond the first line of code. Last few days have been without this issue. As I stated, this does not happen on a regular basis and IMO it is most likely a timing issue. Maybe xlwings should have a timeout parameter - something like wait 2 secs: dwb = xw.Book(excel_data_filepath,2). Thanks.

**Comment by fzumstein** [comment]
Looking at it again, it's pretty obvious that Excel is busy when you try to open the book. It's a bit odd, as we're basically retrying when that error happens. For now, you might just retry on your end a few times until it can connect.

**Comment by mahesh-solanke** [comment]
I was tackling this issue for a long time,
today I got a solution for this, we can skip this using try-catch block

for example:

from pywintypes import com_error

try:
     your code
except com_error as e:
        pass 

hope this will help

thanks,
Mahesh
