### ISSUE TITLE
xlwing and reading Pickle files

### ISSUE THREAD

**Issue by hkeidesen** [xlwings/xlwings#1371]
Hi, 

I am currently working on getting an already working script to work with xlwings, however, I stumbled with reading files (a pickle file in this case)

#### Description
When using pickle files, I get the error as seen in the traceback below. Basically, when using Pandas to read the pickle, it fails to find the file, although the file is in the same working directory as the file Excel reads in xlwings (using the relative path). 

```python


---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\######\report_classifier_api\projectname\ProjectName.py", line 13, in main

    all_results_df = classifier.main('URL/')        

  File "c:\users\######\report_classifier_api\projectname\classifier.py", line 610, in main

    find_relevant_info_on_web(url_soup, report)

  File "c:\users\######\report_classifier_api\projectname\classifier.py", line 523, in find_relevant_info_on_web

    dev_category = category_prediction(dev_text)

  File "c:\users\######\report_classifier_api\projectname\classifier.py", line 496, in category_prediction

    X_train = pd.Series(pd.read_pickle("X_train.pkl"))

  File "C:\Users\######\Anaconda3\envs\api_env\lib\site-packages\pandas\io\pickle.py", line 170, in read_pickle

    f, fh = get_handle(fp_or_buf, "rb", compression=compression, is_text=False)

  File "C:\Users\######\Anaconda3\envs\api_env\lib\site-packages\pandas\io\common.py", line 461, in get_handle

    f = open(path_or_buf, mode)

FileNotFoundError: [Errno 2] No such file or directory: 'X_train.pkl'

```

#### The part where the code fails:

```python
X_train = pd.Series(pd.read_pickle("X_train.pkl"))

```

**Comment by hkeidesen** [comment]
I fixed the issue by using the absolute path, e.g.:
`X_train = pd.Series(pd.read_pickle(r"C:\Users\######\report_classifier_api\ProjectName\X_train.pkl"))`

Might as well not be xlwings causing the error, but this solution could work for any other experiencing similar behavior.
