### ISSUE TITLE
UDFs: AttributeError: Range.CLSID

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1404]
@njwhite, something must have slipped through my testing, but from 0.20.0 I now get below error when using legacy dynamic arrays: 

```
import xlwings as xw
import numpy as np

@xw.func
@xw.ret(expand='table')
def dynamic_array(r, c):
    return np.random.randn(int(r), int(c))
```

```
xlwings server running, clsid={DCD5ED5F-A373-46CF-BDE8-7C5E145A28B9}, event loop on 11612
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "c:\users\felix\dev\xlwings\xlwings\server.py", line 198, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "c:\users\felix\dev\xlwings\xlwings\udfs.py", line 517, in call_udf
    target_range=ComRange(target_range),
  File "c:\users\felix\dev\xlwings\xlwings\udfs.py", line 246, in __init__
    self._ser_resultCLSID = self._impl.api.CLSID
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: Range.CLSID
```

**Comment by njwhite** [comment]
@fzumstein i bet your gen_py directory doesn’t have a Range.py file any more

**Comment by fzumstein** [comment]
I also thought on that - it's what we [already came across](https://github.com/xlwings/xlwings/pull/1318#issuecomment-644402371) during the PR, right? I'll check in a bit.

**Comment by fzumstein** [comment]
Right, so same issue and can be solved by:

1) Deleting `%TEMP%/gen_py`
2) Running
```
$ python
>>> makepy;makepy.main()
```
3) Selecting `Microsoft Excel (...) ` and clicking `OK`

**Comment by njwhite** [comment]
Why does gen_py get spontaneously deleted anyway? Is it pywin32  or the OS clearing temp files? If the latter, can the gen_py directory be moved by config to somewhere more permanent?

**Comment by fzumstein** [comment]
I had the same thoughts, will need to look into it.

**Comment by fzumstein** [comment]
The version dependency [here](https://github.com/xlwings/xlwings/blob/master/xlwings/udfs.py#L240-L246) seems to have been a wrong conclusion. It's rather whether or not the gen_py has been generated or not.

**Comment by fzumstein** [comment]
@njwhite Pending further testing, but #1406 looks like it's solving the issue. The makepy also explains the time difference mentioned [here](https://github.com/xlwings/xlwings/pull/1318#issuecomment-638482313).

**Comment by Colin-b** [comment]
I confirm it solves the issue.

**Comment by fzumstein** [comment]
awesome, thanks for testing, @Colin-b !

**Comment by njwhite** [comment]
@fzumstein found it [here](https://github.com/mhammond/pywin32/blob/c1e4368d421567bc4f138e9c28f6d01ba8de425a/com/win32com/client/gencache.py#L62). If there’s a transient IO error on module load the gencache gets wiped and rebuilt (but no Excel specific classes are regenerated)

**Comment by fzumstein** [comment]
thanks @njwhite , yes couldn't really figure out when the Excel specific files like `Range.py` were generated or not, but they don't seem to be required for our purposes.

**Comment by mahaoyu** [comment]
Hi, I seem to be facing a similar issue now (see stack trace below).
For context, I'm using xlwings in an Excel Add-in project.

This worked fine for months, but now suddenly showed up w/o much warning on xlwings v0.23.0.
I removed, uninstalled the add-in, and upgraded it to v0.24.2 - still facing same issue.

Tried deleting and re-generating my %TEMP%/gen_py folder. Only see two files there: __init__.py and dicts.dat (I think I used to see a larger one with a very long name - possibly the typelib from gencache.py?), which I don't see anymore.

Would you have any advice around this?

Thanks a lot in advance,
Matthias

AttributeError: Range.CLSID
    raise AttributeError("%s.%s" % (self._username_, attr))
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\dynamic.py", line 511, in __getattr__
    self._ser_resultCLSID = self._impl.api.CLSID
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\xlwings\udfs.py", line 241, in __init__
    ComRange(xw_caller),
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\xlwings\udfs.py", line 493, in call_udf
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\xlwings\server.py", line 198, in CallUDF
    return func(*args)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_

**Comment by fzumstein** [comment]
These two lines should take care of generating the required files, what happens if you run them manually after deleting the gen_py folder? https://github.com/xlwings/xlwings/blob/master/xlwings/__init__.py#L48-L49

**Comment by mahaoyu** [comment]
Thanks for your quick feedback @fzumstein 

I get the following error: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\gencache.py", line 515, in EnsureModule
    module = MakeModuleForTypelib(typelibCLSID, lcid, major, minor, progressInstance, bForDemand = bForDemand, bBuildHidden = bBuildHidden)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\gencache.py", line 284, in MakeModuleForTypelib
    makepy.GenerateFromTypeLibSpec( (typelibCLSID, lcid, major, minor), progressInstance=progressInstance, bForDemand = bForDemand, bBuildHidden = bBuildHidden)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\makepy.py", line 279, in GenerateFromTypeLibSpec
    gen.generate(fileUse, bForDemand)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\genpy.py", line 822, in generate
    self.do_generate()
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\genpy.py", line 885, in do_generate
    oleItems, enumItems, recordItems, vtableItems = self.BuildOleItemsFromType()
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\genpy.py", line 750, in BuildOleItemsFromType
    oleItem, vtableItem = self._Build_Interface(type_info_tuple)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\genpy.py", line 718, in _Build_Interface
    oleItem = DispatchItem(info, attr, doc)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\genpy.py", line 270, in __init__
    build.DispatchItem.__init__(self, typeinfo, attr, doc)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\build.py", line 115, in __init__
    self.Build(typeinfo, attr, bForUser)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\build.py", line 263, in Build
    self._AddFunc_(typeinfo,fdesc,bForUser)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\build.py", line 176, in _AddFunc_
    typerepr, resultCLSID, resultDoc = _ResolveType(typerepr, typeinfo)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\build.py", line 434, in _ResolveType
    subrepr, sub_clsid, sub_doc = _ResolveType(subrepr, itypeinfo)
  File "C:\Users\mhansal\Miniconda3\envs\lf\lib\site-packages\win32com\client\build.py", line 450, in _ResolveType
    resultTypeInfo = itypeinfo.GetRefTypeInfo(subrepr)
pywintypes.com_error: (-2147319765, 'Element not found.', None, None)

**Comment by fzumstein** [comment]
You can find the same error mentioned here, but without much clue as to why it happens/how to resolve it: https://mail.python.org/pipermail/python-win32/2008-February/006864.html

**Comment by mahaoyu** [comment]
Thanks @fzumstein - just to add to this:
It appears that this is only a problem for asynchronous UDFs, i.e. functions with the following decorators:
@xw.func(async_mode='threading')

**Comment by fzumstein** [comment]
yes, it's only used there and with legacy dynamic arrays.

**Comment by mahaoyu** [comment]
thanks. if it's only used there with legacy dynamic arrays, is there another way to enable asynchronous functions?

**Comment by fzumstein** [comment]
Only used with legacy dynamic arrays *and* async functions... No, no easy fix for this right now, we'd need to see if there's a way to get away without relying on CLSID I guess...

**Comment by mahaoyu** [comment]
Ok thanks for the context

**Comment by mahaoyu** [comment]
@fzumstein do you think this is worth setting up as a separate issue? 
the asynchronous UDFs have been quite useful for the project/context in which I was using this. I don't know how quickly I could make any contribution here, but would certainly be keen to take a look or at least help support with testing/investigating any workaround.

**Comment by NicholasSiemons** [comment]
@fzumstein thanks for providing context on this issue. I was wondering if there had been any more updates? I am currently running xlwings 0.27.15 and I get this issue when trying to use asynchronous UDFs. It also occurs in 0.28.1.  I have attempted deleting the gen_py file, but it is re-written whenever I attempt to run an asynchronous UDF.

**Comment by fzumstein** [comment]
No, I haven't made any progress on this, unfortunately. But you do want the gen_py to be regenerated. If it fails, then it is because it doesn't find the definition in there. Deleting it (with automatic re-generation) sometimes fixes a faulty file in gen_py.

**Comment by NicholasSiemons** [comment]
Thanks! Good luck in sorting this issue.

**Comment by huapeiyou** [comment]
When I run `=plot(A4#, "History")` according to the textbook instructions, I get the following error:
`AttributeError: Range.CLSID
    raise AttributeError("%s.%s" % (self._username_, attr))
  File "D:\soft_install\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 639, in __getattr__
    self._ser_resultCLSID = self._impl.api.CLSID
  File "D:\soft_install\Anaconda3\lib\site-packages\xlwings\udfs.py", line 250, in __init__
    args[info["pos"]] = ComRange(xw_caller)
  File "D:\soft_install\Anaconda3\lib\site-packages\xlwings\udfs.py", line 427, in call_udf
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "D:\soft_install\Anaconda3\lib\site-packages\xlwings\com_server.py", line 235, in CallUDF
    return func(*args)
  File "D:\soft_install\Anaconda3\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "D:\soft_install\Anaconda3\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "D:\soft_install\Anaconda3\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_`

I don't know how to fix this error.
Delete the gen_py folder and rerun it? It doesn't work.
I'm not a programmer, and I want advice that's easy to understand.
Thank you!

**Comment by fzumstein** [comment]
@huapeiyou you should be able to get around this issue by leaving out the caller:

```python
@xw.func
@xw.arg("df", pd.DataFrame)
def plot(df, name): 
    plt.style.use("seaborn") 
    if not df.empty: 
        caller.sheet.pictures.add(df.plot().get_figure(), name=name, update=True) 
    return f"<Plot: {name}>" 
```

**Comment by huapeiyou** [comment]
@fzumstein According to your instructions, VS Code indicates that `"caller" is not defined` in the plot function, running the function only returns `<Plot: History>`, and does not return the target image object.
Please ignore the fact that I am new to programming.
![002C313B](https://github.com/xlwings/xlwings/assets/67533561/23fce9b1-adef-4f6e-9103-d6885346e320)

**Comment by fzumstein** [comment]
sorry, it should be like this:

```python
@xw.func
@xw.arg("df", pd.DataFrame)
def plot(df, name): 
    plt.style.use("seaborn") 
    if not df.empty: 
        xw.sheets.active.pictures.add(df.plot().get_figure(), name=name, update=True) 
    return f"<Plot: {name}>" 
```

**Comment by huapeiyou** [comment]
Thank you ,  The issue has been resolved.
But now I have a new problem.
I use the with statement to manipulate Excel objects like this: 
`with xw.Book("excel股票分表.xlsx") as wb:
    for sheet in wb.sheets:
        print(sheet.name)
        # 设置日期列单元格的格式
        sheet.range("A:A").number_format = "yyyy-mm-dd"
        chart = sheet.charts.add()
        chart.chart_type = 'line'
        chart.set_source_data(sheet.range("A1").expand())
        chart.name = "5/10周期均线图"
        sheet.range("H2").value = "5/10周期均线图"
        # 设置图表位置
        chart.left = sheet.range("F3").left
        chart.top = sheet.range("F3").top
        # 设置坐标轴名称
        chart.api[1].Axes(1).HasTitle = True  # X轴
        chart.api[1].Axes(1).AxisTitle.Text = '日期'
        chart.api[1].Axes(2).HasTitle = True  # Y轴
        chart.api[1].Axes(2).AxisTitle.Text = '价格'
        # 设置坐标轴标签倾斜度
        chart.api[1].Axes(1).TickLabels.Orientation = 30
    wb.save()`;
Excel does not exit when the with statement is finished, instead, leave an empty Excel program like this:
![1710250205306](https://github.com/xlwings/xlwings/assets/67533561/168bd7bb-9df0-4de4-9fa1-e9a8bf26ab57)

I can't handle it through use
`for app in xw.apps:
    app.quit()`
or
`xw.apps.active.quit()`,
the empty Excel program does not appear to be recognized by xlwings,
What should I do?
Looking forward to your reply!

**Comment by huapeiyou** [comment]
@fzumstein 
Thank you , The issue has been resolved.
But now I have a new problem.
I use the with statement to manipulate Excel objects like this:
```python
with xw.Book("excel股票分表.xlsx") as wb:
    for sheet in wb.sheets:
        print(sheet.name)
        # 设置日期列单元格的格式
        sheet.range("A:A").number_format = "yyyy-mm-dd"
        chart = sheet.charts.add()
        chart.chart_type = 'line'
        chart.set_source_data(sheet.range("A1").expand())
        chart.name = "5/10周期均线图"
        sheet.range("H2").value = "5/10周期均线图"
        # 设置图表位置
        chart.left = sheet.range("F3").left
        chart.top = sheet.range("F3").top
        # 设置坐标轴名称
        chart.api[1].Axes(1).HasTitle = True  # X轴
        chart.api[1].Axes(1).AxisTitle.Text = '日期'
        chart.api[1].Axes(2).HasTitle = True  # Y轴
        chart.api[1].Axes(2).AxisTitle.Text = '价格'
        # 设置坐标轴标签倾斜度
        chart.api[1].Axes(1).TickLabels.Orientation = 30
    wb.save()
```
Excel does not exit when the with statement is finished, instead, leave an empty Excel program like this:
![1710250205306](https://github.com/xlwings/xlwings/assets/67533561/cf8c7dc5-7f2a-4494-9d1c-66e0c59a4789)
I can't handle it through use
```python
for app in xw.apps:
    app.quit()
```
or 
```python
xw.apps.active.quit()
```
the empty Excel program does not appear to be recognized by xlwings,
What should I do?
Looking forward to your reply!
