### ISSUE TITLE
How to open and close an excel workbook in a python for loop using xlwings

### ISSUE THREAD

**Issue by awa5114** [xlwings/xlwings#1411]
I need to open and close the same workbook in a python `for` loop without necessarily saving the workbook. I tried the following in `xlwings`:

    import xlwings as xw
    
    for i in range(5):
        print(i)
        book = xw.Book()
        book.app.quit()

However this will only run for the first iteration. At the second iteration I get an error:

    Traceback (most recent call last):
      File "D:/TEMP/SE/python/ref.py", line 5, in <module>
        book = xw.Book('tree_template.xlsx')
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\main.py", line 533, in __init__
        for wb in app.books:
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\main.py", line 374, in books
        return Books(impl=self.impl.books)
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\_xlwindows.py", line 397, in books
        return Books(xl=self.xl.Workbooks)
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\_xlwindows.py", line 313, in xl
        self._xl = get_xl_app_from_hwnd(self._hwnd)
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\_xlwindows.py", line 222, in get_xl_app_from_hwnd
        ptr = accessible_object_from_window(child_hwnd)
      File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\SE\lib\site-packages\xlwings\_xlwindows.py", line 190, in accessible_object_from_window
        res = oledll.oleacc.AccessibleObjectFromWindow(
      File "_ctypes/callproc.c", line 948, in GetResult
    OSError: [WinError -2147467259] Unspecified error

Why does this occur? How can I get xlwings to exit out of the application without causing any problems?

**Comment by fzumstein** [comment]
In your current code sample, you open a new workbook and completely close out of the Excel app every time. You probably just want to use `book.close()` instead and move `app.quit()` out of the loop.

**Comment by awa5114** [comment]
@fzumstein I have tried that but it didnt work. Could you provide a working example?

**Comment by fzumstein** [comment]
What about:

```python
import xlwings as xw

app = xw.App()

for i in range(5):
    print(i)
    book = xw.Book()
    book.close()
app.quit()
```

**Comment by awa5114** [comment]
Oh I see. No I want to quit excel and reopen it at every iteration. In reality my for loop goes for hundreds of iterations.

**Comment by fzumstein** [comment]
Why? What's your use case?

**Comment by awa5114** [comment]
I open an excel spreadsheet, copy a number of sheets and fill in a number of values in each sheet before exporting to pdf and then closing...

Not being able to close the application after each iteration leaves me with dozens of "closed" workbooks which I have to close out of manually. 

Finally for a case in which I have to execute hundreds of iterations the closed workbooks would clog up my memory, eventually having a negative impact on the running of the script..

Is it clear or do you need more details than this?

**Comment by fzumstein** [comment]
> each iteration leaves me with dozens of "closed" workbooks which I have to close out of manually.

Sorry, don't understand this part. if `book.close()` doesn't close the book, there must be something going on.

**Comment by Scylla2020** [comment]
I think this is what happens when `app = xw.App()` is not declared, eg:
```
import xlwings as xw
for i in range(5):
    print(i)
    book = xw.Book()
    book.close()
```
This will open and close each book. However for each book opened, it will leave an instance of Excel open, so you'll have to manually close all 5 excel instances after the loop finishes.
