### ISSUE TITLE
While Importing XLWINGS - get the error:  "ImportError....._win32sysloader: %1...."

### ISSUE THREAD

**Issue by jschinter** [xlwings/xlwings#1441]
#### OS (e.g. Windows 10 or macOS Sierra) 
Windows 10 Home Ver 2014

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: xlwings64-0.19.5 
Python:  Python 3.8 (Within Anaconda3)
Excel: Not part of problem yet!

#### Describe your issue (incl. Traceback!)
When trying to "IMPORT XLWINGS" in python prompt I get the following error:
DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application

![Python xlwings import error](https://user-images.githubusercontent.com/61219809/97360189-d9d34100-186b-11eb-966f-44b9b4413cd2.jpg)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by meridorkobi** [comment]
The same

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\python38\lib\site-packages\PyInstaller\utils\win32\winutils.py", line 96, in import_pywin32_module
    module = __import__(
  File "C:\Users\PC\AppData\Roaming\Python\Python38\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Users\PC\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 136, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\PC\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 64, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.

**Comment by fzumstein** [comment]
Please see this thread for possible issues and solutions: https://github.com/jupyter/jupyter_core/issues/187
