### ISSUE TITLE
call xw.App(visible=True, add_book=True)  has pywintypes.com_error: (-2147024894, '系统找不到指定的文件。', None, None) error

### ISSUE THREAD

**Issue by sky800719** [xlwings/xlwings#1457]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.8.1
xlwings  0.21.0
WPS表格（11.1.0.10116)

#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\tool\Python38\lib\site-packages\xlwings\main.py", line 210, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book, visible=visible)
  File "D:\tool\Python38\lib\site-packages\xlwings\_xlwindows.py", line 313, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
  File "D:\tool\Python38\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
pywintypes.com_error: (-2147024894, '系统找不到指定的文件。', None, None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
>>> import xlwings as xw
>>> app=xw.App(visible=True,add_book=False)
```

**Comment by fzumstein** [comment]
Hi @sky800719, really sorry but xlwings only supports Microsoft Excel and not WPS.
