### ISSUE TITLE
pythoncom error: Python error invoking COM method (MacroOptions method of Application class failed)

### ISSUE THREAD

**Issue by barry-1928** [xlwings/xlwings#1468]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings==0.21.4
Excel 2016 64 bit
Python 3.8
#### Describe your issue (incl. Traceback!)
Clicking on "Import Functions" under UDFs tab gives the following error. Clicking on "Run main" works as expected(prints alternate “Hello xlwings!” and “Bye xlwings!” in cell A1).
```python
# Your traceback here
xlwings server running, clsid={754D8FD5-4478-4F26-9666-3A68F882F393}, event loop on 25744
pythoncom error: Python error invoking COM method.
 
Traceback (most recent call last):
  File "c:\users\bhatta\desktop\myvenv\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "c:\users\bhatta\desktop\myvenv\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "c:\users\bhatta\desktop\myvenv\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "c:\users\bhatta\desktop\myvenv\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "c:\users\bhatta\desktop\myvenv\lib\site-packages\xlwings\udfs.py", line 669, in import_udfs
    xl_workbook.Application.MacroOptions("'" + xl_workbook.Name + "'!" + fname,
  File "C:\Users\bhatta\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 43126, in MacroOptions
    return self._oleobj_.InvokeTypes(2770, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Macro
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'MacroOptions method of Application class failed', 'xlmain11.chm', 0, -2146827284), None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw


def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"


@xw.func
def hello(name):
    return f"Hello {name}!"


if __name__ == "__main__":
    xw.Book("C:/users/bhatta/Desktop/xlwings/demo.xlsm").set_mock_caller()
    main()

```

Can someone please check?

**Comment by bransonngai** [comment]
Seems I have a same config with you. And yet the same error :
Python error invoking COM method

**Comment by scath999** [comment]
Same problem, same config. For me, this was due to macros not being enabled.

The docs do solve this:

"1) Enable Trust access to the VBA project object model under File > Options > Trust Center > Trust Center Settings > Macro Settings"

https://docs.xlwings.org/en/stable/udfs.html#udfs

That solved it for me. Hope it helps.

**Comment by KESilverTide** [comment]
I have the same error on very different function. Not clear what is wrong here and how to trouble shoot it

**Comment by amo-mhp** [comment]
have this issue been solved?
I just encountered it with the following code:


import numpy as np
import xlwings as xw


@xw.func()
def diagrams(array):
    return array

---------------------------
Error
---------------------------
MacroOptions method of Application class failed 1004

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by fzumstein** [comment]
@amo-mhp `array` is a reserved word in VBA so you can't use it there. Try something like `arr` instead.
