### ISSUE TITLE
pywintypes.com_error: (-2147023266, '这个类型的数据不受支持。', None, None)

### ISSUE THREAD

**Issue by wanghong45676** [xlwings/xlwings#1480]
#### OS (e.g. Windows 10 or macOS Sierra)
win 10 
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version: 0.21.4

Traceback (most recent call last):
  File "g:/CX/jupyter notebook/newxwl.py", line 2, in <module>
    app=xw.App(visible=True,add_book=True)
  File "F:\ProgramData\Anaconda3\lib\site-packages\xlwings\main.py", line 210, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book, visible=visible)
  File "F:\ProgramData\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 299, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
  File "F:\ProgramData\Anaconda3\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
pywintypes.com_error: (-2147023266, '这个类型的数据不受支持。', None, None)

app=xw.App(visible=True,add_book=True)

**Comment by wanghong45676** [comment]
app=xw.App(visible=True,add_book=True)    unable to run

**Comment by fzumstein** [comment]
do you get the same error if you do `xw.Book()` ?

**Comment by wanghong45676** [comment]
I don't get the same error when I write xw.book()

**Comment by wanghong45676** [comment]
yes

**Comment by running1st** [comment]
do you solve the prolem? 
i meet the same question !
maybe we can have a word....

**Comment by fzumstein** [comment]
@running1st do you get the same error when running `xw.Book()`?

**Comment by running1st** [comment]
yes. I get the same error, when I use xw.w.Book() 
if I open one excel before running xw.Book() , the error dispappear . if I do nothing, the error is still there.
how can I deal this problem？

在 2021-09-28 23:04:24，"Felix Zumstein" ***@***.***> 写道：


@running1st do you get the same error when running xw.Book()?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
