### ISSUE TITLE
Encoding error after installing addin

### ISSUE THREAD

**Issue by hoeztutar** [xlwings/xlwings#1498]
Hello,

Today I have installed the Excel addin. After that I started to have encoding errors. I tried to uninstall too but it gives me an encoding error everytime I write xlwings. Is it a licencing issue? I could not see in the documentation that addin was a PRO feature.

Below traceback is from `import xlwings as xw`

```python
Traceback (most recent call last):
  File "<Some directory>/test.py", line 1, in <module>
    import xlwings as xw
  File "<Some directory>\Anaconda3\lib\site-packages\xlwings\__init__.py", line 31, in <module>
    from . import pro
  File "<Some directory>\Anaconda3\lib\site-packages\xlwings\pro\__init__.py", line 9, in <module>
    from .embedded_code import runpython_embedded_code
  File "<Some directory>\Anaconda3\lib\site-packages\xlwings\pro\embedded_code.py", line 11, in <module>
    LicenseHandler.validate_license('pro')
  File "<Some directory>\Anaconda3\lib\site-packages\xlwings\pro\utils.py", line 51, in validate_license
    key = LicenseHandler.get_license()
  File "<Some directory>\Anaconda3\lib\site-packages\xlwings\pro\utils.py", line 36, in get_license
    config = f.readlines()
  File "<Some directory>\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 34: character maps to <undefined>

```

**Comment by fzumstein** [comment]
No, it's not a PRO feature. I think your config file has been messed up. Run this on a command prompt to see if it resolves the issue:

```
xlwings config create --force
```

This will recreate the config file.

**Comment by hoeztutar** [comment]
Reinstalling xlwings and addin worked. you're right probably something with the config. 
Thanks anyways
