### ISSUE TITLE
'Characters' object is not callable

### ISSUE THREAD

**Issue by mrd2242** [xlwings/xlwings#1526]
#### Describe your issue (incl. Traceback!)
I want change the font of part of characters of a single cell. In vba, this code works:
```
With Worksheets("Sheet1").Range("A1") 
 .Value = "abcdefg" 
 .Characters(3, 1).Font.Bold = True 
End With
```
But in python: 
```python
import xlwings as xw

rng = xw.Range("A1")
rng.value = "abcdefg"
rng.api.Characters(3, 1).Font.Bold = True

# Your traceback here

Traceback (most recent call last):
  File "C:/Users/taiping/Desktop/taiping/common/excel/t.py", line 5, in <module>
    rng.api.Characters(3, 1).Font.Bold = True
  File "D:\python3.8\lib\site-packages\xlwings\_xlwindows.py", line 156, in __call__
    v = self._inner(*args, **kwargs)
TypeError: 'Characters' object is not callable
```

Thanks!

**Comment by fzumstein** [comment]
use `GetCharacters` instead. Also, this should be implemented soon natively.
