### ISSUE TITLE
Automation Error 440 while trying to import a new UDF

### ISSUE THREAD

**Issue by JargonPiHarston** [xlwings/xlwings#1531]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7 Pro x64
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings==0.20.1
Excel Professional Plus 2010
Python 3.7.7
#### Describe your issue (incl. Traceback!)
I can't import a new function that I added to the script I have been using without problem so far. Actually I have had this problem before with this exact script but I removed references to Python classes I wrote then it somehow works. Doing the same does not seem to be working this time anymore no matter what simplification I made to the new function get_fx_price(). I tried stripping the function until it actually does nothing yet it is still failed to be imported.

I did some digging and found that the error only occurs when function import_udfs() in udfs.py attempts to import get_fx_prices(). The other functions got imported just fine, one example of those also attached here.

```python
# Your traceback here
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Anaconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Anaconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Anaconda3\lib\site-packages\xlwings\server.py", line 194, in Call
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\Anaconda3\lib\site-packages\xlwings\udfs.py", line 671, in import_udfs
    ArgumentDescriptions=argdocs if argdocs else None)
  File "<COMObject <unknown>>", line 6, in MacroOptions
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'MacroOptions method of Application class failed', 'xlmain11.chm', 0, -2146827284), None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Works fine
@xw.func
@xw.arg('stock_1', doc='Stock 1')
@xw.arg('stock_2', doc='Stock 2')
@xw.arg('tenor', doc='Tenor in days')
def get_correlation(stock_1: str, stock_2: str, tenor: int, as_datetime: datetime.datetime, allows_hedging_vol: bool = True):
    # print("Receiving", stock_1, type(stock_1), stock_2, type(stock_2), tenor, as_datetime)
    if not isinstance(stock_1, str) or not isinstance(stock_2, str):
        # print("Returns None correlation")
        return None
    as_date = as_datetime.date()
    corr = phatra_db.get_correlation(stock_1, stock_2, int(tenor), as_date)
    if corr is None and allows_hedging_vol and (as_date == datetime.date.today()):
        as_date = Exchange('SET').busday_offset(as_date, -1)
        corr = phatra_db.get_correlation(stock_1, stock_2, int(tenor), as_date)
    return corr


# Can't import
@xw.func
def get_fx_price(currency: str,
                 quote_currency: str,
                 as_datetime: datetime.datetime,
                 symbol: str,
                 bank_code: str,
                 rate_type: str):
    if symbol != "":
        currency, quote_currency = symbol[0:3], symbol[3:6]
    '''sr = phatra_db.get_fx(as_date=as_datetime.date() if as_datetime is not None else None,
                          bank_code=bank_code,
                          currency=currency,
                          quote_currency=quote_currency,
                          rate_type=rate_type)'''
    sr = None
    return sr
    '''if isinstance(sr, pd.Series):
        return sr[sr.index.max()]
    else:
        return sr
        '''

```

**Comment by fzumstein** [comment]
You must not use any reserved VBA keywords as your arguments, `currency` is such a reserved keyword.

**Comment by JargonPiHarston** [comment]
Thanks for such swift reply. I did not know that before!
