### ISSUE TITLE
Names from a sheet are not completly deleted

### ISSUE THREAD

**Issue by silviulaurentiu** [xlwings/xlwings#1534]
#### Describe your issue (incl. Traceback!)

A have some names defined into a worksheet(sh) from a workbook (wb)
I tried to delete all defined names from the worksheet, but only half of them are deleted.
If I run the code again, withtout to close the workbook, half of half are deleted.
It seems that the index position is not moved.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
for def_name in sh.names:
  name = str.replace(def_name.name, 'SheetName' + '!', '')
  sh.names[name].delete()

I also tried to delete in this way:

for i in range(len(sh.names)):
  sh.names[i].delete()

but I got the same reuslt, only half of names are deleted at each cod run.

I also got some error on runing:

Traceback (most recent call last):
  File "D:\Test.py", line 113, in <module>
    PW_Loss_on_R()
  File "D:\Test.py", line 53, in PW_Loss_on_R
    for def_name in sh.names:
  File "D:\01.MyVirtEnv\lib\site-packages\xlwings\main.py", line 3408, in __iter__
    yield self(i + 1)
  File "D:\01.MyVirtEnv\lib\site-packages\xlwings\main.py", line 3344, in __call__
    return Name(impl=self.impl(name_or_index))
  File "D:\01.MyVirtEnv\lib\site-packages\xlwings\_xlwindows.py", line 1636, in __call__
    return Name(xl=self.xl(name_or_index))
  File "D:\01.MyVirtEnv\lib\site-packages\xlwings\_xlwindows.py", line 156, in __call__
    v = self._inner(*args, **kwargs)
  File "C:\Users\MyUser\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py", line 28744, in __call__
    ret = self._oleobj_.InvokeTypes(0, LCID, 1, (9, 0), ((12, 17), (12, 17), (12, 17)),Index
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

Process finished with exit code 1

My solution was to delete all names from the worksheet with below code, which works well:
for n in range(len(sh.names)):
  sh.names[0].delete()

Thank you for your wonderful work!

**Comment by fzumstein** [comment]
I think this is a dupe of #1400

**Comment by silviulaurentiu** [comment]
On xlwings 0.23.4 to delete the workbook defined names, I found this solution:
	```
if len(wb.names) > 1:
		#print(len(wb.names))
		for n in range(1, len(wb.names)):
			wb.names[1].delete()
```

**Comment by i-yuya-mb** [comment]
I also see the same issue on xlwings 0.31.5. The counter measure is to use list comprehension.   
```python
for n in [name for name in wb.names]:
    n.delete()
```
