### ISSUE TITLE
Cryptic error when running tutorial

### ISSUE THREAD

**Issue by Pipboyguy** [xlwings/xlwings#1539]
#### Windows 10

0.23.0, Office 365, Python  3.9.2

When I run the quickstart tutorial on https://docs.xlwings.org/en/stable/reports.html

```shell
python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    sheet = wb.sheets['template'].copy(name='report')
  File "C:\ProgramData\Miniconda3\envs\send_mails_env\lib\site-packages\xlwings\main.py", line 80, in __getitem__
    return self(key)
  File "C:\ProgramData\Miniconda3\envs\send_mails_env\lib\site-packages\xlwings\main.py", line 3878, in __call__
    return Sheet(impl=self.impl(name_or_index))
  File "C:\ProgramData\Miniconda3\envs\send_mails_env\lib\site-packages\xlwings\_xlwindows.py", line 572, in __call__
    return Sheet(xl=self.xl(name_or_index))
  File "C:\ProgramData\Miniconda3\envs\send_mails_env\lib\site-packages\xlwings\_xlwindows.py", line 156, in __call__
    v = self._inner(*args, **kwargs)
  File "...\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py", line 36625, in __call__
    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (9, 0), ((12, 1),),Index
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

```

with the contents of test.py being

```python
import xlwings as xw
wb = xw.Book('Book1.xlsx')
sheet = wb.sheets['template'].copy(name='report')
sheet.render_template(title='A Demo!', table=[[1, 2], [3, 4]])
wb.to_pdf()  # requires xlwings >=0.21.1
```

I am using the pro trial licence.

**Comment by Pipboyguy** [comment]
The above error ceases to appear when the sheet is either manually created or created via 
```python
wb.sheets.add("template")
```
Seems that 
```python
sheet = wb.sheets['template'] 
``` 
doesn't create the sheet in the workbook before it tries to instantiate the sheet object.

**Comment by fzumstein** [comment]
You're right, the code expects the workbook to be prepared as shown on the screenshot. I'll try to improve this!
