### ISSUE TITLE
Encountering pywintypes.com error

### ISSUE THREAD

**Issue by ElisonSherton** [xlwings/xlwings#1547]
Hi guys,

Good Day!

I am trying to use xlwings for linking vba with python to automate some stuff but I am encountering the following error. Could someone please look into the following and if they've faced an issue like this before, could you please get back to me?

Thanks & Regards,
Vinayak Nayak.
nayakvinayak95@gmail.com

```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 466, in __call__

    return Book(xl=self.xl(name_or_index))

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 156, in __call__

    v = self._inner(*args, **kwargs)

  File "C:\Users\sanjiv\AppData\Local\Temp\gen_py\3.6\00020813-0000-0000-C000-000000000046x0x1x8.py", line 39136, in __call__

    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (13, 0), ((12, 1),),Index

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "d:\documents\desktop\shares_closing_updater\Shares_Closing_Updater.py", line 11, in main

    wb = xw.Book.caller()

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\main.py", line 613, in caller

    return cls(impl=app.books[name].impl)

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\main.py", line 80, in __getitem__

    return self(key)

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\main.py", line 51, in __call__

    return self._wrap(impl=self.impl(name_or_index))

  File "C:\Users\sanjiv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 468, in __call__

    raise KeyError(name_or_index)

KeyError: 'd:\\documents\\desktop\\shares_closing_updater\\shares_closing_updater.xlsm'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```

**Comment by fzumstein** [comment]
Could you attach some sample code to reproduce? The error message sounds like it can't find the workbook.

**Comment by ElisonSherton** [comment]
Hi @fzumstein,

Thanks for the prompt reply. Here's my code below

```python
import pandas as pd
import numpy as np
import xlwings as xw
from datetime import datetime
from nsepy.history import get_price_list
from bsedata.bse import BSE

# Read the daily sheet shares file
def main():
    b = BSE()
    wb = xw.Book.caller()
    DATE = wb.sheets[0].range("B1").value
    
    # Get the price list for defined Date above
    price_list = get_price_list(DATE)
    price_list = price_list[["SYMBOL", "CLOSE", "ISIN"]]
    bse_scripts = []
    bse_sc = []

    # A one line function to return close price given ISIN
    get_close = lambda x: price_list[price_list.ISIN == x]["CLOSE"]
    
    Name = "XXX"
    share_row = 6

    while True:

        sheet_name = "dly"

        # Get the name of the stock
        Name = wb.sheets[sheet_name].range(f"G{share_row}").value
        
        # If the name is blank, then end the update
        if not Name:
            break
        
        # Get the ISIN Number of the stock
        ISIN = wb.sheets[sheet_name].range(f"B{share_row}").value
        ISIN = ISIN.strip()

        close_price = get_close(ISIN)

        # Copy current closing into previous closing
        wb.sheets[sheet_name].range(f"H{share_row}").value = wb.sheets[sheet_name].range(f"I{share_row}").value

        # Fetch the current closing and correspondingly populate the closing column for the day
        if len(close_price) > 0:
            wb.sheets[sheet_name].range(f"I{share_row}").value = float(close_price)
        else:
            wb.sheets[sheet_name].range(f"I{share_row}").value = "#NA"
            try:
                bse_code_number = wb.sheets[sheet_name].range(f"A{share_row}").value
                bse_code_number = str(int(bse_code_number)).strip()
                q = b.getQuote(bse_code_number)
                bse_sc.append(bse_code_number)
                bse_scripts.append({"Name": q["companyName"],
                                    "Close": q["currentValue"],
                                    "Prev Close":q["previousClose"],
                                    "52weekHigh":q["52weekHigh"],
                                    "52weekLow":q["52weekLow"]})
                
            except Exception as e:
                wb.sheets["BSE_Scripts"].range("A10").value = str(e)
                pass

        share_row += 1
    bse_df = pd.DataFrame(bse_scripts)
    wb.sheets["BSE_Scripts"].range("A1").value = bse_df
```

Apart from xlwings and standard python libraries, I have used a few external libraries as follows
1. [nsepy](https://nsepy.xyz/)
2. [bsedata](https://pypi.org/project/bsedata/)

I have kept the excel file and the python file in the same directory structure as well

![image](https://user-images.githubusercontent.com/45599762/111892285-fa20b980-8a1f-11eb-9443-caefebf388c8.png)

I am using MS Excel 13 and Windows 7 machine with python 3.6 installed on my local machine.

Hope this helps to reproduce the error. 

Thanks & Regards,
Vinayak Nayak.

**Comment by fzumstein** [comment]
maybe adding a `time.sleep(0.5)` at the end of your while True will help...

**Comment by ElisonSherton** [comment]
Hi @fzumstein 

I tried adding the above line of come by importing the time library but it still gives me the same error as above.


![error_message](https://user-images.githubusercontent.com/45599762/112317986-95d95080-8cd2-11eb-8c19-7cea36ee83ad.PNG)

Kindly have a look at this detailed error log and let me know if you find something here...

Thanks & Regards,
Vinayak

**Comment by fzumstein** [comment]
Try a quickstart example and see if that works?

**Comment by ElisonSherton** [comment]
Yes It did, thanks for the prompt response! 

The problem was that my workbook had gotten corrupt somehow and also the names of the sheets were mismatched from what I had in my python script.

Thanks & Regards,
Vinayak
