### ISSUE TITLE
xlwings issue with pywin32

### ISSUE THREAD

**Issue by jontankersley** [xlwings/xlwings#1638]
#### xlwings fails to run

```python
xlwings install addin
Traceback (most recent call last):
  File "C:\Users\jtankersley\AppData\Local\Programs\Python\Python39\Scripts\xlwings-script.py", line 33, in <module>
    sys.exit(load_entry_point('xlwings==0.23.4', 'console_scripts', 'xlwings')())
  File "C:\Users\jtankersley\AppData\Local\Programs\Python\Python39\Scripts\xlwings-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\jtankersley\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\jtankersley\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\jtankersley\appdata\local\programs\python\python39\lib\site-packages\xlwings\__init__.py", line 9, in <module>
    from . import _xlwindows as xlplatform
  File "c:\users\jtankersley\appdata\local\programs\python\python39\lib\site-packages\xlwings\_xlwindows.py", line 14, in <module>
    import pywintypes
  File "C:\Users\jtankersley\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 105, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\jtankersley\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 87, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes39.dll)
```

#### Possible solution!

Possible compatibility issue with default pwyin32 (300)

Ran 
``` python
pip install pywin32 --upgrade
Requirement already satisfied: pywin32 in c:\users\jtankersley\appdata\roaming\python\python39\site-packages (300)
Collecting pywin32
  Downloading pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 3.3 MB/s
Installing collected packages: pywin32
  Attempting uninstall: pywin32
    Found existing installation: pywin32 300
    Uninstalling pywin32-300:
      Successfully uninstalled pywin32-300
Successfully installed pywin32-301
```

##### xlwings works

```python
xlwings addin install
xlwings version: 0.23.4
Successfully installed the xlwings add-in! Please restart Excel.

```

**Comment by fzumstein** [comment]
These issues are often caused if you have multiple versions of pywin32 installed. Can you see if any of these suggestions help? https://stackoverflow.com/questions/65573140/importerror-no-system-module-pywintypes-pywintypes39-dll If not, that's an area where Anaconda/miniconda help...

**Comment by jontankersley** [comment]
Given trying to do cmdline, MS Studio Code, MS Studio Code devel I could readily have multiple versions installed (though I would hope I don't.... I DO now since I upgraded the version that I use from my cmd prompt.
Note, the pip install pywin32 --upgrade fixed my problem and I have xlwings showing up in Excel now.

**Comment by fzumstein** [comment]
Glad it works now!
