### ISSUE TITLE
UDF server fails with threading and API reference

### ISSUE THREAD

**Issue by hoo-ray** [xlwings/xlwings#1654]
#### Describe your issue (incl. Traceback!)

The following code works as expected when launched from the xlwings Add-In ribbon button "Run main" if option "RunPython: Use UDF Server" is unchecked:
 ```python
import time
import threading
import pythoncom
import xlwings as xw

@xw.func
def main():
    def thread_fcn():
        #pythoncom.CoInitialize()
        wb = xw.Book.caller()
        wb.app.api.StatusBar = "hello"
    thread = threading.Thread(target=thread_fcn)
    thread.start()
    time.sleep(2)
    thread.join()
```
Note that the command pythoncom.CoInitialize() is not required but does not hurt either.

However, when I activate the UDF server, I get this error:
```python
C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
xlwings server running, clsid={88BD2071-5701-40AF-8A32-A0D656285A46}, event loop on 4940
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\code\xlwings\myproject_v024.py", line 11, in thread_fcn
    wb.app.api.StatusBar = "hello"
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\xlwings\main.py", line 715, in app
    return App(impl=self.impl.app)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\xlwings\_xlwindows.py", line 521, in app
    return App(xl=self.xl.Application)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\win32com\client\__init__.py", line 474, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
```
Note that I upgraded to the latest version of mkl-services but still get the warning message during initialization of the UDF server. I do not get this message when executing the code without UDF server!
```
The following packages will be UPDATED:

    intel-openmp: 2020.2-254            --> 2021.2.0-haa95532_616
    mkl:          2020.2-256            --> 2021.2.0-haa95532_296
    mkl-service:  2.3.0-py37h196d8e1_0  --> 2.3.0-py37h2bbff1b_1
    mkl_fft:      1.2.0-py37h45dec08_0  --> 1.3.0-py37h277e83a_2
    mkl_random:   1.1.1-py37h47e9c7a_0  --> 1.2.1-py37hf11a4ad_2
    numpy:        1.19.2-py37hadc3359_0 --> 1.20.2-py37ha4e8547_0
    numpy-base:   1.19.2-py37ha3acd2a_0 --> 1.20.2-py37hc2deb75_0
    scipy:        1.5.2-py37h9439919_0  --> 1.6.2-py37h66253e8_1
```

Activating the commented command pythoncom.CoInitialize(), stopping the UDF Server and re-running the code gives me this error:
```
C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
xlwings server running, clsid={88BD2071-5701-40AF-8A32-A0D656285A46}, event loop on 8076
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\code\xlwings\myproject_v024.py", line 11, in thread_fcn
    wb.app.api.StatusBar = "hello"
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\xlwings\main.py", line 715, in app
    return App(impl=self.impl.app)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\xlwings\_xlwindows.py", line 521, in app
    return App(xl=self.xl.Application)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\win32com\client\__init__.py", line 474, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\Users\olzh0g1\AppData\Local\conda\conda\envs\py37\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147417842, 'The application called an interface that was marshalled for a different thread.', None, None)
```

I followed the instructions given on https://docs.xlwings.org/en/stable/threading_and_multiprocessing.html and fully qualified the book reference in the thread.

What is wrong here?
Why does the code work without the UDF server but not with?
Is the issue possibly related to the mkl-service warning?
Is it the combination of threading and using the API property in the command wb.app.API.StatusBar = "hello"?
I guess no because this code fails with the same error:
 ```python
...
    def thread_fcn():
        pythoncom.CoInitialize()
        wb = xw.Book.caller()
        wb.sheets[0].range("A1").value = "hello"
...
```

If this is a general issue with the COM interface then it should be documented.

Please advise - thanks.

**Comment by fzumstein** [comment]
You can use the async mode for this use case. Also note the `caller` argument and the native support for `status_bar`:

```python
@xw.func(async_mode='threading')
def hello(name, caller):
    caller.sheet.book.app.status_bar = "hello2"
    return str(caller.sheet)
```

**Comment by hoo-ray** [comment]
Thanks for the quick response :-)

I am afraid I was not clear enough: I am *NOT* running my above code as UDF. I am running it from some VBA code using RunPython. Alternatively, I run it from the xlwings Add-In ribbon button "Run main"

Note that I did all testing for this report in xlwings 0.24.2, but for production purposes I am using version 0.17.1

According to the documentation the async_mode argument in the decorator should have no impact in this case:
> The @xw.func decorator is only used by xlwings when the function is being imported into Excel. It tells xlwings for which functions it should create a VBA wrapper function, otherwise it has no effect on how the functions behave in Python.

I tried it nevertheless but I keep getting the same error messages:
1. *without* the command pythoncom.CoInitialize() I get:
```
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
```
2. *with* the command pythoncom.CoInitialize() I get:
```
pywintypes.com_error: (-2147417842, 'The application called an interface that was marshalled for a different thread.', None, None)
```

What I cannot understand why my code works without the UDF server, while it fails with the UDF server ...?

**Comment by fzumstein** [comment]
> I followed the instructions given on https://docs.xlwings.org/en/stable/threading_and_multiprocessing.html and fully qualified the book reference in the thread.

I think you should try to use `Book.caller()` in the main thread and passing over a serialized version of it to your thread, then build the COM object again there.

**Comment by hoo-ray** [comment]
Hi Felix,
thanks for the additional advice. Unfortunately, I am totally lost trying to follow your suggestion not knowing how to serialize and deserialize. Is there any documentation available anywhere?
I tried this code which I based on the xlwings source code of the ComRange class:
 ```python
import threading
import pythoncom
from win32com.client import Dispatch
import xlwings as xw

@xw.func(async_mode='threading')
def main():
    """UDF server fails with threading."""
    def thread_fcn(ser, clsid):
        pythoncom.CoInitialize()    # required for UDF mode
        deser = pythoncom.CoGetInterfaceAndReleaseStream(
            ser, pythoncom.IID_IDispatch
        )
        dispatch = Dispatch(deser, resultCLSID=clsid)
        xwb = xw._xlwindows.Book(xl=dispatch)
        xwb.app.api.StatusBar = "hello"
        xwb.sheets[0].range("A1").value = "hello"
    xwb = xw.Book.caller()
    ser = pythoncom.CoMarshalInterThreadInterfaceInStream(
            pythoncom.IID_IDispatch, xwb.api
        )
    clsid = xwb.impl.api.CLSID

    # thread_fcn(ser, clsid) # call thread_fcn from main thread
    thread = threading.Thread(target=thread_fcn, args=(ser, clsid))
    thread.start()
    thread.join()
```

Calling `thread_fcn()` from a separate thread silently fails both with and without UDF server. Calling it from the main thread (commented out) does update the StatusBar, but fails to write to the (existing!) Worksheet:
```
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\code\xlwings\myproject.py", line 57, in main
    xwb2.sheets[0].range("A9").value = "1"
TypeError: 'Sheets' object is not subscriptable
```

Please advise!
Thanks

**Comment by fzumstein** [comment]
I think you can hand over the workbook, sheet etc. name as a string, then create the object in the thread, similar to this answer here: https://github.com/xlwings/xlwings/issues/473#issuecomment-434588637

**Comment by hoo-ray** [comment]
Great hint, this works (v0.17.1):
```python
import threading
import xlwings as xw

def main():
    """UDF server works with threading."""
    def thread_fcn(name):
        xwb = xw.Book(name)
        xwb.app.api.StatusBar = "hello"
        xwb.sheets[0].range("A1").value = "hello"
    xwb = xw.Book.caller()
    thread = threading.Thread(target=thread_fcn, args=[xwb.name])
    thread.start()
    thread.join()
```

Thank you very much :-)
