### ISSUE TITLE
Can't zoom sheet to a specified value

### ISSUE THREAD

**Issue by niuzijia** [xlwings/xlwings#1685]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
I want to zoom the sheet to a specified value, but it don't work
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
if __name__ == "__main__":
    import xlwings as xw

    my_book = r'my_excel.xlsx'
    my_sht = 'sheet1'
    
    book = xw.Book(my_book)
    sht = book.sheets[my_sht]
    sht.api.Zoom = 80

```

**Comment by fzumstein** [comment]
Zoom is a property of ActiveWindow. Try; `book.app.api.ActiveWindows.Zoom = 80`, seems like you need to activate the sheet first, see: https://stackoverflow.com/a/5953765/918626

**Comment by niuzijia** [comment]
@fzumstein Thanks for your reply, here is my new code, but it gives a error. Is there any wrong?
```python
# My traceback here
if __name__ == "__main__":
    import xlwings as xw

    app = xw.apps.add()
    sheet = xw.sheets.active
    print(sheet.name)
    sheet.api.ActiveWindows.Zoom = 80
```
The error is:
```python
Traceback (most recent call last):
  File "E:\24 Python\02 Install File\lib\site-packages\xlwings\_xlwindows.py", line 122, in __getattr__
    v = getattr(self._inner, item)
  File "E:\24 Python\02 Install File\lib\site-packages\win32com\client\__init__.py", line 473, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Worksheet instance at 0x1530610973904>' object has no attribute 'ActiveWindows'
```

**Comment by fzumstein** [comment]
ActiveWindow, not ActiveWindows (fixed it on my comment)
