### ISSUE TITLE
"The user has declined permission" error while running xlwings with macOS Automator

### ISSUE THREAD

**Issue by yuriynefedov** [xlwings/xlwings#1693]
#### OS
macOS Big Sur (11.4)
#### xlwings, Excel and Python versions
0.24.5, Office 365, Python 3.8.5

#### Describe your issue (incl. Traceback!)
I'm having an issue with running an Automator script on my Mac that uses xlwings to read and write data into an Excel spreadsheet.

```python
The action “Run AppleScript” encountered an error: “[2021.08.01 19:45:21] /Users/yuriynefedov/Desktop/clarity-test/common.py:18 - DEBUG - Config path: /Users/yuriynefedov/Desktop/clarity-test/settings.ini
Traceback (most recent call last):
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 482, in __call__
return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/aeosa/aem/aemsend.py", line 92, in send
raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The user has declined permission. (-1743)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Users/yuriynefedov/Desktop/clarity-test/app/controller.py", line 238, in get_work_documents
self._matter_data = self.get_data_matter()
File "/Users/yuriynefedov/Desktop/clarity-test/app/controller.py", line 194, in get_data_matter
wbxl = xw.Book(origin_xlsm_file)
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/xlwings/main.py", line 662, in __init__
for wb in app.books:
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/xlwings/main.py", line 60, in __iter__
for impl in self.impl:
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/xlwings/_xlmac.py", line 265, in __iter__
n = len(self)
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/xlwings/_xlmac.py", line 228, in __len__
return self.app.xl.count(each=kw.workbook)
File "/Users/yuriynefedov/Desktop/clarity-test/venv/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 518, in __call__
raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
OSERROR: -1743
MESSAGE: The user has declined permission.
COMMAND: app(pid=62165).count(each=k.workbook)”

```

The script works perfectly when run from Terminal. Nevertheless, the nature of the application I'm developing requires using an Automator script. I'm almost 100% sure the issue has to do with permissions, but unfortunately I can't seem to find a way to allow Automator to use Microsoft Excel directly, and when running the script with Automator I never get asked for permission (as opposed to running from Terminal). Therefore, I was wondering if someone might have run xlwings through an Automator script and has encountered similar issues.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
wbxl = xw.Book(origin_xlsm_file)

```

**Comment by fzumstein** [comment]
Is there a way to invoke Automator from the Terminal?
