### ISSUE TITLE
`App.kill()` does not work with custom DCOM Config on Windows Server

### ISSUE THREAD

**Issue by rudolfbyker** [xlwings/xlwings#1743]
### Versions

- Windows server
- Office 365
- Python 3.8.8 (Anaconda)
- xlwings 0.23.0

### Description

When you change the Excel identity in `dcomcnfg` on Windows server, `App.kill()` does not work. It seems to be related to this explanation https://stackoverflow.com/a/4988116/836995 . I did not get the same issue on Windows 10.

### Steps to reproduce

1. Change the Identity for Excel in `dcomcnfg`:
![image](https://user-images.githubusercontent.com/10025342/138236851-ba26f7fc-10aa-4a2d-bc9f-f7583b0a8b43.png)
2. Create any old Excel file, called `Book1.xlsb`.
3. Run this:
```python
import xlwings as xw
book = xw.Book("Book1.xlsb")
app = book.app
app.kill()
```
4. Observe traceback:
```python
Traceback (most recent call last):
  File ".\test.py", line 5, in <module>
    app.kill()
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\main.py", line 302, in kill
    return self.impl.kill()
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 370, in kill
    handle = win32api.OpenProcess(PROCESS_TERMINATE, False, self.pid)
pywintypes.error: (87, 'OpenProcess', 'The parameter is incorrect.')
```
5. Change back to "The launching user."
6. Run the script again.
7. Observe that there is no error. Excel opens and closes as expected.

**Comment by fzumstein** [comment]
Yes, I've ran into this before, but didn't have time to investigate. You could try if psutil or os.kill give you the same error? https://stackoverflow.com/a/17858114/918626

**Comment by fzumstein** [comment]
@rudolfbyker were you ever able to get some insights here?

**Comment by rudolfbyker** [comment]
Sorry, no. I tried, but did not understand.

However, I found that `.quit()` works just as well as `.kill()` for what I'm doing so now I'm using `.quit()`.
