### ISSUE TITLE
...cells.api.AutoFilter() does not work anymore

### ISSUE THREAD

**Issue by balan777** [xlwings/xlwings#1781]
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings.__version__
Out[52]: '0.24.9'

Python:
sys.version
Out[54]: '3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]'

Excel:
Office 365

#### Describe your issue (incl. Traceback!)

The AutoFilter() function worked fine with the xlwings version 0.15.10. After updating to '0.24.9' it does not work anymore.

The sheet is not empty.

```python

if xw.books.active.sheets[0].api.AutoFilterMode==False :
      xw.books.active.sheets[0].cells.api.AutoFilter()

Traceback:

com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'Microsoft Excel', 'Die AutoFilter-Methode des Range-Objektes konnte nicht ausgeführt werden.', 'xlmain11.chm', 0, -2146827284), None)

Translation from German:

com_error: (-2147352567, 'Exception error occurred.', (0, 'Microsoft Excel', 'The AutoFilter method of the Range object could not be executed.', 'xlmain11.chm', 0, -2146827284), None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
#You need some active workbook with some data in the first scheet.

import xlwings as xw


xw.Book()
wb=xw.books.active
sht=wb.sheets[0]
#add some data in to the sheet
if sht.api.AutoFilterMode==False :
     print('da') 
     sht.cells.api.AutoFilter()




"""
Comment:
Autofilter in the sheet was previously manually set to off:

if sht.api.AutoFilterMode==False:
    print('da')
    sht.cells.api.AutoFilter()

Autofilter in the sheet was previously manually set to on:

if sht.api.AutoFilterMode==False:
    print('da')
    sht.cells.api.AutoFilter()
    
da
Traceback (most recent call last):

  File "C:\Users\BALANE~1\AppData\Local\Temp/ipykernel_18340/1716278584.py", line 3, in <module>
    sht.cells.api.AutoFilter()

  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 70, in __call__
    v = self.__method(*args, **kwargs)

  File "C:\Users\BALANE~1\AppData\Local\Temp\gen_py\3.7\00020813-0000-0000-C000-000000000046x0x1x9.py", line 33378, in AutoFilter
    , Criteria1, Operator, Criteria2, VisibleDropDown, SubField

  File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),

com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'Microsoft Excel', 'Die AutoFilter-Methode des Range-Objektes konnte nicht ausgeführt werden.', 'xlmain11.chm', 0, -2146827284), None)

```

**Comment by fzumstein** [comment]
Looks like AutoFilter requires arguments, see: https://github.com/xlwings/xlwings/issues/1767 not sure why it would have worked without before

**Comment by balan777** [comment]
In excel an AutoFilter funktion without arguments switches an autotfilter on (if it was off) or off (if it was on):

Try in excel please:

****Sub do_auto_filter()**
    **Set wb = ThisWorkbook**    
    **wb.ActiveSheet.Cells.AutoFilter**
**End Sub****

If You will try to call this procedure from python, it will also work!

Python:

**macros=wb.macro('do_auto_filter')**

Why it worked with xlwings version 0.15.10 directly via api function is also an interesting question for me! ;-) But yesterday after upgrading my xlwings version from 0.15.10 to 0.24.9 I suddenly got the error as described above.
