### ISSUE TITLE
unable to set cell values

### ISSUE THREAD

**Issue by ekwf** [xlwings/xlwings#1786]
#### OS (e.g. Windows 10 or macOS Sierra)

Win10 Pro 19044.1348

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.25.0
Excel 365
Python 3.7

#### Describe your issue (incl. Traceback!)

<Sheet [Relay.xlsm]sm_test>
sfasdf
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\server.py", line 198, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\udfs.py", line 519, in call_udf
    ret = func(*args)
  File "C:\Users\User\Documents\step_model\Relay.py", line 16, in init_sm
    sht.range('B3').value = "foo"
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\main.py", line 2027, in value
    conversion.write(data, self, self._options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\conversion\__init__.py", line 48, in write
    pipeline(ctx)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\conversion\framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\conversion\standard.py", line 74, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\conversion\standard.py", line 62, in _write_value
    rng.raw_value = value
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\main.py", line 1620, in raw_value
    self.impl.raw_value = data
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\xlwings\_xlwindows.py", line 859, in raw_value
    self.xl.Value = data
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\__init__.py", line 482, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

import xlwings as xw

@xw.func
def init_sm():
	sht = xw.Book.caller().sheets[0]
	print(sht)
	print(sht.range('B3').value) #prints value
	sht.range('B3').value = "foo"  #exception	
	return 1

if __name__ == "__main__":
    xw.serve()

**Comment by fzumstein** [comment]
That's a limitation of UDFs, you can only return values, not write outside of UDFs, see: https://support.microsoft.com/en-us/topic/description-of-limitations-of-custom-functions-in-excel-f2f0ce5d-8ea5-6ce7-fddc-79d36192b7a1
