### ISSUE TITLE
On a standalone project can't get the code to run from within excel the code run's from the IDE

### ISSUE THREAD

**Issue by boazdori** [xlwings/xlwings#1807]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.24.9
excel: 365
python: 3.9.7
Anaconda: fresh install

#### Describe your issue (incl. Traceback!)
---------------------------
Error
---------------------------
C:\Users\User\anaconda3\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service

  from . import _distributor_init

Traceback (most recent call last):

  File "C:\Users\User\anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>

    from . import multiarray

  File "C:\Users\User\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>

    from . import overrides

  File "C:\Users\User\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>

    from numpy.core._multiarray_umath import (

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "project.py", line 11, in <module>

    import numpy as np

  File "C:\Users\User\anaconda3\lib\site-packages\numpy\__init__.py", line 145, in <module>

    from . import core

  File "C:\Users\User\anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>

    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for

many reasons, often due to issues with your setup or how NumPy was

installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\User\anaconda3\python.exe"

  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.

Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

**Comment by fzumstein** [comment]
Looks like you haven't configured the Conda settings properly in your addin or xlwings.conf sheet, see: https://docs.xlwings.org/en/stable/addin.html#user-settings

**Comment by boazdori** [comment]
Felix hi,
you are right I added 
Conda Path C:\Users\User\anaconda3
and
Conda Env C:\Users\User\anaconda3
and it's working
Thanks
Boaz
