### ISSUE TITLE
Resource deadlock avoided issue since OS upgrade

### ISSUE THREAD

**Issue by robzer** [xlwings/xlwings#1860]
#### xlwings 0.24.9 python 3.8.8  

been running a python script with the xlwings 'run main' button on excel. Python script has the same name as the spreadsheet and is located on a OneDrive location here /Users/user/OneDrive - MVPQ Capital/Fund Management/PyCode. It has been working like a dream until got new mac (and new OS by the same occasion). Been getting the below error, dont know why.

```python
# Your traceback here

Traceback (most recent call last):File "<string>", line 1, in <module>File "<frozen importlib._bootstrap>", line 1027, in _find_and_loadFile "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlockedFile "<frozen importlib._bootstrap>", line 945, in _find_specFile "<frozen importlib._bootstrap_external>", line 1430, in find_specFile "<frozen importlib._bootstrap_external>", line 1402, in _get_specFile "<frozen importlib._bootstrap_external>", line 1539, in find_specFile "<frozen importlib._bootstrap_external>", line 1582, in _fill_cacheOSError: [Errno 11] Resource deadlock avoided: '/Users/user/OneDrive - MVPQ Capital/Fund Management/PyCode'

```

#### using xlwings tab in excel to run the code 

```python

interpreter: /Users/anaconda3/envs/mvpq/bin/python
pythonpath: /Users/user/OneDrive - MVPQ Capital/Fund Management/PyCode

```

Please let me know if you have any idea on how to fix this! many thanks. Note: I have been deliberatly staying on the 0.24.9 xlwings version because 0.25 was causing issues.

**Comment by robzer** [comment]
edit: this is related to a OneDrive update, which was quite messy to say the least. This blog was helpful is solving
https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/updates-to-files-on-demand-on-macos/ba-p/3207503

**Comment by fzumstein** [comment]
Hi @robzer thanks for reporting and do you mind sharing what you had to change to resolve? It looks like this does need another iteration though to fix this so I'll leave this open for the macOS case. For Windows, there is already another issue open (#1829).

**Comment by robzer** [comment]
@fzumstein needed to re-download shared files locally as explained in the link above

**Comment by fzumstein** [comment]
gotcha, this makes sense, yes.
