### ISSUE TITLE
Can xlwings run in Linux?  such as loading existing Excel files

### ISSUE THREAD

**Issue by hanjiangxue20** [xlwings/xlwings#1901]
#### OS (e.g. Windows 10 or macOS Sierra)
CentOS7
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.27.6
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
[2022-04-26 19:42:14,023] ERROR in stability_test_view.py: [line: 945] 标记excel异常：Your platform only supports the instantiation via xw.Book(json=...)
Traceback (most recent call last):
  File "/app/apps/operate/stability_test_view.py", line 916, in mark_error_in_excel
    wb = xlwings.Book(excel_path)
  File "/usr/local/lib/python3.6/site-packages/xlwings/main.py", line 820, in __init__
    for app in apps:
  File "/usr/local/lib/python3.6/site-packages/xlwings/main.py", line 225, in __iter__
    for app in self.impl:
  File "/usr/local/lib/python3.6/site-packages/xlwings/main.py", line 4941, in impl
    "Your platform only supports the "
xlwings.XlwingsError: Your platform only supports the instantiation via xw.Book(json=...)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
        wb = xlwings.Book(excel_path)
        # wb = app.books.open(excel_path)
        for k, v in error_record.items():
            sheet_name = DEPLOY_PARAMS_MAP.get(k)[0]
            ws = wb.sheets[sheet_name]
            # read rows
            column = None
            _header = ws.range(2, 1).expand('right').value
            for index, _h in enumerate(_header):
                if _h == k:
                    column = index + 1
                    break
            for _row, _value in v.items():
                if column:
                    # mark red
                    logger.info(f'标红excel：{sheet_name}:{_row}:{column}, msg:{_value}')
                    ws.range(_row, column).color = 200, 0, 0
                     ws.api.AddComment(_value)

        wb.save(excel_path)
```

**Comment by fzumstein** [comment]
Currently, xlwings can only run as a remote interpreter on Linux, see: https://docs.xlwings.org/en/stable/remote_interpreter.html

There are plans to add read/write capabilities, but for now you have to use one of OpenPyXL, XlsxWriter, or pyxlsb, depending on the file format.
