### ISSUE TITLE
Issue with running frozen on xlwings

### ISSUE THREAD

**Issue by jsaurabh36** [xlwings/xlwings#1905]
#### OS (e.g. Windows 10 or macOS Sierra)
Window 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

python 3.9 but i also have python 3.8 installed on the same machine

#### Describe your issue (incl. Traceback!)
I created an executable with pyinstaller and tring to run using runfrozenpython. Executable seems to work perfectly on one machine and very slow on other and seem to wait at line "import xlwing as xw" for almost 2mins. Looks like some kind of setting on device vs the another any help would be appreciated. below is trace

```python
# Your traceback here

Traceback (most recent call last):
File "SSimulation.py", line 2, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "xlwings_init.py", line 9, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "xlwings_xlwindows.py", line 33, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "xlwings\utils.py", line 12, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "numpy_init.py", line 153, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "numpy\lib_init.py", line 36, in
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 478, in exec_module
File "PyInstaller\loader\pyimod03_importers.py", line 298, in get_code
File "PyInstaller\loader\pyimod02_archive.py", line 290, in extract
File "PyInstaller\loader\pyimod02_archive.py", line 87, in enter
KeyboardInterrupt
[14532] Failed to execute script 'SSimulation' due to unhandled exception!
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
The only advise I would have is to try with a full Python installation and see if you hit the same behavior.
