### ISSUE TITLE
PivotTables on Windows and Mac OS X

### ISSUE THREAD

**Issue by ahmedelz** [xlwings/xlwings#191]
Hi,

I need to work with excel sheets to create pivot tables. I was able to get the script to work on windows by accessing `api` with the following code:

```
import xlwings.constants as win32c

pc = wb.api.PivotCaches().Create(SourceType=win32c.xlDatabase,
     SourceData=sourcedata, Version=win32c.xlPivotTableVersion12)
```

However, on Mac OS X, the same line above errors out with:
AttributeError: Unknown property, element or command: 'PivotCaches'

Note: I'm importing win32com.client.constants as win32c on windows and I'm also importing xlwings.constants as win32c.

Any suggestions or pointers on how to call PivotCaches on Mac OS X?

**Comment by fzumstein** [comment]
thanks for looking into this. Unfortunately, to get the syntax right for the Mac version, it's a little more involved. First, you'll need to make it work with Apple Script. [This](http://download.microsoft.com/download/3/A/7/3A70FB4B-0C6A-43E3-AAB7-AC9166B25632/Excel2004AppleScriptRef.pdf) is a good first reference, despite its age. Then you can translate it into `appscript` syntax using `ASTranslate` from http://appscript.sourceforge.net/tools.html . Other than that, just by looking at `_xlmac.py` you should get a good idea of how things look like in `appscript`.

**Comment by ahmedelz** [comment]
Felix,

Thanks a lot for the pointers to Apple Script documentation and ASTranslate. These were very helpful and indeed process to get the syntax for mac is much more involved. I was able to write Apple Script code that matches the behavior I wanted and got it translated using `ASTranslate` and I can see it doing the correct behavior in Excel when `Send events to app` is selected in `ASTranslate`. However, I'm unable to get it to work using pyton `appscript`. So, I have the spreadsheet already opened in Excel with the source data in 'Sheet0'. Here is the `python` code snippet I'm using to test this and I see Excel indeed creating new 'Summary_A' sheet then it errors outs on the last line:

```python
from appscript import app, mactypes
from appscript import k as kw

app('Microsoft Excel').activate()
app('Microsoft Excel').active_sheet.name.set('Sheet0')
app('Microsoft Excel').make(at=app.active_workbook.end,new=kw.worksheet,with_properties={kw.name: u'Summary_A'})
app('Microsoft Excel').make(new=kw.pivot_table,at=app.sheets('Summary_A'),with_properties={kw.source_data:app.ranges['Sheet0!A14:AC5733'],kw.name:'Summary_APivot'})

  app('Microsoft Excel').make(new=kw.pivot_table,at=app.sheets('Summary_A'),with_properties={kw.source_data:app.ranges['Sheet0!A14:AC5733'],kw.name:'Summary_APivot'})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 462, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/aem/__init__.py", line 189, in event
    codecs or self._codecs, self._createproc, self._sendproc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/aem/aemsend.py", line 54, in __init__
    self.AEM_event.setparam(key, codecs.pack(value))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 274, in pack
    return aem.Codecs.pack(self, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/aem/aemcodecs.py", line 317, in pack
    return encoder(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 130, in packdict
    record.setparam(keyCode, self.pack(value))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 266, in pack
    data = data.AS_resolve(Reference, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/genericreference.py", line 65, in AS_resolve
    ref = getattr(ref, method)(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 589, in __getitem__
    return Reference(self.AS_appdata, self.AS_aemreference.byname(selector))
AttributeError: 'Property' object has no attribute 'byname'
```
I appreciate if you have further pointers to help me fix this error.

**Comment by fzumstein** [comment]
It's much easier if you start off the `xlwings` objects and get the underlying `appscript` object by adding `xl_sheet` for `Sheet`, for example this seems to work:

```
from appscript import app
from appscript import k as kw

from xlwings import Workbook, Range, Sheet

wb = Workbook('/Users/Felix/Desktop/pivot.xlsx')

summary_sheet = Sheet('Summary_A')

app('Microsoft Excel').make(new=kw.pivot_table,
                            at=summary_sheet.xl_sheet,
                            with_properties={kw.source_data: Range('Sheet0', 'A1:B28').xl_range,
                                             kw.name: 'Summary_APivot'})
```

**Comment by Cbarrow98** [comment]
Hi Felix, is it possible if you could explain the code from the first comment ive tried to tweak it to my own but I think some of the  code has been updated since I am getting the error "AttributeError: 'Book' object has no attribute 'xl_workbook'"

**Comment by fzumstein** [comment]
yes, it's very old. You will need to replace xl_sheet and xl_range etc with `api`

**Comment by Cbarrow98** [comment]
Do I have to import appscript if I am using windows ?

**Comment by Cbarrow98** [comment]
closest i have gotten based on the first comment: pc = wb.api.PivotCaches().Create(SourceType=win32c.xlDatabase,
SourceData=sourcedata, Version=win32c.xlPivotTableVersion12)


---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-63-9363d07bb76d> in <module>
      1 pc = wb.api.PivotCaches().Create(SourceType=win32c.xlDatabase,
----> 2 SourceData=sourcedata, Version=win32c.xlPivotTableVersion12)

NameError: name 'sourcedata' is not defined

**Comment by fzumstein** [comment]
no, that is the macOS code, for Windows have a look at the very first comment in this thread.

**Comment by fzumstein** [comment]
`sourcedata` is an Excel range as pywin32 object, so e.g. xw.Book(...).sheets[0].range('A1:B2').api`

**Comment by bradbase** [comment]
There's a modern-ish example of pivot tables in an example I wrote years ago. It's probably broken against the library it is intended to be an example for but the pivot table code should be a reasonable guide.

https://github.com/bradbase/python-harvest_apiv2/blob/master/examples/xlwings/accounting.py

**Comment by fzumstein** [comment]
Thanks @bradbase! An off-topic comment though:

```
    new_invoices.range('A1').value = 'client.id'
    new_invoices.range('B1').value = 'id'
    new_invoices.range('C1').value = 'number'
    ...
```

is an anti-pattern as this will be very slow. You should rather do:

```
    new_invoices.range('A1').value = ['client.id', 'id', 'number', ...]
```
instead which is just a single call und much much faster given the amount of cells you have.

**Comment by Cbarrow98** [comment]
So after successfully creating the pivot cache, when trying to create the pivot table itself i get the following error from this code

PivotTable = PivotCache.CreatePivotTable(TableDestination="'Sheet1'!A10B10", TableName="Bond_Table", DefaultVersion=constants.PivotTableVersionList.xlPivotTableVersion14)


com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)

**Comment by fzumstein** [comment]
try `yourbook.sheets['Sheet1']['A10:B10'].api` instead of `"'Sheet1'!A10B10"`

**Comment by Cbarrow98** [comment]
Okay it seems to except that. However now it claiming I have no data in the fields of want to derive a pivot table from. Here is the full code with explanation on what I am trying to accomplish:


###create the cache and the source data is in the sheet "Portfolio" which i need to create a pivot table using this data
PivotCache = wb.api.PivotCaches().Create(SourceType=win32c.xlDatabase,
SourceData=wb.sheets['Portfolio'].range('A10:B10').api, Version=win32c.xlPivotTableVersion14)

### creating the pivot table which places the pivot table in Sheet2
PivotTable = PivotCache.CreatePivotTable(TableDestination=wb.sheets['Sheet2']['A10:B10'].api, TableName="Bond_Table", DefaultVersion=constants.PivotTableVersionList.xlPivotTableVersion14)

The error:

You cannot use the command on a selection in only one row. Try the following:\n\n• If you're using an advanced filter, select a range of cells that contains at least two rows of data. Then click the Advanced Filter command again.\n• If you're creating a PivotTable report or PivotChart report, type a cell reference or select a range that includes at least two rows of data.", 'xlmain11.chm', 0, -2146827284), None)

**Comment by bradbase** [comment]
Range A10:B10 seems to only have one row of data.
-------- Original message --------From: Cbarrow98 <notifications@github.com> Date: 10/2/21  10:07 pm  (GMT+10:00) To: xlwings/xlwings <xlwings@noreply.github.com> Cc: Bradley van Ree <brads@bradbase.net>, Mention <mention@noreply.github.com> Subject: Re: [xlwings/xlwings] PivotTables on Windows and Mac OS X (#191) 

Okay it seems to except that. However now it claiming I have no data in the fields of want to derive a pivot table from. Here is the full code with explanation on what I am trying to accomplish:

###create the cache and the source data is in the sheet "Portfolio" which i need to create a pivot table using this data

PivotCache = wb.api.PivotCaches().Create(SourceType=win32c.xlDatabase,

SourceData=wb.sheets['Portfolio'].range('A10:B10').api, Version=win32c.xlPivotTableVersion14)

creating the pivot table which places the pivot table in Sheet2

PivotTable = PivotCache.CreatePivotTable(TableDestination=wb.sheets['Sheet2']['A10:B10'].api, TableName="Bond_Table", DefaultVersion=constants.PivotTableVersionList.xlPivotTableVersion14)

The error:

You cannot use the command on a selection in only one row. Try the following:\n\n• If you're using an advanced filter, select a range of cells that contains at least two rows of data. Then click the Advanced Filter command again.\n• If you're creating a PivotTable report or PivotChart report, type a cell reference or select a range that includes at least two rows of data.", 'xlmain11.chm', 0, -2146827284), None)

**Comment by fzumstein** [comment]
just found this which might be helpful: https://trenton3983.github.io/files/solutions/2020-06-22_pivot_table_win32com/create_pivot_table_with_win32com.html

There's another reference specifically for extending xlwings with pivot tables but I can't find it right now.

**Comment by bradbase** [comment]
Cheers FelixThanks for the input.I should see about getting that example working again. The Harvest library has moved a bit since I made the example. Theoretically the same method signatures  as the Harvest API hasn't changed, but lots of lines of code have changed.At the time the example was written working took priority over performance and I had a beginner working with me. But as it is now an example of pivot tables referenced from xlwings help I think improving performance is a positive.Thanks again 
-------- Original message --------From: Felix Zumstein <notifications@github.com> Date: 10/2/21  6:49 pm  (GMT+10:00) To: xlwings/xlwings <xlwings@noreply.github.com> Cc: Bradley van Ree <brads@bradbase.net>, Mention <mention@noreply.github.com> Subject: Re: [xlwings/xlwings] PivotTables on Windows and Mac OS X (#191) 
Thanks @bradbase! An off-topic comment though:
    new_invoices.range('A1').value = 'client.id'
    new_invoices.range('B1').value = 'id'
    new_invoices.range('C1').value = 'number'
    ...

is an anti-pattern as this will be very slow. You should rather do:
    new_invoices.range('A1').value = ['client.id', 'id', 'number', ...]

instead which is just a single call und much much faster given the amount of cells you have.

**Comment by fzumstein** [comment]
here it is: https://www.yinglinglow.com/blog/2018/04/29/xlwings-pivot-table and I think there's another resource on this

**Comment by bradbase** [comment]
I'm interested in that link if it finds it's way back to the surface.Sent from my Galaxy
-------- Original message --------From: Felix Zumstein <notifications@github.com> Date: 10/2/21  10:43 pm  (GMT+10:00) To: xlwings/xlwings <xlwings@noreply.github.com> Cc: Bradley van Ree <brads@bradbase.net>, Mention <mention@noreply.github.com> Subject: Re: [xlwings/xlwings] PivotTables on Windows and Mac OS X (#191) 
just found this which might be helpful: https://trenton3983.github.io/files/solutions/2020-06-22_pivot_table_win32com/create_pivot_table_with_win32com.html
There's another reference specifically for extending xlwings with pivot tables but I can't find it right now.

**Comment by Cbarrow98** [comment]
Hi Bradley,

That's bizarre, the screenshot below should show the book i am working with and the sheets which shows there is data those columns.


![image](https://user-images.githubusercontent.com/71831382/107506702-6218f000-6b96-11eb-861b-c9b7cc78314b.png)

And, thanks Felix will have a look at those links now.

**Comment by bradbase** [comment]
Providing it's working, that's fine.The error I saw was stating it wanted two rows of data. And you'd specified only one row over two columns.I'm not at a computer atm so can't replicate your situation.
-------- Original message --------From: Cbarrow98 <notifications@github.com> Date: 10/2/21  10:53 pm  (GMT+10:00) To: xlwings/xlwings <xlwings@noreply.github.com> Cc: Bradley van Ree <brads@bradbase.net>, Mention <mention@noreply.github.com> Subject: Re: [xlwings/xlwings] PivotTables on Windows and Mac OS X (#191) 
Hi Bradley,
That's bizarre, the screenshot below should show the book i am working with and the sheets which shows there is data those columns.

And, thanks Felix will have a look at those links now.

**Comment by Cbarrow98** [comment]
> Providing it's working, that's fine.The error I saw was stating it wanted two rows of data. And you'd specified only one row over two columns.I'm not at a computer atm so can't replicate your situation. -------- Original message --------From: Cbarrow98 <notifications@github.com> Date: 10/2/21 10:53 pm (GMT+10:00) To: xlwings/xlwings <xlwings@noreply.github.com> Cc: Bradley van Ree <brads@bradbase.net>, Mention <mention@noreply.github.com> Subject: Re: [xlwings/xlwings] PivotTables on Windows and Mac OS X (#191) Hi Bradley, That's bizarre, the screenshot below should show the book i am working with and the sheets which shows there is data those columns. And, thanks Felix will have a look at those links now. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Yeah it still shows the error not sure where I am going wrong the data is clearly there. I must be quoting it wrong.

![image](https://user-images.githubusercontent.com/71831382/107510485-ea4dc400-6b9b-11eb-8030-60c0992532ca.png)

**Comment by Cbarrow98** [comment]
solved it, Thanks for everyone's help much appreciated

**Comment by ArjunARV** [comment]
Can we change Source data of existing Pivot table using xlwings??

**Comment by Blanket58** [comment]
Is this feature request being followed? This functionality is really helpful, if there are some simplified functions been implemented in xlwings.
Or can somebody please give a simple sample code that can run suceesfully? I already did many search, can't find any code I can use.

**Comment by Blanket58** [comment]
Given the scarcity of online references and the cryptic nature of AppScript's documentation, Here I wite out a clear example demonstrating pivot table creation via the `api` attribute on macOS.

```python
import xlwings as xw
from appscript import k as kw

app = xw.App(visible=False, add_book=False)
wb = app.books.open('example.xlsx')
# Sheet1 contains the orginal data which needs to pivot on.
ws = wb.sheets.add('Sheet2', after='Sheet1')
pt = wb.app.api.make(
    new=kw.pivot_table,
    at=ws.api,
    with_properties={
        kw.source_data: wb.sheets['Sheet1'].range('A1').expand().api,
        kw.name: 'The Pivot Table',
        kw.column_grand: False,
        kw.row_grand: False
    }
)
pt.table_style2.set('PivotStyleLight16')  # Specify a style for the pivot table.
pt.add_fields_to_pivot_table(
    pt,
    row_fields=['Column1'],
    page_fields=['Column2']
)
pt.pivot_fields['Column2'].current_page.set('One enum in Column2')  # Specify a value for the filter field.
pt.row_fields['Column1'].set_subtotals(subtotal_index=kw.automatic_subtotal, value=False)  # Delete the subtotal.
pt.pivot_fields['Column3'].pivot_field_orientation.set(kw.orient_as_data_field)
ws.range('B:B').number_format = '0.00%'
# Give the data field a white-red color scale.
fc = worksheet.range('B5').expand('down').api.format_conditions.make(
    new=kw.format_condition,
    at=worksheet.range('B5').expand('down').api,
    with_properties={
        kw.format_condition_type: kw.color_scale,
    }
)
fc.color_scale_criterion[1].format_color.color.set([255, 255, 255])
fc.color_scale_criterion[2].format_color.color.set([248, 105, 107])

wb.save()
app.quit()
```

**Comment by fzumstein** [comment]
Official support for PivotTables has been added with xlwings 0.37.3.
