### ISSUE TITLE
MacOS excel error pop up not complete

### ISSUE THREAD

**Issue by CoenV97** [xlwings/xlwings#1914]
#### OS (e.g. Windows 10 or macOS Sierra)
MacOS Monterey: 12.0.1

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version:  0.27.7
Python version: 3.10.4
Excel version: 16.61

#### Describe your issue (incl. Traceback!)

I have created a python file which reads values from excel and inserts them into corresponding placeholders in a word document. When running the code within vscode it runs without issues. However, once I try to run the code from the excelbutton (through xlwings, using the sample callback macro) I get a pop up error which is not complete (it either stops halfway in a line or spurts out unreadable characters). Has anyone got any experience with xlwings/ docxtpl/ python-docx and came up to a similar issue?

Is there maybe any way through which I can find the complete error message?
```python
# Your traceback here
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/Coen/VectorAutomatisering/VectorAutomatisering.py", line 24, in main
doc.render(context)
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docxtpl/template.py", line 327, in render
self.render_init()
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docxtpl/template.py", line 50, in render_init
self.init_docx()
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docxtpl/template.py", line 46, in init_docx
self.docx = Document(self.template_file)
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docx/api.py", line 25, in Document
document_part = Package.open(docx).main_document_part
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docx/opc/package.py", line 128, in open
pkg_reader = PackageReader.from_file(pkg_file)
File "/Users/Coen/opt/anaconda3/lib/python3.9/site-packages/docx/opc/pkgreader.py", line 32, in from_file
phys_reader = Pˇˇˇˇˇˇˇˇ
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Because I am not able to upload the excel file apparently, I have added a screenshot of the information I aim to export to the word document. 

<img width="846" alt="Schermafbeelding 2022-05-13 om 14 27 25" src="https://user-images.githubusercontent.com/105497309/168283192-5aac696f-db8c-43b6-8a72-8393b10c534a.png">

The word document with placeholders looks like this:

<img width="381" alt="Schermafbeelding 2022-05-13 om 14 39 30" src="https://user-images.githubusercontent.com/105497309/168284956-67833dc0-1dae-40d7-9f8f-9d1483728075.png">

```python
import os, sys # Standard python Libraries

import xlwings as xw

from docxtpl import DocxTemplate



Working_Directory = os.getcwd()

os.chdir(Working_Directory)



def main():

wb = xw.Book.caller()

sht_panel = wb.sheets['PANEL']

doc = DocxTemplate ('Template')



# Get Values directly from EXCEL



context = sht_panel.range('A2').options(dict,expand='table', numbers=int).value



# Render & Save Word Document



output_name = f'Rapport_Sjabloon_{context["Opdrachtgever"]}.docx'

doc.render(context)


[doc.save](https://doc.save/)(output_name)
```

**Comment by fzumstein** [comment]
Don't use `os.getcwd()` but use a full (absolute) path instead. xlwings may run in a different working directory when run from Excel than what you want.

**Comment by fzumstein** [comment]
Is this still an issue? In this case please reopen and paste the code after the change to using full path.
