### ISSUE TITLE
xlwings `Range.value` dropping formula error cells

### ISSUE THREAD

**Issue by goroderickgo** [xlwings/xlwings#1924]
#### OS (e.g. Windows 10 or macOS Sierra)

- macOS Monterey

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

- xlwings 0.24.9 
- Office 365 (Excel v.16.61.1 22052000)
- Python 3.9

#### Describe your issue (incl. Traceback!)

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/e3-work/opt/anaconda3/envs/new-modeling-toolkit/lib/python3.9/site-packages/xlwings/main.py", line 1993, in value
    return conversion.read(self, None, self._options)
  File "/Users/e3-work/opt/anaconda3/envs/new-modeling-toolkit/lib/python3.9/site-packages/xlwings/conversion/__init__.py", line 32, in read
    pipeline(ctx)
  File "/Users/e3-work/opt/anaconda3/envs/new-modeling-toolkit/lib/python3.9/site-packages/xlwings/conversion/framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "/Users/e3-work/opt/anaconda3/envs/new-modeling-toolkit/lib/python3.9/site-packages/xlwings/conversion/standard.py", line 136, in __call__
    elif len(c.value[0]) == 1:
IndexError: list index out of range

```
#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

In my case, xlwings silently drops cells from a range if there is a formula error. How I found this error was that I had two ranges that I expected to have the exact same dimensions. Doing `Range.shape` showed they had the same dimensions; however, one range had a row with all formula errors (`#REF!`, though it seems to work with other formula errors too, such as my example below). When I tried to do `Range.value` on the two ranges, I would get data structures of different dimensions, because it seemed like xlwings was silently dropping the row with formula errors. 

I haven't tested all the combinations, but I've attached a small example workbook ([book1.xlsx](https://github.com/xlwings/xlwings/files/8783696/book1.xlsx)) to accompany the code below. In my small example, I also uncovered that if I try to do `Range.value` for a range larger than 1 cell with all formula errors, I get an error (see traceback above)

```python
import xlwings as xw

xw.Book("Book1.xlsx").set_mock_caller()
wb = xw.Book.caller()

wb.sheets["Sheet1"].range("A1").value
# >>> Returns nothing (presumably it's a None)

wb.sheets["Sheet1"].range("A1:B2").value
# >>> Returns error (traceback above), but would expect something like [[None, None], [None, None]]


wb.sheets["Sheet1"].range("A1:B3").value
# >>> Returns [2.0, 2.0], but would expect something like [[None, None], [None, None], [2.0, 2.0]]
```

**Comment by fzumstein** [comment]
This is a bug with AppleScript, see screenshot. Note that it works correctly on Windows. See similar issue https://github.com/xlwings/xlwings/issues/1028 that seems to be fixed now, so I'll try to reach out to Microsoft again with this new issue.
<img width="812" alt="Screen Shot 2022-05-27 at 10 30 56" src="https://user-images.githubusercontent.com/2265504/170662414-7b7bfa08-86c4-4ed3-834a-6b7de0b115c1.png">

**Comment by goroderickgo** [comment]
Thanks @fzumstein for the quick response! I had a hunch it might be Mac-specific, so I'll just stay tuned
