### ISSUE TITLE
Add`horizontal_alignment` and `vertical_alignment`

### ISSUE THREAD

**Issue by Blanket58** [xlwings/xlwings#1937]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.27.10, Office 365, Python 3.9

#### Describe your issue (incl. Traceback!)
I don't know how to set the `horizontal_alignment` to be `center` on macOS.

```python
# Your traceback here
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 479, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: Can't get reference. (-1728)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 515, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app('/Applications/Microsoft Excel.app', newinstance=(0, 335954)).workbooks['工作簿2'].worksheets['Sheet1'].horizontal_alignment
		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 335954)).workbooks['工作簿2'].worksheets['Sheet1'].horizontal_alignment.set(-4108)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw
from xlwings.constants import Constants

app = xw.App(visible=True, add_book=False)
wb = app.books.add()
sheet = wb.sheets.active
sheet.range('A1').value = 1
sheet.api.horizontal_alignment.set(Constants.xlCenter)
```

Furthermore, where can I find the document of how to use appscript to manipulate excel just like the document of VBA posted on microsoft's website? Thanks a lot. 🙏

**Comment by fzumstein** [comment]
mac synstax is a bit convoluted, but you can get some instructions here: https://github.com/xlwings/xlwings/blob/main/DEVELOPER_GUIDE.md#mac-implementation

**Comment by Blanket58** [comment]
Thanks! Something like this just solved my problem.
```python
from appscript import k

wb.sheets['Sheet1'].range('A:H').api.horizontal_alignment.set(k.horizontal_align_center)
```

By the way, is there any schedule about adding the alignment and border into xlwings?

**Comment by fzumstein** [comment]
Thanks for posting your solution! No ETA at the moment, sorry...

**Comment by fzumstein** [comment]
implemented in #2752
