### ISSUE TITLE
The internal function does not start from under the external function in the excel workbook (using tkinter)

### ISSUE THREAD

**Issue by AleksejCagareisvili** [xlwings/xlwings#1960]
OS (Windows 10)

Versions of xlwings, Excel and Python (e.g. 0.27.11, Excel 2016, Python 3.9, VsCode)

For interactive work with the user, I created a mini-form for requesting data (January, February, March). Based on the request, files from different months are loaded. I am using the tkinter module for this task.

In the main function - def show_message () put the action function - def clicked (), the basis of the selection (January, February, March).

This feature works in VsCode. I'm trying to run this function in the Excel workbook itself, but only a window appears with a choice of parameters (January, February, March) and a button that does not respond to pressing. That is, the internal function def clicked() does not run.

The function works only when data is entered in a small range of values, but not the entire 2-D array created from parts of the dataframe

![Code execution](https://user-images.githubusercontent.com/82659281/178732718-dfa87dae-b24d-4088-bb59-4e92fe48ec31.png)

```python
import pandas as pd
import xlwings as xw
from tkinter import *
from tkinter.ttk import Combobox


# Call function with xlwings
def show_message():
    # button press function
    def clicked():
        current_month = combo.get()
        # Condition met if January is selected
        if current_month == 'January':
            parts = []
            # Launching a cycle to collect data from different books
            for ticker in ['City_1', 'City_2', 'City_3', 'City_4', 'City_5']:
                df_0001_part = pd.read_excel(
                    f'MyProjects\\Same_folder\\{current_month}\\Same_folder_2\\{ticker}.xlsx',
                    skiprows=2,
                    nrows=5,
                    usecols='D',
                    decimal=','
                    )
                df_0001_part = df_0001_part.rename(columns={'Amount': ticker})
                df_0001_part = df_0001_part.drop(index=[0, 1, 2])
                df_0001_part.index = ['Column_1', 'Column_2']
                df_0001_part = pd.DataFrame(df_0001_part.T)
                parts.append(df_0001_part)

            df_0001_full = pd.concat(parts, axis=0).reset_index().values

            # Recording the collected data in an excel workbook (xw.Book.caller)
            wb = xw.Book.caller()
            sheet = sheet = wb.sheets[2]
            sheet.range('D2').value = df_0001_full

    window = Tk()
    window.title('Template form')
    window.geometry('200x100')

    combo = Combobox(window)
    combo['values'] = ('January', 'February', 'March')
    combo.current(0)
    combo.grid(column=2, row=0)

    btn = Button(window, text='Click!', command=clicked)
    btn.grid(column=3, row=0)

    window.mainloop()


print(show_message())
```
Please tell me where there may be an error or it's just the lack of any module compatibility.

**Comment by AleksejCagareisvili** [comment]
Used RunPython: Use UDF Server. Writes that it cannot find the file in the file directory.

I found an error. To start tkinter through the Excel shell itself, you need to specify the full path, not a relative one. Thanks for RunPython: Use UDF Server. Helped a lot!

Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "e:\common_files\data_yoga\vspractic2022\py_spripts\automation_excel\test_simple.py", line 57, in clicked
    df_7104_part = pd.read_excel(f'py_spripts\\automation_excel\\{current_month}\\report_7104\\{ticker}.xlsx',
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1376, in __init__
    ext = inspect_excel_format(
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1250, in inspect_excel_format
    with get_handle(
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'py_spripts\\automation_excel\\January\\report_7104\\City_1.xlsx

![FileNotFoundError](https://user-images.githubusercontent.com/82659281/178780584-0f10d3fb-428a-40d4-ba07-67d262e8d2c5.png)
