### ISSUE TITLE
#xlwings  OSERROR: -1743 MESSAGE: The user has declined permission.

### ISSUE THREAD

**Issue by Canaan115** [xlwings/xlwings#1966]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version: 0.27.11     |     Python version 3.10
#### Describe your issue (incl. Traceback!)

no matter what IDE(Main IDE is Pycharm) I use I receive the same result, even on terminal both Bash & zsh, but if I use Iterm2 this problem does not occur. 

The permission window never loads, but if I run the python program in iterm2 which is on a lower level of permissions(closer to root but not root) this problem does not occur. I thought the problem was with the IDE, but it is with xlwings on the MacOS.

```python
# Your traceback here
/usr/local/bin/python3 /Users/someone/PycharmProjects/SomeFile/What.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aeosa/appscript/reference.py", line 479, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The user has declined permission. (-1743)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/someone/PycharmProjects/SomeFile/What.py", line 3, in <module>
    xw.Book()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xlwings/main.py", line 862, in __init__
    impl = apps.active.books.add().impl
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xlwings/main.py", line 4819, in add
    return Book(impl=self.impl.add())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xlwings/_xlmac.py", line 346, in add
    if self.app.visible:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xlwings/_xlmac.py", line 220, in visible
    .visible.get()[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aeosa/appscript/reference.py", line 515, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: The user has declined permission.
		COMMAND: app('/System/Library/CoreServices/System Events.app').processes[its.unix_id == 3098].visible.get()

Process finished with exit code 1
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
```python
# Your code here
import xlwings as xw

xw.Book()
```

**Comment by fzumstein** [comment]
Can you try if the solution in https://github.com/xlwings/xlwings/issues/1851 works for you? This operation probably requires root privileges and causes the issue if you don't have that. That should be fixable.

**Comment by Canaan115** [comment]
Sorry for late reply, I got sick; Anyways, I have tried the solution issue #1851, but that did not work. I will give the updated code a try. Thank you.

**Comment by Canaan115** [comment]
The update code works just fine now, but still the issue persists in PyCharm. Terminal and others the issue is no longer present. I will continue reaching out to PyCharm to try to get the issue resolve with the IDE.

**Comment by fzumstein** [comment]
You can always start PyCharm from the Terminal to get rid of the issue (or wait for an upgrade that fixes it for you).
