### ISSUE TITLE
UDF returning multiple arrays stopped working after xlwings-0.27.11

### ISSUE THREAD

**Issue by SimoneD89** [xlwings/xlwings#1972]
#### OS:
- Windows 10

#### Versions of xlwings, Excel and Python
- xlwings-0.27.11 (first version where my script broke)
- python 3.10.5
- Excel 365

#### Describe your issue (incl. Traceback!)
After the module update, (0.27.10 -> 0.27.11) my script stopped working. The problem arises from the new pd.NA compatibility. My script was a UDF call from Excel (VBA) where the function returns two numpy arrays. See the minimal example for a better understanding

```python
# Your traceback here
Traceback (most recent call last):
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return func(*args)
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\server.py", line 230, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\udfs.py", line 549, in call_udf
    xl_result = conversion.write(ret, None, ret_info["options"])
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\conversion\__init__.py", line 80, in write
    pipeline(ctx)
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\conversion\framework.py", line 76, in __call__
    stage(*args, **kwargs)
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\conversion\standard.py", line 118, in __call__
    c.value = [
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\conversion\standard.py", line 119, in <listcomp>
    [c.engine.impl.prepare_xl_data_element(x) for x in y] for y in c.value
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\conversion\standard.py", line 119, in <listcomp>
    [c.engine.impl.prepare_xl_data_element(x) for x in y] for y in c.value
  File "c:\users\sdresti\appdata\local\programs\python\python310\lib\site-packages\xlwings\_xlwindows.py", line 425, in prepare_xl_data_element
    elif pd and pd.isna(x):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

#### Include a minimal code sample to reproduce the issue
The following code works in xlwings-0.27.10 but not in xlwings-0.27.11

Python UDF
```python
def toy_func():
    return (
        np.array(["1", "2"]),
        np.array(["1", "2"])
    )
```

Macro code in Excel
```VBA
Dim PythonArray() As Variant
PythonArray() = toy_func()

first_array = PythonArray(0)
second_array = PythonArray(1)
```

**Comment by fzumstein** [comment]
Returning multiple values from a function isn't supported, so you've been relying on a hack, unfortunately.

**Comment by SimoneD89** [comment]
Thanks for the reply. It would be nice to keep this "unwanted" feature (if possible), by using some workaround (since it is almost supported).

I guess it would be enough to replace (line 425 in _xlwindows.py)
`elif pd and pd.isna(x):`
with
`elif pd and pd.isna(x) is True:`

Kind Regards

**Comment by fzumstein** [comment]
You'd get hit further down the road though. For example, if your array would look like this:

```python
import xlwings as xw
import numpy as np
import datetime as dt

@xw.func
def toy_func():
    return (
        np.array([dt.datetime(2000, 1, 1), dt.datetime(2000, 1, 2)]),
        np.array([dt.datetime(2000, 1, 1), dt.datetime(2000, 1, 2)])
    )

```

you would not get the correct datetime conversion.
