### ISSUE TITLE
MacOS M1 + Wps office  Application could not handle this command.

### ISSUE THREAD

**Issue by ZhaoyangJia** [xlwings/xlwings#1990]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Monterey 12.5 M1 
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings:0.27.12 Excel:wpsoffice ,python 3.8.13
#### Describe your issue (incl. Traceback!)
Run the following code:
```python
# Your traceback here
if __name__ == "__main__":
    file1 = "/Users/zhaoyangjia/Desktop/a.xlsx"
    app = xw.App(spec="wpsoffice",visible=True,add_book=False) # mac指定app，不创建表格
    wb = app.books.open(file1)
```
Error:
```
(base) zhaoyangjia@Air ~ % /Users/zhaoyangjia/opt/miniconda3/bin/python /Users/zhaoyangjia/Documents/test.py
Traceback (most recent call last):
  File "/Users/zhaoyangjia/opt/miniconda3/lib/python3.8/site-packages/aeosa/appscript/reference.py", line 479, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Users/zhaoyangjia/opt/miniconda3/lib/python3.8/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: Application could not handle this command. (-1708)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaoyangjia/Documents/test.py", line 44, in <module>
    wb = app.books.open(file1)
  File "/Users/zhaoyangjia/opt/miniconda3/lib/python3.8/site-packages/xlwings/main.py", line 4872, in open
    impl = self.impl(name)
  File "/Users/zhaoyangjia/opt/miniconda3/lib/python3.8/site-packages/xlwings/_xlmac.py", line 339, in __call__
    if not b.xl.exists():
  File "/Users/zhaoyangjia/opt/miniconda3/lib/python3.8/site-packages/aeosa/appscript/reference.py", line 515, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
                OSERROR: -1708
                MESSAGE: Application could not handle this command.
                COMMAND: app('/Applications/wpsoffice.app', newinstance=(0, 1265973)).workbooks['a.xlsx'].exists()
```

**Comment by fzumstein** [comment]
Unfortunately, xlwings does not support WPS -- only Excel and Google Sheets (via remote interpreter).
