### ISSUE TITLE
OneDrive workbook.save() fails when using existing full path.

### ISSUE THREAD

**Issue by wbrenneman** [xlwings/xlwings#1997]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.27.10, Office 365, Python 3.9.13 64-bit
#### Describe your issue (incl. Traceback!)
When working with a synced file on OneDrive, and attempting to save the workbook, if the path arg matches workbook.fullname the workbook.xl.SaveAs() function is used instead of the workbook.xl.Save() and OneDrive throws a fit and the save fails.  However, if no path is provided the save works.

```python
Traceback (most recent call last):
  File "C:\GIT\ScriptToolbox\Azure_Boards_Scripts\workitems\test.py", line 6, in <module>
    foo.save(path)
  File "C:\Users\U369603\AppData\Local\Programs\Python\Python39\lib\site-packages\xlwings\main.py", line 1065, in save
    self.impl.save(path, password=password)
  File "C:\Users\U369603\AppData\Local\Programs\Python\Python39\lib\site-packages\xlwings\_xlwindows.py", line 838, in save
    self.xl.SaveAs(
  File "C:\Users\U369603\AppData\Local\Programs\Python\Python39\lib\site-packages\xlwings\_xlwindows.py", line 104, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\U369603\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py", line 46807, in SaveAs
    return self._oleobj_.InvokeTypes(3174, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (3, 49), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', "Cannot access 'test.xlsx'.", 'xlmain11.chm', 0, -2146827284), None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xl

path = r"C:\Users\U369603\OneDrive - Company\test.xlsx"

foo = xl.Book(path)
foo.save(path)

```

**Comment by wbrenneman** [comment]
Something like this in _xlwindows.py and _xlmac.py ??
```
if ((saved_path != "") and (path is None)) or (saved_path == path):
    # Previously saved: Save under existing name
    self.xl.Save()
```

**Comment by fzumstein** [comment]
thanks! yes, something like this will work.
