### ISSUE TITLE
Unable to api.copy() range on Mac

### ISSUE THREAD

**Issue by JavascriptMick** [xlwings/xlwings#1998]
#### OS (e.g. Windows 10 or macOS Sierra)
MacOS Big Sur 11.6.8

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings                   0.27.7                   pypi_0    pypi
Excel Mac Version 16.64
Python 3.9.12

#### Describe your issue (incl. Traceback!)
Trying to copy data validation from cell to another cell.

According to this ref (if there is a better ref for these api workarounds, please tell me)...
/Users/[Me]/anaconda3/envs/[my_env]/lib/python3.9/site-packages/xlwings/_xlmac.py
...there should be a *copy* command on the api.

So I am trying to do something like this...
```python
sht.range('A1:A6').api.copy
sht2.range("A1").api.select
sht2.api.paste
```

but I can't even get the copy to work...

```python
range_test.api.copy()
Traceback (most recent call last):
  File "/Users/mdausmann/anaconda3/envs/dev-prolims-conversion/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 596, in __getattr__
    selectortype, code = self.AS_appdata.referencebyname()[name]
KeyError: 'copy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mdausmann/anaconda3/envs/dev-prolims-conversion/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 598, in __getattr__
    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'copy'

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
wb_test = xw.Book()
range_test = wb_test.sheets['Sheet1'].range("A1")
range_test.api.copy()
```

**Comment by JavascriptMick** [comment]
ok, I am dumb.  Apparently I can just
```Python
range.copy()
range_to.paste('validation')
```

dumb dumb dumb.
