### ISSUE TITLE
`Python error invoking COM method` if opening more than one xlsm file

### ISSUE THREAD

**Issue by AndreasMatthias** [xlwings/xlwings#2002]
* Run the following powershell script which creates two xlsm files.

```
xlwings quickstart foo
xlwings quickstart bar

"import xlwings as xw

@xw.func
def Moo():
    return 123
" | Out-File -Encoding UTF8 -FilePath bar/bar.py
```

* Open file `bar.xlsm`
* Insert `=Moo()` in cell A1
* Goto xlwings Ribbon:
   * activate "Show Console"
   * click "Import Functions" 
* Open file `foo.xlsm`

Now a console windows appears with the following content:

```
xlwings server running, clsid={AC756C73-FCCE-4810-968F-C0BF121AE444}, event loop on 5660
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\MyProgs\python\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\MyProgs\python\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\MyProgs\python\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return func(*args)
  File "C:\MyProgs\python\lib\site-packages\xlwings\server.py", line 230, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\MyProgs\python\lib\site-packages\xlwings\udfs.py", line 454, in call_udf
    module = get_udf_module(module_name, this_workbook)
  File "C:\MyProgs\python\lib\site-packages\xlwings\udfs.py", line 413, in get_udf_module
    module = import_module(module_name)
  File "C:\MyProgs\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bar'
```

I've tested this scenario on two different computers. On the newer one with a recent Office 365, the function name, `Moo()` in this example, had to start with an uppercase letter. Otherwise I could  not trigger this issue. However, on an older computer with Office 2013 I could always trigger this issue, whether or not the function name started with an uppercase letter.

I've noticed that after running `Import Functions` again and recalculation the worksheet, this issue disappears. I did not notice any further problems afterwards during this session. But once I opened these files again, I got this error message again.

As far as I can say, this is just an issue during opening the files.

**Comment by fzumstein** [comment]
I can replicate this (thanks for including the detailed steps) but nothing off the top of my head that I could think of causing this...
