### ISSUE TITLE
Xlwings / detailed error message?

### ISSUE THREAD

**Issue by Rapid1898-code** [xlwings/xlwings#2003]
I try to read an excel-sheet with the following code:

```
import os
import sys
import xlwings as xw

if __name__ == '__main__':
  SAVE_INTERVAL = 10
  path = os.path.abspath(os.path.dirname(sys.argv[0]))  
  fn = os.path.join(path, "TESTinput.xlsx")    
  wb = xw.Book (fn)
  ws1 = wb.sheets[0]
  inpNorth = ws1.range("A2:Z20").value
```

Due the reason that there is (for whatever reason) a negative valiue in a date-formated field (-693555)I am not able to read the excel and get the following error:

```
$ python test.py
Traceback (most recent call last):
  File "C:\DEV\Fiverr\ORDER\seitzmax\test.py", line 15, in <module>
    inpNorth = ws1.range("A2:Z20").value
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\main.py", line 2267, in value
    return conversion.read(self, None, self._options)
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\conversion\__init__.py", line 55, in read
    pipeline(ctx)
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\conversion\framework.py", line 76, in __call__
    stage(*args, **kwargs)
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\conversion\standard.py", line 99, in __call__
    c.value = c.range.raw_value
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\main.py", line 1833, in raw_value
    return self.impl.raw_value
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 1118, in raw_value
    return self.xl.Value
  File "C:\DEV\.venv\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 181, in __getattr__
    v = getattr(self._inner, item)
  File "C:\DEV\.venv\xlwings\lib\site-packages\win32com\client\__init__.py", line 583, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\DEV\.venv\xlwings\lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_e
```

Is it possible to read from this error-message in which line the wrong value is?Or is there any other way to handle this wrong entries with xlwing and not only get a general error message?
(when handling big files with somewhere an error in it this is really problematic...)

Find attached the xlsx i can´t read and get the error.

[TESTinput.xlsx](https://github.com/xlwings/xlwings/files/9443621/TESTinput.xlsx)

**Comment by fzumstein** [comment]
I think you'll need to use the `value2` property, that unfortunately hasn't been implemented natively yet (see https://github.com/xlwings/xlwings/issues/1238). So for now just juse `myrange.api.Value2`. This gives you the unformatted value and you can look for the negative value.

**Comment by Rapid1898-code** [comment]
Thanks a lot for the response -
When i understand it right - i have to check the xlsx i want to import manually as described above.
There is no automatic check in any way when reading the xlsx with the .range-method.
Correct?

**Comment by fzumstein** [comment]
Sort of, yes. You could also just do `ws1.range("A2:Z20").api.Value2` and transform the date serial into a Python datetime yourself. While xlwings doesn't have a helper function for that, I believe xlrd or OpenPyXL have.
