### ISSUE TITLE
Class Not Registered Issue

### ISSUE THREAD

**Issue by lakshyap98** [xlwings/xlwings#2016]
I'm trying to open file with xlwings, getting this error:

```
import xlwings
app = xlwings.App(visible=False)

pywintypes.com_error: (-2147221164, 'Class not registered', None, None)
```

**Comment by fzumstein** [comment]
This looks like an issue with Excel and/or pywin32, a dependency of xlwings. Do you get the same when running `xw.Book()`? See e.g., https://windowsreport.com/class-not-registered-vba/

**Comment by lakshyap98** [comment]
No @fzumstein 

Even when i try **xlwings.books**, it's throwing **Nonetype has no attribute books**

**Comment by fzumstein** [comment]
please post the full traceback/error message, thanks!

**Comment by lakshyap98** [comment]
```
import xlwings
xlwings.Books()
```
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'xlwings' has no attribute 'Books'**

```
xlwings.books
```
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\main.py", line 97, in _repr_
    for i, x in enumerate(self):
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\main.py", line 67, in _iter_
    for impl in self.impl:
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\main.py", line 5038, in impl
    return apps.active.books.impl
AttributeError: 'NoneType' object has no attribute 'books'**

```
xlwings.Books
```
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'xlwings' has no attribute 'Books'**

```
app = xlwings.App(visible=False)
```
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\main.py", line 279, in _init_
    self.impl = engines.active.apps.add(
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\main.py", line 188, in add
    return App(impl=self.impl.add(**kwargs))
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\_xlwindows.py", line 506, in add
    return App(spec=spec, add_book=add_book, xl=xl, visible=visible)
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\xlwings\_xlwindows.py", line 530, in _init_
    self._xl = COMRetryObjectWrapper(DispatchEx("Excel.Application"))
  File "C:\Users\Lucifer\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\_init_.py", line 145, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(
pywintypes.com_error: (-2147221164, 'Class not registered', None, None)**

**Comment by fzumstein** [comment]
I removed your invalid commands from the last comment to not confuse other users. So yeah, I think you should try to repair Excel, it's not an issue with xlwings directly. Maybe with pywin32, but looks more like Excel to me.
