### ISSUE TITLE
Folders from OneDrive resolve incorrect fullname if subpaths

### ISSUE THREAD

**Issue by dpwrussell** [xlwings/xlwings#2017]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Monterey 12.5.1

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.27.14
Python 3.10.6
Excel 16.64

#### Describe your issue (incl. Traceback!)

In OneDrive (for business) I am looking at some files from a colleague. The files of interest are in a path like `Bob/Project/Project1`. I am only interested in `Project1`, so I used the `Add shortcut to my files` button in OneDrive to get that directory to appear on my locally synced OneDrive. This works just fine. I can see within my local OneDrive root, a folder called `Project1`.

However, when I try and use `xlwings` to read an Excel document in there, I get an error because the fullname that has been resolved for this file is (I debugged the Python code):

```
/Users/dpwrussell/Documents/OneDrive - MyBusiness/Projects/Project1/sheet.xlsx
```

when I think it should have been:

```
/Users/dpwrussell/Documents/OneDrive - MyBusiness/Project1/sheet.xlsx
```

Basically, because it's OneDrive, the filename has been resolved into a URL, then back to a file path, but the file path assumes a full path which is not the case here because only `Project1` has been added to my OneDrive, not `Projects`. It isn't possible to `Add shortcut to my files` from `Projects` so that isn't even possible as a workaround (assuming that works).

```python
Traceback (most recent call last):
  File "/Users/dpwrussell/Code/project1code/main.py", line 13, in <module>
    wb = xw.Book(file_name)
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/main.py", line 867, in __init__
    wb.fullname.lower() == fullname
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/main.py", line 1118, in fullname
    return self.impl.fullname
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/_xlmac.py", line 538, in fullname
    return fullname_url_to_local_path(
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/utils.py", line 546, in fullname_url_to_local_path
    raise xlwings.XlwingsError(
xlwings.XlwingsError: Couldn't find your local OneDrive for Business file, see: xlwings.org/error
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
wb = xw.Book('/Users/dpwrussell/Documents/OneDrive - MyBusiness/Project1/sheet.xlsx')
```

**Comment by fzumstein** [comment]
Yeah, Microsoft couldn't have messed this one up any worse. So you are running the code from Python and not from Excel via RunPython, correct?

**Comment by dpwrussell** [comment]
Yes, I'm just using `xlwings` as a convenient library to read Excel files from a Python application. Excel is not actively involved.

**Comment by fzumstein** [comment]
Right, I think this particular case is solvable by creating a dict of URL/local path after opening the file and looking there first when doing the transformation from url to local path.

As a workaround for now, you could disable `File collaboration` in the OneDrive preferences, followed by a full restart of Excel `Cmd-Q`. This will give you back the local file paths, but will prevent you from working on a file in the "Google Sheets" mode. 

<img width="652" alt="Screen Shot 2022-09-14 at 14 12 28" src="https://user-images.githubusercontent.com/2265504/190150990-9c26db5c-0041-465d-8aae-b8fa033ea9dd.png">
