### ISSUE TITLE
Converters in nested UDF calls

### ISSUE THREAD

**Issue by rizzato** [xlwings/xlwings#2070]
#### Given the UDFs and date converter bellow:

```python
# Your code here
def my_date_converter(year,month,day,**kwargs):
    return np.datetime64('%04i-%02i-%02i' % (year,month,day)).astype('datetime64[D]')
    
@xw.func
def list_of_dates():
    return [np.datetime64('2022-10-17'), np.datetime64('2022-10-18')]

@xw.func
@xw.arg('dates_arg', dates=datetime.date)
def whatever(dates_arg):
    return [np.datetime64(dt)+np.timedelta64(1,'D') for dt in dates_arg]
```

#### The type conversion is made in the return from the list_of_dates function but not converted back to date for the args of the whatever function.

**Comment by fzumstein** [comment]
Here's a copy/pasteable example of your code:

```python
import xlwings as xw
import numpy as np
import datetime
    
@xw.func
def list_of_dates():
    return [np.datetime64('2022-10-17'), np.datetime64('2022-10-18')]

@xw.func
@xw.arg('dates_arg', dates=datetime.date)
def whatever(dates_arg):
    print(dates_arg)  # <== print the args
    return [np.datetime64(dt)+np.timedelta64(1,'D') for dt in dates_arg]

```

And here is the output (Show Console):

```python
[44851.0, 44852.0]  # <== Date Serial
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\felix\Miniconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "c:\users\felix\dev\xlwings\xlwings\server.py", line 235, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "c:\users\felix\dev\xlwings\xlwings\udfs.py", line 539, in call_udf
    ret = func(*args)
  File "c:\users\felix\desktop\gh\gh.py", line 17, in whatever
    return [np.datetime64(dt)+np.timedelta64(1,'D') for dt in dates_arg]
  File "c:\users\felix\desktop\gh\gh.py", line 17, in <listcomp>
    return [np.datetime64(dt)+np.timedelta64(1,'D') for dt in dates_arg]
ValueError: Could not convert object to NumPy datetime
[datetime.date(2022, 1, 31), datetime.date(2022, 1, 30)]
```

UDFs don't automatically format the cells as Date in Excel, so what you get as input to your `np.datetime64` input is a date serial, not a datetime object.

**Comment by rizzato** [comment]
Exact, just lilke when you use a range as the input. But the problem is that in the nested call, the converter defined in the _whatever_ function _dates_arg_ argument is not being called.

**Comment by rizzato** [comment]
I'm a bit, lost. I'm using `np.datetime64` transparently in my UDFs, I mean if a UDF returns `np.datetime64`, it reaches excel as expected (Date Serial). Is there another layer of conversion to transform Date Serial into datetime objects? 
Is there an UDF call lifecicle map in the docs?
Thanks a lot for the fast response.
