### ISSUE TITLE
ValueError: set_wakeup_fd only works in the main thread of the main interpreter 

### ISSUE THREAD

**Issue by Turbolento** [xlwings/xlwings#2084]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.27.14,  WPS,  Python3.9
#### Describe your issue (incl. Traceback!)
My application needs to run as a Windows service, and when I run it, I get the error "ValueError: set_wakeup_fd only works in the main thread of the main interpreter "

```python
# Your traceback here
Traceback (most recent call last):
  File "D:\rpa\test.py", line 15, in <module>
    from business.koubei import download_koubei_task, download_koubei_month_task
  File "D:\rpa\business\koubei.py", line 15, in <module>
    from util.log import logger
  File "D:\rpa\util\log.py", line 9, in <module>
    from util.func_tools import root_path
  File "D:\rpa\util\func_tools.py", line 10, in <module>
    import xlwings as xw
  File "C:\Program Files\Python39\lib\site-packages\xlwings\__init__.py", line 145, in <module>
    from .server import serve
  File "C:\Program Files\Python39\lib\site-packages\xlwings\server.py", line 326, in <module>
    loop = asyncio.new_event_loop()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 315, in __init__
    super().__init__(proactor)
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 633, in __init__
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter 
```

**Comment by fzumstein** [comment]
Please provide full instructions on how to replicate this error message. Also, WPS is not officially supported, but I am not sure if it's got to do anything with it.
