### ISSUE TITLE
AttributeError: Unknown property, element or command: 'Copy'

### ISSUE THREAD

**Issue by AlessandroFazio** [xlwings/xlwings#2117]
- MacOS 12.4

- Versions of xlwings 0.27.15, 
- Excel 16.67
- Python3.10

Hello, I'm running this common piece of code and I'm getting problems.

dirName = "path"

listOfFiles = list()
for (dirpath, dirnames, filenames) in os.walk(dirName):
    listOfFiles += [os.path.join(dirpath, file) for file in filenames]

combined_wb = xw.Book()

for file in listOfFiles:
    wb = xw.Book(file)
    for sheet in wb.sheets:
        sheet.api.Copy(After=combined_wb.sheets[-1].api)

Traceback (most recent call last):
  File "/var/root/.conda/envs/pythonProject1/lib/python3.10/site-packages/aeosa/appscript/reference.py", line 599, in __getattr__
    selectortype, code = self.AS_appdata.referencebyname()[name]
KeyError: 'Copy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alessandrofazio/PycharmProjects/pythonProject1/portfolio/applications/report_builder.py", line 22, in <module>
    sheet.api.Copy(After=combined_wb.sheets[-1].api)
  File "/var/root/.conda/envs/pythonProject1/lib/python3.10/site-packages/aeosa/appscript/reference.py", line 601, in __getattr__
    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'Copy'

I tried with copy and Copy but none of them seems to work. Any suggestion?

**Comment by fzumstein** [comment]
copy is available natively: https://docs.xlwings.org/en/stable/api.html#xlwings.Sheet.copy
