### ISSUE TITLE
NotImplementedError when I want to save file

### ISSUE THREAD

**Issue by quenlowi** [xlwings/xlwings#2120]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.28.5 + Python 3.7.6

#### Describe your issue (incl. Traceback!)

NotImplementedError when I want to save file

```python
Traceback (most recent call last):
  File "D:\MY_CODE\test.py", line 8, in <module>
    book.save('test.xlsx')
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\main.py", line 1145, in save
    with self.app.properties(display_alerts=False):
  File "C:\Code\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\main.py", line 655, in properties
    initial_state[attribute] = getattr(self, attribute, value)
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\main.py", line 422, in display_alerts
    return self.impl.display_alerts
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\base_classes.py", line 65, in display_alerts
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MY_CODE\test.py", line 8, in <module>
    book.save('test.xlsx')
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\main.py", line 773, in __exit__
    self.quit()
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\main.py", line 388, in quit
    return self.impl.quit()
  File "C:\Code\Python\Python37\lib\site-packages\xlwings\base_classes.py", line 50, in quit
    raise NotImplementedError()
NotImplementedError
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

with xw.App(visible=True,add_book=False) as app:
      book = app.books.add()
      sht = book.sheets.add()
      sht.range('A1').value = 'Hello World'
      book.save('test.xlsx')
```

**Comment by fzumstein** [comment]
You must be missing the `pywin32` dependency. Run `pip install pywin32` and try again. I need to look into improving the error message.

**Comment by quenlowi** [comment]
Actually I have already installed pywin32. I uninstalled it and installed it again, the error persists.
pywin32-305-cp37-cp37m-win_amd64.whl

I'm guessing this error is the same unknown reason as my other issue
https://github.com/xlwings/xlwings/issues/2119
since when I transfer files to my friend's computer, the problems go away
But on my computer it just doesn't work, which bothers me

**Comment by fzumstein** [comment]
Maybe there's something up with your Python installation. You could try Anaconda or miniconda and see if this works. I am going to close this issue as this seems specific to your environment and neither your friend nor I can replicate it. I shall be working on better error messages though.
