### ISSUE TITLE
xlwings.XlwingsError: Make sure to have "appscript" and "psutil", dependencies of xlwings, installed.

### ISSUE THREAD

**Issue by lssee003** [xlwings/xlwings#2128]
#### OS (e.g. Windows 10 or macOS Sierra)
Mac OS Apple M2 Ventura 13.1 (22C65)

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.9.13
Excel for Mac 16.68
appscript                     1.1.2
psutil                        5.9.0
xlwings                       0.27.15

#### Describe your issue (incl. Traceback!)

I am trying to use the package and am encountering this error. It works on jupyter notebook but not on pycharm. 

I have tried reinstalling all packages but doesn't work. 

```python
Traceback (most recent call last):
  File "/Users/xxx/Desktop/TD API/test.py", line 3, in <module>
    wb = xw.Book()
         ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xlwings/main.py", line 938, in __init__
    if apps.active:
       ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xlwings/main.py", line 212, in active
    for app in self.impl:
               ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xlwings/main.py", line 5119, in impl
    raise XlwingsError(
xlwings.XlwingsError: Make sure to have "appscript" and "psutil", dependencies of xlwings, installed.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

wb = xw.Book()
```

**Comment by fzumstein** [comment]
You're most likely using another Python installation/virtual environment in PyCharm that doesn't have these packages installed.

**Comment by fzumstein** [comment]
closing this due to inactivity
