### ISSUE TITLE
OSERROR: -1743 MESSAGE: The user has declined permission.

### ISSUE THREAD

**Issue by floraFoodi** [xlwings/xlwings#2138]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS BigSur 11.6
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
'0.28.7', Python 3.9.2
#### Describe your issue (incl. Traceback!)
"The user has declined permission" issue.  Read through all the post related to it. Tried to run under visual studio code ( where the program was originally developed), terminal in visual studio code and terminal but still get the same error.  
```python
# Your traceback here
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:09:00) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.28.7'
>>> xlwings.Book()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 479, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The user has declined permission. (-1743)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlwings/main.py", line 939, in __init__
    impl = apps.active.books.add().impl
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlwings/main.py", line 4958, in add
    return Book(impl=self.impl.add())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlwings/_xlmac.py", line 401, in add
    xl = self.app.xl.make(new=kw.workbook)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 515, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: The user has declined permission.
		COMMAND: app(pid=1368).make(new=k.workbook)
>>> 
```
<img width="336" alt="Screen Shot 2023-01-11 at 6 42 19 PM" src="https://user-images.githubusercontent.com/31659630/211941762-ab73d691-7e1f-4e6a-a000-d17b64a5ca30.png">

**Comment by fzumstein** [comment]
If this doesn't work in a Terminal, then I don't know what could make this work... are you using the built-in Terminal?

**Comment by floraFoodi** [comment]
I tried the first suggestion in #967 "in Excel, under Preferences > General, uncheck the Show Workbook Gallery when opening Excel." and it fixed the permission issue. Now when I tried to run the "run main" button from excel, it asked for "To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again." I am pretty sure it has been installed. Will investigate more.

**Comment by floraFoodi** [comment]
Issue resolved. Seems like the interpreter of the addin was pointing to a wrong python package. Did a "xlwings addin remove",  "xlwings addin install", xlwings config create --force and solved the issue.
