### ISSUE TITLE
Finding files with os.walk works when python is called as mock_caller, but fails when run with RUN button

### ISSUE THREAD

**Issue by andresrodri22** [xlwings/xlwings#2164]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
"""So the Issue is I'm trying to retrieve an absolute path for a file whithin any path, in this case I used the current working directory.
It returns the correct string and it's written to the A1 cell as supposed in the code when the macro is called from python. 
But returns NoneTypen when called within the RUN main button inside Excel.
then the way the folders are structures is:
-myAPP
   --Folder to look files for
      ---SubFolders
   --demo.xslm
   --demo.py
"""

Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\arodriguez\documents\python plc hardware\hardware.py", line 56, in main

    final_aml = et.parse(empty_hardware_path)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse

  File "src\lxml\parser.pxi", line 1902, in lxml.etree._parseDocument

TypeError: cannot parse from 'NoneType'
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
def find_file_cwd(filename):
    # --> Return the absolute path given the file name, whithin current directory.
    for relPath,dirs,files in os.walk(os.getcwd()):
        for dir in dirs:
            for rp,d,f in os.walk(dir):
                if(filename in f):
                    full_path = os.path.join(os.getcwd(),rp,filename)
                    return full_path
def main():
    wb = xw.Book.caller()
    # main()
    print("script running...")
    empty_hardware_path = find_file_cwd("empty-hardware.aml")
         if(empty_hardware_path!=None):
             wb.sheets['CPU'].range('A1').value = empty_hardware_path
         else:
              wb.sheets['CPU'].range('A1').value = str(type(empty_hardware_path))
```

**Comment by fzumstein** [comment]
you can't rely on the working directory, see e.g.,: https://github.com/xlwings/xlwings/issues/815

**Comment by andresrodri22** [comment]
I also tried to retrieve the the file path hardcoding the directory instead of os.getwcd() such as: "C:\\users\\myuser\\Documents\\Python PLC Hardware",  r"C:\users\myuser\Documents\Python PLC Hardware" but is still has the same behavior. It finds empty-hardware.xml when ran with python, but fails with RUN button witin Excel sheet.

![issue-img1](https://user-images.githubusercontent.com/58445973/217567417-f4546ed3-4d76-4cf8-98dc-af06a117d24d.png)

**Comment by fzumstein** [comment]
And this isn't an issue becasuse it says `aml` instead of `xml` in the screenshot?

**Comment by andresrodri22** [comment]
No, it's a typo here in the comment, but in the code is ok. In the inital comment is a sample of the code I'm using.
