### ISSUE TITLE
The 'remote' engine requires xlwings PRO

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2212]
#### OS (e.g. Windows 10 or macOS Sierra)
Docker development on macOS

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.30.2
Python 3.11.2
Office 365

#### Describe your issue (incl. Traceback!)
[Demo repository](https://github.com/Jeroendevr/fastapi-docker-xlwings)

```python
fastcontainer  | INFO:     Started server process [1]
fastcontainer  | INFO:     Waiting for application startup.
fastcontainer  | INFO:     Application startup complete.
fastcontainer  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
fastcontainer  | INFO:     172.26.0.1:53478 - "POST /hello HTTP/1.1" 500 Internal Server Error
fastcontainer  | ERROR:    Exception in ASGI application
fastcontainer  | Traceback (most recent call last):
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/xlwings/main.py", line 135, in __getitem__
fastcontainer  |     return self.engines_by_name[name_or_index]
fastcontainer  |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
fastcontainer  | KeyError: 'remote'
fastcontainer  | 
fastcontainer  | During handling of the above exception, another exception occurred:
fastcontainer  | 
fastcontainer  | Traceback (most recent call last):
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
fastcontainer  |     result = await app(  # type: ignore[func-returns-value]
fastcontainer  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fastcontainer  |     return await self.app(scope, receive, send)
fastcontainer  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
fastcontainer  |     await super().__call__(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
fastcontainer  |     await self.middleware_stack(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
fastcontainer  |     raise exc
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
fastcontainer  |     await self.app(scope, receive, _send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
fastcontainer  |     await self.app(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
fastcontainer  |     raise exc
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
fastcontainer  |     await self.app(scope, receive, sender)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
fastcontainer  |     raise e
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
fastcontainer  |     await self.app(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
fastcontainer  |     await route.handle(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
fastcontainer  |     await self.app(scope, receive, send)
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
fastcontainer  |     response = await func(request)
fastcontainer  |                ^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
fastcontainer  |     raw_response = await run_endpoint_function(
fastcontainer  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
fastcontainer  |     return await run_in_threadpool(dependant.call, **values)
fastcontainer  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
fastcontainer  |     return await anyio.to_thread.run_sync(func, *args)
fastcontainer  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
fastcontainer  |     return await get_asynclib().run_sync_in_worker_thread(
fastcontainer  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
fastcontainer  |     return await future
fastcontainer  |            ^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
fastcontainer  |     result = context.run(func, *args)
fastcontainer  |              ^^^^^^^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/src/app/app/main.py", line 17, in hello
fastcontainer  |     book = xw.Book(json=data)
fastcontainer  |            ^^^^^^^^^^^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/xlwings/main.py", line 897, in __init__
fastcontainer  |     impl = engines[engine].apps.active.books.open(json=json).impl
fastcontainer  |            ~~~~~~~^^^^^^^^
fastcontainer  |   File "/usr/local/lib/python3.11/site-packages/xlwings/main.py", line 138, in __getitem__
fastcontainer  |     raise LicenseError(
fastcontainer  | xlwings.LicenseError: The 'remote' engine requires xlwings PRO.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Demo workbook as from the fastapi demo
docker.yaml
```yaml
FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
```

compose.yaml
```yaml
services:
  api:
    build: .
    container_name: fastcontainer
    environment:
      PORT: 8000
    env_file:
      - dev.env
    ports:
      - '8000:8000'
    restart: "no"
```

```env
XLWINGS_LICENSE_KEY={deploykey}
```

I think I need to set my deploy key somewhere in the docker environment. Is 'remote' the docker container or the workbook?

**Comment by Jeroendevr** [comment]
#2211 related to this issue perhaps?

**Comment by fzumstein** [comment]
> #2211 related to this issue perhaps?

no, that's for .30.3 and only when running the CLI

I can't replicate the issue using your repo. How are you starting the process? The container needs to have access to the env var that you set in dev.env. Have you tried working off this repo? https://github.com/xlwings/xlwings-server-helloworld-fastapi

**Comment by Jeroendevr** [comment]
Tried to reproduce it myself without any luck. So I close this issue. Thanks for looking into it.
