### ISSUE TITLE
unittest xlwings as developer - XLWINGS_LICENSE_KEY_SECRET has no attribute encode

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2220]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Ventura
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings - latest from source
Python - 3.9.16
Excel - Office 365
#### Describe your issue (incl. Traceback!)
Cloned the git repository and installed as suggested in the [DEVELOPER_GUIDE](https://github.com/Jeroendevr/xlwings/blob/master/DEVELOPER_GUIDE.md)

```shell
python -m unittest test_active.py

Traceback (most recent call last):
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/hayer/.pyenv/versions/3.9.16/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/hayer/xlwings/tests/test_active.py", line 4, in <module>
    import xlwings as xw
  File "/Users/hayer/xlwings/xlwings/__init__.py", line 39, in <module>
    from .main import (
  File "/Users/hayer/xlwings/xlwings/main.py", line 2916, in <module>
    from . import conversion, expansion
  File "/Users/hayer/xlwings/xlwings/conversion/__init__.py", line 18, in <module>
    from .standard import (
  File "/Users/hayer/xlwings/xlwings/conversion/standard.py", line 11, in <module>
    from ..pro import Markdown
  File "/Users/hayer/xlwings/xlwings/pro/__init__.py", line 14, in <module>
    from .embedded_code import dump_embedded_code, runpython_embedded_code
  File "/Users/hayer/xlwings/xlwings/pro/embedded_code.py", line 25, in <module>
    LicenseHandler.validate_license("pro")
  File "/Users/hayer/xlwings/xlwings/pro/utils.py", line 99, in validate_license
    os.getenv("XLWINGS_LICENSE_KEY_SECRET").encode(),
AttributeError: 'NoneType' object has no attribute 'encode'
```

Setting the License key is not the same as the secret I assume. Also setting the `xlwings license update -k YOUR_LICENSE_KEY` [docs](https://docs.xlwings.org/en/latest/pro/license_key.html#activate-a-developer-key) and yields a similar AttributeError. 

Does this have to do with having installed the editable install?

```

**Comment by fzumstein** [comment]
Then you'll probably not up to date with upstream/main.

**Comment by Jeroendevr** [comment]
Double checked that one 
I have the 
```Python
try:
    from .pro import _xlofficejs, _xlremote

    engines.add(Engine(impl=_xlremote.engine))
    engines.add(Engine(impl=_xlofficejs.engine))
    __pro__ = True
except (ImportError, LicenseError, **AttributeError**):
    __pro__ = False
``` 
AttributeError added.
