### ISSUE TITLE
Set xlwings License key is dev enviroment

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2241]
Regarding issue #2220 I still recieve the same result when I want to set the xlwings license. 

```shell
xlwings license update -k {LICENSE_KEY}
```

```Shell
Traceback (most recent call last):
  File "/Users/hayer/.virtualenvs/xlwings/bin/xlwings", line 5, in <module>
    from xlwings.cli import main
  File "/Users/hayer/xlwings/xlwings/__init__.py", line 39, in <module>
    from .main import (
  File "/Users/hayer/xlwings/xlwings/main.py", line 2926, in <module>
    from . import conversion, expansion
  File "/Users/hayer/xlwings/xlwings/conversion/__init__.py", line 18, in <module>
    from .standard import (
  File "/Users/hayer/xlwings/xlwings/conversion/standard.py", line 11, in <module>
    from ..pro import Markdown
  File "/Users/hayer/xlwings/xlwings/pro/__init__.py", line 14, in <module>
    from .embedded_code import dump_embedded_code, runpython_embedded_code
  File "/Users/hayer/xlwings/xlwings/pro/embedded_code.py", line 25, in <module>
    LicenseHandler.validate_license("pro")
  File "/Users/hayer/xlwings/xlwings/pro/utils.py", line 99, in validate_license
    os.getenv("XLWINGS_LICENSE_KEY_SECRET").encode(),
AttributeError: 'NoneType' object has no attribute 'encode'
```

However even when setting the `XLWINGS_LICENSE_KEY_SECRET` to something like "hello" also returns the same error.

**Comment by fzumstein** [comment]
Sorry, I had commented on #2220. This is now really fixed by https://github.com/xlwings/xlwings/commit/5aa76e8026572cdb001c56a9127ffa9c1fac3dfd
