### ISSUE TITLE
The query still on picture.update()

### ISSUE THREAD

**Issue by mqslllddyy** [xlwings/xlwings#2253]
Hi Felix,

this is still on picture.update(), and when i use this method to update with a new pic, then i want to get the property of the pic, i.e.: print(picture.width), but it returns error : 

(0, 'Microsoft Excel', '不能取得类 Picture 的 Width 属性', 'xlmain11.chm', 0, -2146827284), None)

Means it can't get the property Width of class Picture.

Can help on this? thx!

**Comment by mqslllddyy** [comment]
**_Added more code segment :_** 

Traceback (most recent call last):
  File "d:\python\xlwings\XLWINGS OBJECT MODEL\Picture\picture.py", line 36, in <module>
    print(picture.width)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\main.py", line 4190, in width
    return self.impl.width
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\_xlwindows.py", line 2211, in width
    return self.xl.Width
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\_xlwindows.py", line 199, in __getattr__
    v = getattr(self._inner, item)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\client\__init__.py", line 583, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'Microsoft Excel', '不能取得类 Picture 的 Width 属性', 'xlmain11.chm', 0, -2146827284), None)

**Comment by fzumstein** [comment]
You would need to provide a self-contained minimal code sample to reproduce.

**Comment by mqslllddyy** [comment]
Hi Felix,

Pls. find below code segment :

import xlwings as xw
from pathlib import Path

book = xw.Book("picture.xlsx") # use an empty excel file
sheet = book.sheets[0]
picture = sheet.pictures[0]
this_dir = Path(__file__).resolve().parent
picture.update(this_dir / "test.jpg")
print(picture.width)


Best Regards!

Meng, Qingsong(Rocky)

发件人: Felix Zumstein ***@***.***>
发送时间: 2023年5月7日 15:47
收件人: xlwings/xlwings ***@***.***>
抄送: mqslllddyy ***@***.***>; Author ***@***.***>
主题: Re: [xlwings/xlwings] The query still on picture.update() (Issue #2253)


You would need to provide a self-contained minimal code sample to reproduce.

**Comment by fzumstein** [comment]
You'll need to reassign the picture object like this:

```python
picture = picture.update(...)
```

**Comment by mqslllddyy** [comment]
Yes, you are right! Thx !

Best Regards!

Meng, Qingsong(Rocky)

发件人: Felix Zumstein ***@***.***>
发送时间: 2023年5月7日 22:39
收件人: xlwings/xlwings ***@***.***>
抄送: mqslllddyy ***@***.***>; Author ***@***.***>
主题: Re: [xlwings/xlwings] The query still on picture.update() (Issue #2253)


You'll need to reassign the picture object like this:

picture = picture.update(...)
