### ISSUE TITLE
on windows10 how to fix this error

### ISSUE THREAD

**Issue by wangyan-samuel** [xlwings/xlwings#2271]
windows  10   
Python 3.7.9 (tags/v3.7.9）

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
>>> import xlwings as xw
>>> xw.App(visible=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\20982\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\xlwings\main.py", line 310, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'

```

**Comment by fzumstein** [comment]
Please upgrade xlwings

**Comment by wangyan-samuel** [comment]
> Please upgrade xlwings
it's the latest 
xlwings==0.30.7

**Comment by fzumstein** [comment]
You're right, that case is still not fixed, so will try to fix this with a proper error msg with next release. In the meantime, you need to install the pywin32 dependency on Windows.

**Comment by wangyan-samuel** [comment]
i‘ve already installed pywin32==228 dependence on Windows 
but the error still existes

**Comment by fzumstein** [comment]
in this case, the installation is probalby broken.

Try to run these imports:

```
import pywintypes
import win32api
import win32con
```
