### ISSUE TITLE
pre-commit run --all-files: pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2273]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Monterey

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings - 0.30.8 from source
Python 3.9 and 3.11

I did a `pip install -e ".[all]"
seem my `pip list`

```Python
Package            Version  Editable project location
------------------ -------- -------------------------
appscript          1.2.2
black              23.3.0
blinker            1.6.2
certifi            2023.5.7
cfgv               3.3.1
charset-normalizer 3.1.0
click              8.1.3
contourpy          1.0.7
cycler             0.11.0
distlib            0.3.6
filelock           3.12.0
Flask              2.3.2
fonttools          4.39.4
identify           2.5.24
idna               3.4
iniconfig          2.0.0
isort              5.12.0
itsdangerous       2.1.2
Jinja2             3.1.2
kiwisolver         1.4.4
lxml               4.9.2
MarkupSafe         2.1.2
matplotlib         3.7.1
mypy-extensions    1.0.0
nodeenv            1.8.0
numpy              1.24.3
packaging          23.1
pandas             2.0.2
pathspec           0.11.1
pdfrw              0.4
Pillow             9.5.0
pip                23.1.2
platformdirs       3.5.1
plotly             5.14.1
pluggy             1.0.0
pre-commit         3.3.2
psutil             5.9.5
pyparsing          3.0.9
pytest             7.3.1
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.31.0
setuptools         67.7.2
six                1.16.0
tenacity           8.2.2
tzdata             2023.3
urllib3            2.0.2
virtualenv         20.23.0
Werkzeug           2.3.4
wheel              0.40.0
xlwings            0.0.0    /Users/hayer/xlwings
```

#### Describe your issue (incl. Traceback!)
Running `pre-commit` results in some error. It mentions Poetry, although that is not installed. I am not familiar with pre-commit but perhaps is is a issue related to pre-commit. 

```python
pre-commit run --all-files
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
### version information


pre-commit version: 3.3.2
git --version: git version 2.40.1
sys.version:
    3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /Users/hayer/.virtualenvs/xlwings_311/bin/python
os.name: posix
sys.platform: darwin


### error information

An unexpected error has occurred: CalledProcessError: command: ('/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/hayer/.cache/pre-commit/repojetja5sx
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/st/_0g2w6450zs5w9xts7h111f00000gn/T/pip-build-env-gq1yq4xp/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/st/_0g2w6450zs5w9xts7h111f00000gn/T/pip-build-env-gq1yq4xp/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

Traceback (most recent call last):
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/Users/hayer/.virtualenvs/xlwings_311/lib/python3.11/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/hayer/.cache/pre-commit/repojetja5sx
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/hayer/.cache/pre-commit/repojetja5sx/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/st/_0g2w6450zs5w9xts7h111f00000gn/T/pip-build-env-gq1yq4xp/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/st/_0g2w6450zs5w9xts7h111f00000gn/T/pip-build-env-gq1yq4xp/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by fzumstein** [comment]
Yes, that's a pre-commit issue so I am politely closing this issue. Here's CoPilot's 2ct on the error msg: 

```
It looks like there was an error while running pre-commit run --all-files. The error message indicates that there was an issue with the metadata preparation in the pyproject.toml file.

You can try running pre-commit autoupdate to update pre-commit and its hooks to the latest version. If that doesn't work, you can try removing the .venv directory and running pre-commit install to reinstall the virtual environment.

If the issue persists, you can try running pre-commit run --all-files --debug to get more detailed information about the error.
```
