### ISSUE TITLE
InvokeTypes(3174, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12,  17), (12, 17), (12, 17), (3, 49), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename pywintypes.com_error: 

### ISSUE THREAD

**Issue by Teddynh-ai** [xlwings/xlwings#2279]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings : 0.24.9
Office 365
Python 3.9 sur anaconda
#### Describe your issue (incl. Traceback!)
When saving the workbook, this error appears while for the other parts, everything works. In addition, on another computer, with exactly the same code, same file location, saving the workbook is done very well. My excel is updated, the file is not open elsewhere, the saved workbook does not does not have the same name as a workbook currently. I think it's a problem related to an xlwings directory or related to the WINDOWS operating system.
I have already deleted this directory as seen in other issues  "C:\Users\NHTRAK~1\AppData\Local\Temp\gen_py\3.9 but it doesn't work.
Do you have any ideas?

```python
# Your traceback here
"Traceback (most recent call last):
  File "c:\Users\nhtrakotoari\Desktop\Centrale\dist\Application_Centrale_v12\code version 12 (2).py", line 1150, in ESN_Template
    wb.save(os.path.join(os.environ["HOMEPATH"], "Desktop",self.filename_ESN))
  File "C:\Users\nhtrakotoari\Documents\Python Scripts\lib\site-packages\xlwings\main.py", line 874, in save
    self.impl.save(path)
  File "C:\Users\nhtrakotoari\Documents\Python Scripts\lib\site-packages\xlwings\_xlwindows.py", 
line 582, in save
    self.xl.SaveAs(os.path.realpath(path), FileFormat=file_format)
  File "C:\Users\nhtrakotoari\Documents\Python Scripts\lib\site-packages\xlwings\_xlwindows.py", 
line 70, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\NHTRAK~1\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py", line 46533, in SaveAs
    return self._oleobj_.InvokeTypes(3174, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12, 
17), (12, 17), (12, 17), (3, 49), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
pywintypes.com_error: (-2147352567, 'Une exception sÆest produite.', (0, 'Microsoft Excel', "Microsoft Excel ne peut accÚder au fichier ½\xa0C:\\Desktop\\5B133000\xa0╗. Plusieurs raisons sont possibles\xa0:\n\nò Le nom du fichier ou le chemin d'accÞs nÆexiste pas. \nò Ce fichier est actuellement utilisÚ par un autre programme.\nò Le classeur que vous essayez dÆenregistrer porte le mÛme nom quÆun classeur actuellement ouvert.", 'xlmain11.chm', 0, -2146827284), None)"
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
wb = xw.Book(os.path.join(basedir,"Template",'ESN_TEMPLATE.xlsx'))
 wb.save(os.path.join(os.environ["HOMEPATH"], "Desktop",self.filename_ESN))
```

**Comment by fzumstein** [comment]
The reason is given pretty much in clear text at the last line: ` "Microsoft Excel ne peut accÚder au fichier ½\xa0C:\\Desktop\\5B133000\xa0╗. Plusieurs raisons sont possibles\xa0:\n\nò Le nom du fichier ou le chemin d'accÞs nÆexiste pas. \nò Ce fichier est actuellement utilisÚ par un autre programme.\nò Le classeur que vous essayez dÆenregistrer porte le mÛme nom quÆun classeur actuellement ouvert."`
