### ISSUE TITLE
Modifying Cell which is not caller in UDF

### ISSUE THREAD

**Issue by philipdp123** [xlwings/xlwings#2292]
#### Versions of xlwings, Excel and Python (0.30.8, Office 365, Python 3.11.3)

Using the below UDF, I get an error when trying to edit a cell, which is not the caller.

#### Traceback
```python
Traceback (most recent call last):
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py", line 305, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py", line 310, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py", line 639, in _invokeex_
    return func(*args)
           ^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\server.py", line 235, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\udfs.py", line 538, in call_udf
    ret = func(*args)
          ^^^^^^^^^^^
  File "c:\users\Some User\desktop\xxxlwings\temp\temp.py", line 28, in hello
    caller.offset(1, 1).value = x
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\main.py", line 2411, in value
    conversion.write(data, self, self._options)
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\conversion\__init__.py", line 102, in write
    pipeline(ctx)
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\conversion\framework.py", line 79, in __call__
    stage(*args, **kwargs)
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\conversion\standard.py", line 75, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\conversion\standard.py", line 63, in _write_value
    rng.raw_value = value
    ^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\main.py", line 1973, in raw_value
    self.impl.raw_value = data
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\_xlwindows.py", line 1209, in raw_value
    self.xl.Value = data
    ^^^^^^^^^^^^^
  File "C:\Users\Some User\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\client\__init__.py", line 597, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

```
#### Code snippet

```python
@xw.func
def hello(x, caller):
    # caller is an xlwings range object
      caller.offset(1, 1).value = x

    return f"Hello {x}!"

```

**Comment by fzumstein** [comment]
UDFs don't allow you to write outside the caller cells, see: https://github.com/xlwings/xlwings/issues/1786
