### ISSUE TITLE
api.Comment not working on Mac?

### ISSUE THREAD

**Issue by Rapid1898-code** [xlwings/xlwings#2295]
#### Versions of xlwings 0.30.10, Python 3.9.0

Hello - i have a working solution on windows with the following code:

```
import xlwings as xw
wb = xw.Book("test.xlsx")
ws = wb.sheets[0]

wText2 = "i was able to add a comment to an excel-cell using the following code:\n Is it possible to autofit the size of the comment-box somehow in excel?"

try:
  ws.range("A1").api.Comment.Delete()
except:
  pass
ws.range("A1").api.AddComment(Text=wText2)
ws.range("A1").api.Comment.Shape.DrawingObject.AutoSize = True
```

This works fine - but when i try to run this code on Mac i get this error-message:

```
Traceback (most recent call last):
  File "/Users/polzimac/Documents/DEV/Python-Diverses/Xlwings/exmplComment.py", line 12, in <module>
    ws.range("A1").api.AddComment(Text=wText2)
  File "/Users/polzimac/Documents/DEV/venv/xlwings/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 598, in __getattr__
    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'AddComment'
(xlwings) PolziMacs-Mini:xlwings polzimac$ 
(xlwings) PolziMacs-Mini:xlwings polzimac$ 
```

Is it also possible to run this process on Mac?

**Comment by fzumstein** [comment]
Using `.api` means you have to write platform-dependent code. On macOS, this uses appscript instead of pywin32. There's rudimentary support for Notes (previously called Comments) here: https://docs.xlwings.org/en/latest/api/note.html

You can get some inspiration about the macOS object model by checking its current implementation: https://github.com/xlwings/xlwings/blob/main/xlwings/_xlmac.py#L1487

**Comment by fzumstein** [comment]
```
ws["A7"].api.add_comment(comment_text='a comment')
```

**Comment by Rapid1898-code** [comment]
Hello - thanks  lot again - this seems to work now in Mac -
Is it also possible to delete the comment in a cell on Mac?

Like i do it with this command on Windows:
`ws.range(wCell).api.Comment.Delete() `

**Comment by fzumstein** [comment]
that's already implemented: https://docs.xlwings.org/en/latest/api/note.html#xlwings.main.Note.delete

**Comment by Rapid1898-code** [comment]
thx again - probably one final question -
I realized that the comment-assigment works fine with this code when the cell is empty
```
ws[wCell].api.AddComment(Text = colText)  # for Windows
ws[wCell].note.text = colText   # for Mac
```

But when there is allready a comment in the cell and i do before the new writing as above a 
`ws[wCell].note.delete()`
the text i not written using the write-statements from above
(the comment is empty and only the user can be seen at the top of the comment-window when hovering)

Why is that?
(i would like to delete probably existing comments and then write the new comment to the cell)

**Comment by fzumstein** [comment]
here I have to pass, dunno 🤷‍♂️
