### ISSUE TITLE
Problem with COMObject when dealing with FileDialog

### ISSUE THREAD

**Issue by huche6** [xlwings/xlwings#2296]
#### I made a custom button in a ribbon to export a specific file containing values within a spreadsheet. When clicking this button, a FileDialogSaveAs is opened. I would like to add specific filters in this FileDialog which can be easily done in VBA. However when calling the method FileDialog.Filters.Clear() in python I get the error:

```
File "<COMObject <unknown>>", line 2, in Add
 pywintypes.com_error: (-2147352567, 'Une exception s’est produite.', (0, None, None, None, 0, -2147352573), None) 
```
I have a similar error with Filters.Add and I didn't find a workaround.

```python

pythoncom error: Python error invoking COM method.
Traceback (most recent call last): 
File "C:\Users\AppData\Roaming\Python\Python311\site-packages\win32com\server\policy.py", line 303, in _Invoke_ 
return self._invoke_(dispid, lcid, wFlags, args)                                                                               
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
File "C:\Users\AppData\Roaming\Python\Python311\site-packages\win32com\server\policy.py", line 308, in _invoke_   
 return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)                                                                 
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
File "C:\Users\Hugo-TwiinIt\AppData\Roaming\Python\Python311\site-packages\win32com\server\policy.py", line 637, in _invokeex_ 
return func(*args)
       ^^^^^^^^^^^                                                                                              
File "C:\Users\micromamba\envs\generic_excel\Lib\site-packages\xlwings\server.py", line 235, in CallUDF      
res = call_udf(script, fname, args, this_workbook, FromVariant(caller))                                                       
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           
File "C:\Users\Hugo-TwiinIt\micromamba\envs\generic_excel\Lib\site-packages\xlwings\udfs.py", line 538, in call_udf       
ret = func(*args)                                                                                                             
      ^^^^^^^^^^^                                                                                       
File "c:\users\hugo-twiinit\documents\codes\generic\generic\generic.py", line 172, in demo_run                           
_demo_run()
File "c:\users\hugo-twiinit\documents\codes\generic\generic\generic.py", line 98, in _demo_run
dialog.Filters.Clear()                                                                                         
File "<COMObject <unknown>>", line 2, in Clear                                                                        
pywintypes.com_error: (-2147352567, 'Une exception s’est produite.', (0, None, None, None, 0, -2147352573), None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
def _demo_run():
    app = xw.apps.active
    dialog = app.api.FileDialog(2)
    dialog.Filters.Clear()

```
thanks in advance

**Comment by huche6** [comment]
It seems that it does not work with FileDialogSaveAs

**Comment by michaeldengxyz** [comment]
FYI only ----------------

                ####----- Error when run from Tk UI -----####
                #File "C:\Users\dengm\OneDrive\Program\Work\JDOC-CSV\Excel2PDF_win32com.py", line 57, in <module>
                #wb.ActiveSheet.ExportAsFixedFormat(0, pdf_filename)
                #File "<COMObject <unknown>>", line 4, in ExportAsFixedFormat
                #pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'Document not saved. The document may be open, or an error may have been encountered when saving.', 'xlmain11.chm', 0, -2146827284), None)
                

                #when hard-coded the input <filename> as the following, it works!!!
                #filename = r"C:\Users\dengm\Downloads\New folder\02_Workflow-Doc Creation Notification_Unexecuted.xlsx"

                #this is a file path issue for wb.ActiveSheet.ExportAsFixedFormat!!
                #--- just give the file name for <pdf_filename> without directory path, it works to convert to pdf, save to the default folder "Documents" of the user: os.path.expandvars("%userprofile%\\Documents")
                ####----- Error when run from Tk UI -----####
