### ISSUE TITLE
names.add result in a COM error on Windows 10 + Office 365.

### ISSUE THREAD

**Issue by hirolau** [xlwings/xlwings#2298]
#### OS 

Windows 10 Enterprise

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
XLWings version: 0.30.10
Office: Office 365 Version 2208 (Build 15601.20680)

I do not have access to other OSes or versions of Excel and have not been able to test
if this error happens for other setups.

#### Describe your issue (incl. Traceback!)

Adding a name does not seem to work and result in an COM Error.

The following code works as expected and defines a name in the Excel Workbook:

```python
import win32com.client as win32
excel = win32.gencache.EnsureDispatch('Excel.Application')
wb = excel.Workbooks.Open(r"TestAPI.xlsm")
excel.Visible = True
wb.Names.Add(Name='my_custom_name', RefersTo='MyCustomValue')

```

But doing the same using the `names.add` result in an error:

```python
xlwings server running, clsid={1DC04920-D6B3-47F7-ACDC-0C03845E1FCA}, event loop on 22232
Workbook: <Book [TestAPI.xlsm]>
Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
XLWings version: 0.30.10


<Name 'my_defined_name1': ="my_defined_vale1">
<Name 'my_defined_name2': ="my_defined_vale3">

pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Temp\xlwings_venv\Lib\site-packages\win32com\server\policy.py", line 305, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\xlwings_venv\Lib\site-packages\win32com\server\policy.py", line 310, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\xlwings_venv\Lib\site-packages\win32com\server\policy.py", line 639, in _invokeex_
    return func(*args)
           ^^^^^^^^^^^
  File "C:\Temp\xlwings_venv\Lib\site-packages\xlwings\server.py", line 235, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\xlwings_venv\Lib\site-packages\xlwings\udfs.py", line 538, in call_udf
    ret = func(*args)
          ^^^^^^^^^^^
  File "c:\users\n475330\desktop\xlwings\ace.py", line 18, in add_name
    wb.names.add("named_constant", '="constant"')
  File "C:\Temp\xlwings_venv\Lib\site-packages\xlwings\main.py", line 4545, in add
    return Name(impl=self.impl.add(name, refers_to))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\xlwings_venv\Lib\site-packages\xlwings\_xlwindows.py", line 2302, in add
    return Name(xl=self.xl.Add(name, refers_to))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUserName\AppData\Local\Temp\gen_py\3.11\00020813-0000-0000-C000-000000000046x0x1x9.py", line 28869, in Add
    ret = self._oleobj_.InvokeTypes(181, LCID, 1, (9, 0), ((12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Name
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python

import xlwings as xw
import sys


@xw.func
def add_name():

    wb = xw.Book.caller()

    print(f"Workbook: {wb}")
    print(f"Python version: {sys.version}")
    print(f"XLWings version: {xw.__version__}")

    for name in wb.names:
        print(name)

    wb.names.add("named_constant", "constant") # This line fails when calling the add_name UDF.

    print('Got here!, Function call almost done!')

    return 'Done'

```

**Comment by fzumstein** [comment]
UDFs don't allow you to write outside the caller cells or do anything else, see: https://github.com/xlwings/xlwings/issues/1786
