### ISSUE TITLE
Cannot get quickstart project to work.

### ISSUE THREAD

**Issue by hlanier** [xlwings/xlwings#2318]
I am sorry to bother you with what will probably be a very easy setup problem, but I am stuck on the simple task of running the quickstart demo.   I have read the documentation, watched several videos (that appear to be somewhat outdated) and have exhausted chat gpt to the point that it is going around in circles with no helpful answers.

Windows 10 Pro (64 bit)
Microsoft 365 Apps for business
Anaconda3-2023.07-2 installs Python 3.11.4 and xlwings 0.29.1
(Note:  I have completely uninstalled and reinstalled being careful to remove all references to anaconda and xlwings before reinstalling.  I have also tried doing the suggested
 conda upgrade -c conda-forge xlwings
But it completely corrupts the Anaconda setup which required an additional reinstall.)

The xlwings64-0.29.1.dll is located in C:\Users\Harold\anaconda3/
Trust Center | Macro Settings | Trust access to the VBA project object model is checked.
Xlwings.xlam is located in C:\Users\Harold\AppData\Roaming\Microsoft\Excel\XLSTART and has been added to the Excel Active Application Add-ins.
Tools | References | xlwings at same location has been checked.

Xlwings tab is visible in Excel and shows 0.29.1 version under Advanced.
Conda Path:  C:\Users\Harold\anaconda3
Conda Env:  base
All other settings are blank…

Path in User variables for Harold includes:
C:\Users\Harold\anaconda3
C:\Users\Harold\anaconda3\Library\mingw-w64\bin
C:\Users\Harold\anaconda3\Library\usr\bin
C:\Users\Harold\anaconda3\Library\bin
C:\Users\Harold\anaconda3\Scripts

Used xlwings quickstart to set up a folder myproject  in folder C:\Test, which installed two files myproject.xlsm and myproject.py.
Running myproject.py changes cell A1 in Sheet1 from Hello xlwings to Bye xlwings as expected which suggest that I am somewhat connected.

NOW FOR THE PROBLEMS:

=hello("Harold") in a blank cell gives #NAME?
hello() is not listed as an available function under fx…

Thinking that I should first import functions to use them I have clicked on fx Import Functions button in xlwings tab but get this Error:

ModuleNotFoundError: No module named 'myproject'
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Harold\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    module = import_module(module_name)
  File "C:\Users\Harold\anaconda3\Lib\site-packages\xlwings\udfs.py", line 416, in get_udf_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    module = get_udf_module(module_name, xl_workbook)
  File "C:\Users\Harold\anaconda3\Lib\site-packages\xlwings\udfs.py", line 739, in import_udfs
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\Users\Harold\anaconda3\Lib\site-packages\xlwings\server.py", line 231, in Call
           ^^^^^^^^^^^
    return func(*args)
  File "C:\Users\Harold\anaconda3\Lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\Harold\anaconda3\Lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\Harold\anaconda3\Lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_ -2147467259

===========================================================================
The two listed macros SampleCall() and SampleRemoteCall() give errors

Sub SampleCall()
    mymodule = Left(ThisWorkbook.Name, (InStrRev(ThisWorkbook.Name, ".", -1, vbTextCompare) - 1))
    RunPython "import " & mymodule & ";" & mymodule & ".main()"
End Sub

Gives error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'myproject'

Sub SampleRemoteCall()
    RunRemotePython "http://127.0.0.1:8000/hello", apiKey:="DEVELOPMENT"
End Sub

Gives error:
Request Timeout: A connection with the server could not be established. (408)

======================================================================
I am very excited about using xlwings, as it appears to be able to do exactly what I want, but I need help getting past step one.

**Comment by hlanier** [comment]
Since writing my request for help, I have partially solved my problem, but the solution does not make sense.

Within the xlwings Tab, if I check ‘add workbook to PYTHONPATH’, I can then press Import Functions and the user defined function hello() will work and the Sub SampleCall() will work.  But this does not make sense as the two files are in the same folder which is supposed to not require any help locating the path.  Is it possible that the check mark is working backwards?

This does not solve the SampleRemoteCall() issue which still gives the error (408) message.

**Comment by fzumstein** [comment]
* `Add workbook to PYTHONPATH` is indeed required for quickstart projects and is therefore automatically activated when installing the add-in for the first time via `xlwings addin install`.

* `SampleRemoteCall` is a function from xlwings PRO and requires you to follow these docs/tutorial: https://docs.xlwings.org/en/latest/pro/server/server.html
