### ISSUE TITLE
number_format is not implemented in the app

### ISSUE THREAD

**Issue by OlegBEZb** [xlwings/xlwings#2324]
Good evening!

I faced a problem that the same code (I hope it's really the same :)) works differently in the notebook and in the running flask server. Two small code snippets are given below.

Thank you very much for considering this!

#### OS 
macOS Ventura 13.2.1 (22D68)

#### Versions of xlwings, Excel and Python
Python 3.10.12
Excel 16.76
xlwings both 0.30.7 and 0.30.11
#### Describe your issue (incl. Traceback!)

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/.conda/lib/python3.10/site-packages/xlwings/main.py", line 2193, in number_format
    return self.impl.number_format
  File "/path/.conda/lib/python3.10/site-packages/xlwings/pro/_xlremote.py", line 706, in number_format
    raise NotImplementedError()
NotImplementedError

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Jupyter notebook code
wb = xw.Book(os.path.join(format_examples_folder, "Excel.xlsx")) 
range = wb.selection.sheet["A1"]
range.number_format

# server_flask.py
@app.route("/hello", methods=["POST"])
def hello():
    with xw.Book(json=request.json, read_only=False, mode='i') as wb:
        range = wb.selection.sheet["A1"]
        # this line causes the traceback presented above
        range.number_format
```

**Comment by fzumstein** [comment]
The server API is currently work-in-progress, so this isn't available yet (it is being completed according to the needs of paying clients). Depending on what you wanna do with it, you may be able to work around it by using a macro: https://docs.xlwings.org/en/latest/pro/server/server.html#workaround-for-missing-features

**Comment by OlegBEZb** [comment]
> The server API is currently work-in-progress, so this isn't available yet (it is being completed according to the needs of paying clients). Depending on what you wanna do with it, you may be able to work around it by using a macro: https://docs.xlwings.org/en/latest/pro/server/server.html#workaround-for-missing-features

Dear Felix, thank you very much for the answer!

**Comment by OlegBEZb** [comment]
@fzumstein , I've tried to follow your recommendations together with the documentation but still struggle to launch macros. I've tried an Office Script approach from the [server](https://docs.xlwings.org/en/latest/pro/server/server.html#workaround-for-missing-features) example as well as the one for [add-in](https://docs.xlwings.org/en/latest/pro/server/officejs_addins.html#workaround-for-missing-features). For the first one, I've created the function manually in an opened Excell app. For the second one, I've added the code to the taskpane script. Could you, please, elaborate on this? I am using the PRO trial and want to try an Add-In with a backend running on my personal laptop.

Thank you for your support!

**Comment by fzumstein** [comment]
you would need to paste your code

**Comment by OlegBEZb** [comment]
@fzumstein , thank you for the reply! 

`taskpane.html`
```
<script>
  // ... Rest of the script ...

async function wrapText(context, sheetName, cellAddress) {
      // The first parameter has to be the request context, the others
      // are those parameters that you will provide via Python
      const range = context.workbook.worksheets
        .getItem(sheetName)
        .getRange(cellAddress);
      range.format.wrapText = true;
      await context.sync();
    }
xlwings.registerCallback(wrapText);

  // ... Rest of the script ...
</script>
```

I just use unchanged Ribbon Hello World button without any changes
`server_flask.py`
```python
@app.route("/hello", methods=["POST"])
def hello():
    with xw.Book(json=request.json) as book:
        wrap_text = book.app.macro("wrapText")
        wrap_text("Unformatted example", "A1")
```

I don't get any output but nothing changes in the Excel app

**Comment by fzumstein** [comment]
does A1 on the Unformatted excample sheet contain a long string that would be wrapped?

**Comment by OlegBEZb** [comment]
> does A1 on the Unformatted example sheet contain a long string that would be wrapped?

Yes. It has a string which is longer than the horizontal border. Apart from that, as I understand even without that "Wrap Text" button in Excel will be visibly pressed. 

I have tried to launch the func from the ipynb and it worked a couple of times. But I can't reproduce this in a stable way.

```python
wb = xw.Book("sample.xlsx")
wrap_text = wb.app.macro("wrapText")
wrap_text("Unformatted example", "A1")
```

**Comment by fzumstein** [comment]
> "Wrap Text" button in Excel will be visibly pressed.
nope, no invisible button pressing happening anywhere in xlwings.

make sure to reload the taksk pane and check its source (right-click on task pane and View Source) to make sure the update has been properly loaded.

**Comment by OlegBEZb** [comment]
Dear @fzumstein, sorry for being unclear. By the button pressed I meant Excel's native "Wrap Text" regime on the Home tab (image below). It becomes dark when wrapping is applied (regardless programmatically or manually). So I was checking the macro both visually (text is really wrapped) and by looking at the Excel's field.
![image](https://github.com/xlwings/xlwings/assets/28011503/92b12c71-ff9f-4736-aab6-7ec78b775368)

I am not using task pane, my flow is the following: 
1. One "Hello World" button in the `manifest.xml`. There is no "Show taskpane" button as I want to use only ribbon
```
<bt:String id="MyFunctionButton.Label" DefaultValue="Hello World" />
```
with action
```
<Action xsi:type="ExecuteFunction">
  <FunctionName>hello-ribbon</FunctionName>
</Action>
```
2. Button UI in the `taskpane.html`
```
// Sample 2: Button on Ribbon
// Needs event.completed() and Office.actions.associate
// "hello-ribbon" is the identifier in manifest.xml
function helloRibbon(event) {
  xlwings.runPython(window.location.origin + "/hello");
  event.completed();
}
Office.actions.associate("hello-ribbon", helloRibbon);
```
3. Macro script in the `taskpane.html`
```
<script>
  // ... Rest of the script ...

async function wrapText(context, sheetName, cellAddress) {
// The first parameter has to be the request context, the others
// are those parameters that you will provide via Python
const range = context.workbook.worksheets
  .getItem(sheetName)
  .getRange(cellAddress);
range.format.wrapText = true;
await context.sync();
}
xlwings.registerCallback(wrapText);

  // ... Rest of the script ...
</script>
```
4. In `server_flask.py` I am trying to use the macro function
```python
@app.route("/hello", methods=["POST"])
def hello():
    with xw.Book(json=request.json) as book:
        wrap_text = book.app.macro("wrapText")
        wrap_text("Unformatted example", "A1")
```

So it is kind of an Excel->Python->Excel flow. As I understood from the documentation, this should work without any problems but right now for me only Excel->Python part works. So that's why I can't directly reload the task pane but I've conducted my experiments via relaunching Excel completely together with reloading the server and the add-in.

**Comment by fzumstein** [comment]
I can't see anything wrong from here. However, at least for development purposes, I'd recommend you to activate the task pane as this allows you to actively reload the client code and you'll be able to put `console.log()` statements for debugging and you can also look at the source code, just to be sure that you are really using the code you want to.

**Comment by OlegBEZb** [comment]
> I can't see anything wrong from here. However, at least for development purposes, I'd recommend you to activate the task pane as this allows you to actively reload the client code and you'll be able to put `console.log()` statements for debugging and you can also look at the source code, just to be sure that you are really using the code you want to.

Dear @fzumstein , thank you for the idea. Let me try. If it doesn't solve the issue, I'll add more details to the issue

**Comment by OlegBEZb** [comment]
@fzumstein , I've localized the issue thanks to your suggestions to use the taskpane.

The functions from your examples (`wrapText` and `colourSelected`) work perfectly as extected. But for some reason I can't find a way to retrieve the values from JS func back to Python.

Below is the function I use to replace the non-implemented `.number_format ` field
```js
// Function to extract the number format from a specific cell
async function getNumberFormatFromCell(context, sheetName, cellAddress) {
  try {
    const range = context.workbook.worksheets.getItem(sheetName).getRange(cellAddress);
    range.load("numberFormat");
    await context.sync();

    console.log("Number format of the cell " + cellAddress + ":", range.numberFormat[0][0]);
    return range.numberFormat[0][0];
  } catch (error) {
    console.error("Error:", error);
  }
}
```
The func from above is defined and registered in the `taskpane.html`
```js
xlwings.registerCallback(getNumberFormatFromCell);
```

And this is the Python code from `server_flask.py` where I try to check the function (when default 'Run hello' is pressed on the taskpane)
```python
@app.route("/hello", methods=["POST"])
def hello():
    with xw.Book(json=request.json) as book:
        getNumberFormatFromCell = book.app.macro("getNumberFormatFromCell")
        res = getNumberFormatFromCell("Unformatted example", "D9")
        print('getNumberFormatFromCell', res)
```

In the console log I clearly see that the JS function sees the format well: 
`Number format of the cell D9:"General"`
But Python gets `None` value regarless of different types of cells I tried.

In the documentation I didn't find any examples with a value retrieved from the macro. Could you, please, share the approach for it if it's possible?

**Comment by fzumstein** [comment]
Right, no, that isn't possible at the moment. You can only trigger a macro that runs client-side, i.e. in Excel, but you can't get results back to Python. So whatever it is that you want to do with number_format, you'd have to do it all in JS.

Being able to supply additional properties (such as number_format) to the Python backend is on todo my list, but I can't give you an ETA.

**Comment by OlegBEZb** [comment]
@fzumstein , thank you for the answer! Could you describe what this "end-to-end" functionality in JS looks like? Or maybe share any ideas for a workaround? I was thinking about the dirty but working idea of using some cell for writing the results and reading them further. Apart from that, how difficult is it for an external user like me to contribute this feature (returning results from the macro) to the library? I tried to study the source code of the library - looks great but definitely not simple.

**Comment by fzumstein** [comment]
Let me first understand what you are trying to achieve?

**Comment by OlegBEZb** [comment]
In my exercise, I am scanning all cells of a sheet and for further processing, I want to understand what kind of values are stored there. For example, for textual values I have one kind of processing, for dates the other and so on. Excel's native format types (General, Number, etc) are quite useful here as together with the value they help identify the final type of the cell. I plan to further add some formatting (colours, fonts) and values to the sheet and therefore I use xlwings rather than pandas or so. 

Not the topic but has the similar problem with formulas. They are also not available for server. I planned some special kind of analysis of them (not value field, but formula).

**Comment by fzumstein** [comment]
In summary you can say that xlwings Server is still work-in-progress and advanced use cases such as yours aren't covered yet.

However, you might be ale to get the type on the Python side, i.e. loop through the values and do a `isinstance(value, str)` on them. Not super efficient, but may work.

**Comment by OlegBEZb** [comment]
Is there any specific reason why, for example, an "offline" call to the app is so different and requires a separate implementation in comparison to the server? As a person familiar only with a Python side of a question, wasn't able to udnerstand this from the documentation or the code.

To the best of my experience with the library, the value itself has very limited information regarding the Excel cell. For example, Excel's "Currency" is detected as int, "Percentage" also as int, "Date" as a string.

**Comment by fzumstein** [comment]
The classic version has access to Excel at runtime and can pull out the information from the cells when they are required. xlwings Server is on a different machine with no Excel running, so all information has to be serialized ahead of time and sent over. For now, it only sends over what's usually required for the normal use case of xlwings.

**Comment by fzumstein** [comment]
This is now available in xlwings Lite as an async get function: https://docs.xlwings.org/en/latest/api/range.html#xlwings.Range.get_number_format

xlwings Server is now only lacking support for the Async API, once it does, it will automatically be supported. This is now tracked under https://github.com/xlwings/xlwings-server/issues/416
