### ISSUE TITLE
xlwings vba UnicodeDecodeError stops import or edit from running.

### ISSUE THREAD

**Issue by nmadura** [xlwings/xlwings#2335]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version: 0.30.12
Microsoft® Excel® for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20226) 64-bit 
Python 3.11.5
#### Describe your issue (incl. Traceback!)
when encountering an invalid unicode sequence xlwings errors out. This functionality may be OK, however it provides little detail to proceed with.

```python
# Your traceback here
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Scripts\xlwings.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 1358, in main
    args.func(args)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 849, in vba_imp
    vba_code = f.readlines()
               ^^^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 930: illegal multibyte sequence
```

I was able to trace down the offending area by wrapping the f.readlines() call in a try block
this is replacing line 849 in cli.py

```python
        elif path.suffix in (".cls", ".frm"):
            with open(path, "r") as f:
                try: 
                    vba_code = f.readlines()
                except UnicodeDecodeError as ude:
                    if ude.end > 50:
                        offending = ude.object[ude.end - 50:ude.end]
                    else:
                        offending = ude.object[ude.start:ude.end]
                    print("UnicodeDecodeError reading <{}>, \nexception: {} \ncontext: {}".format(path, ude, offending))
                    raise ude
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Can you provide the source or the offending character?
You could also try to do `with open(path, "r", encoding="utf-8") as f:` in your code extract above to see if that solves it.

**Comment by nmadura** [comment]
Someone had copy/pasted the UTF-8 [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) U+FEFF into the vba code to match with a regular expression 
Once I was able to ascertain where the process was terminating I was able to eliminate the offending mark so as to no longer trip up xlwings.
What is interesting is that the vba export process does not seem to be tripped up by the offending character

**Comment by nmadura** [comment]
I was able to create a quick test case.
steps to reproduce
1. place xlwings_test.xlsm into an empty folder
2. open the folder in VS Code
3. open a Terminal (Terminal > New Terminal)
4. type `xlwings vba edit --file .\xlwings_testcase.xlsm` (this should download Module1.bas with no issue)
5. open Module1.bas
6. edit Module1.bas and save the file

output:
```python
Watching for changes in xlwings_testcase.xlsm (silent mode)...(Hit Ctrl-C to stop)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\264872\AppData\Local\Programs\Python\Python311\Scripts\xlwings.exe\__main__.py", line 7, in <module>
  File "C:\Users\264872\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 1365, in main
 can't decode byte 0xef in position 90: illegal multibyte sequence
```

[xlwings_testcase.xlsx](https://github.com/xlwings/xlwings/files/12690816/xlwings_testcase.xlsx)
Please rename to .xlsm, I couldn't upload a .xlsm

**Comment by fzumstein** [comment]
This actually doens't reproduce it on my machine. I believe this also depends on the locale of the machine. Are you running this from the Python package or the xlwings.exe? If the former, can you try to change this line: https://github.com/xlwings/xlwings/blob/main/xlwings/cli.py#L849

into

```python
import locale
vba_code = f.readlines(encoding=locale.getpreferredencoding())
```

and check if you still get the error?

**Comment by nmadura** [comment]
I am running through a VS Code Terminal (which I believe uses powershell)
and invoking the xwings.exe from power shell
(I installed xwings using `pip install xwings`)

I modified the line per the above request and received 
```Python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\264872\AppData\Local\Programs\Python\Python311\Scripts\xlwings.exe\__main__.py", line 7, in <module>
  File "C:\Users\264872\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 1367, in main
    args.func(args)
  File "C:\Users\264872\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 851, in vba_import
    vba_code = f.readlines(encoding=locale.getpreferredencoding())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _IOBase.readlines() takes no keyword arguments```

**Comment by fzumstein** [comment]
Oops sorry, that should go a line above as argument in open()

**Comment by nmadura** [comment]
I also want to note this error occurs in both `xlwings vba import` and `xlwings vba edit` (upon save)
the locations are: 
https://github.com/xlwings/xlwings/blob/2b307190fd8506963ed2c7b94480ee59364b26df/xlwings/cli.py#L849
https://github.com/xlwings/xlwings/blob/2b307190fd8506963ed2c7b94480ee59364b26df/xlwings/cli.py#L906

Seeing the remark about locale reminded me, I do working with a lot of Japanese built macros and have changed my "non unicode" system locale to Japanese
![japanese system locale](https://github.com/xlwings/xlwings/assets/1625899/d32444d8-ba08-47f0-9a10-f9f3ebd5d1bf)

**Comment by nmadura** [comment]
updated code to... 
```Python
            with open(path, "r", encoding=locale.getpreferredencoding()) as f:
                vba_code = f.readlines()
```

Still with this result
```Python
PS C:\Users\xxxx\OneDrive - xxxx\Documents\source\xlwings_test> xlwings vba import --file .\xlwings_testcase.xlsm
xlwings version: 0.30.12

This will affect the following workbook/folder:

* xlwings_testcase.xlsm
* C:\Users\xxxx\OneDrive - xxxx\Documents\source\xlwings_test

Proceed? [Y/n] y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Scripts\xlwings.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 1367, in main
    args.func(args)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\cli.py", line 851, in vba_import
    vba_code = f.readlines()
               ^^^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 402: illegal multibyte sequence```

**Comment by fzumstein** [comment]
Ok I am starting to understand, try this instead:

```python
            with open(path, "r", encoding="utf-8") as f:
                vba_code = f.readlines()
```

**Comment by nmadura** [comment]
I apologize for the delay, I got busy with my real work...

yes, setting `encoding="utf-8"` corrects the problem for me.

if you submit a fix, please do so against both locations in cli.py (for `vba edit` and `vba import`)

Thanks for your help!

**Comment by fzumstein** [comment]
Cool, thanks for confirming. yes I'll fix this so have re-opened the issue for now.

**Comment by fzumstein** [comment]
@DoanGoodman that's a different issue, please open a separate issue if you're still seeing this.

**Comment by angel-fear** [comment]
Hi!
I also have the same problem when try to open xlsm file in VSCode session using xlwings vba edit command:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python\Scripts\xlwings.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python\Lib\site-packages\xlwings\cli.py", line 1299, in main
    args.func(args)
  File "C:\Program Files\Python\Lib\site-packages\xlwings\cli.py", line 854, in vba_edit
    path_to_type = export_vba_modules(book, overwrite=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Lib\site-packages\xlwings\cli.py", line 761, in export_vba_modules
    exported_code = f.readlines()
                    ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 76: invalid continuation byte
```

[Here](https://drive.google.com/file/d/1mT-YI63GLpZn9uSkzgf0_nouxQWZRa3s/view?usp=sharing) is the problem file.
Thanks for your help!
