### ISSUE TITLE
Pywintypes.com_error?

### ISSUE THREAD

**Issue by Rapid1898-code** [xlwings/xlwings#2350]
Out of a sudden i can´t use xlwings anymore on one of my computers - 

A simply:

```
import xlwings as xw
xw.App()
```

throws this error:

```
$ python test2.py
Traceback (most recent call last):
  File "G:\DEV\Python-Diverses\Xlwings\test2.py", line 2, in <module>
    xw.App()
  File "G:\DEV\.venv\xlwings\lib\site-packages\xlwings\main.py", line 310, in __init__
    self.impl = engines.active.apps.add(
  File "G:\DEV\.venv\xlwings\lib\site-packages\xlwings\main.py", line 210, in add
    return App(impl=self.impl.add(**kwargs))
  File "G:\DEV\.venv\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 510, in add
    return App(spec=spec, add_book=add_book, xl=xl, visible=visible)
  File "G:\DEV\.venv\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 563, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx("Excel.Application"))
  File "G:\DEV\.venv\xlwings\lib\site-packages\win32com\client\__init__.py", line 145, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
(xlwings) 
```

It seems this has something to do with the excel-version which is installed on my computer.
(tested this on another computer and it still worked fine)

Any suggestion how i can fix this?
Is it necessary to re-install the Office-Package on the problematic computer or is there anything else i can do?

**Comment by fzumstein** [comment]
Yes, this seems related to the Excel installation. Maybe try to repair?

**Comment by Rapid1898-code** [comment]
Yes thx - i tried to reapair the installation (full online repair - not the fast one)
And now it works again.
