### ISSUE TITLE
xlwings.App() throws up an error

### ISSUE THREAD

**Issue by ChristianC7** [xlwings/xlwings#2351]
Recently I got a new laptop and installed python 3.12 (64-bit) and when I try to do the following:  xw.App() it throws an error:  

Traceback (most recent call last):

import xlwings as xw

>xw.App()4
###
File "<console>", line 1, in <module>

File "c:\users\cchanco\appdata\local\programs\python\python312\Lib\site-packages\xlwings\main.py", line 310, in __init__

self.impl = engines.active.apps.add(

AttributeError: 'NoneType' object has no attribute 'apps'

## Thanks in advance for checking into this!

**Comment by ChristianC7** [comment]
After I downloaded some other related libraries and re-started my work laptop, the issue was resolved.
