### ISSUE TITLE
mac onedrive business 

### ISSUE THREAD

**Issue by kuaijishi** [xlwings/xlwings#2386]
macOS Sierra,Office 365,xlwings version: 0.29.1
My business edition OneDrive address is“/Users/luobo/Library/CloudStorage/OneDrive-致同会计师事务所（特殊普通合伙）”，我在【xlwings.conf】set"ONEDRIVE_COMMERCIAL_MAC","$HOME/Library/CloudStorage/OneDrive-致同会计师事务所（特殊普通合伙）"
,Still encountering errors。

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/luobo/miniconda3/lib/python3.11/site-packages/xlwings/utils.py", line 406, in prepare_sys_path
fullname_url_to_local_path(
File "/Users/luobo/miniconda3/lib/python3.11/site-packages/xlwings/utils.py", line 545, in fullname_url_to_local_path
raise xlwings.XlwingsError(
xlwings.XlwingsError: Couldn't find your local OneDrive for Business file, see: xlwings.org/error。
thanks。

**Comment by fzumstein** [comment]
OneDrive for Business on macOS requires a setting, see: 
https://docs.xlwings.org/en/latest/onedrive_sharepoint.html#onedrive-for-business

**Comment by kuaijishi** [comment]
I apologize for disturbing you again.

I am using the local path on my computer, which is“/Users/luobo/Library/CloudStorage/OneDrive-会计师事务所（特殊普通合伙）/1-永丰科技/004-报表与附注/0-内部往来核对.xlsx”，I have set it to：   "INTERPRETER_MAC","/Users/luobo/miniconda3/bin/python" "ONEDRIVE_COMMERCIAL_MAC","$HOME/Library/CloudStorage/OneDrive-会计师事务所（特殊普通合伙）”：

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/luobo/miniconda3/lib/python3.11/site-packages/xlwings/utils.py", line 406, in prepare_sys_path
fullname_url_to_local_path(
File "/Users/luobo/miniconda3/lib/python3.11/site-packages/xlwings/utils.py", line 545, in fullname_url_to_local_path
raise xlwings.XlwingsError(
xlwings.XlwingsError: Couldn't find your local OneDrive for Business file, see: xlwings.org/error

**Comment by fzumstein** [comment]
In this case it's possible that there's a unicode bug, not really sure though.
A possible workaround would be to copy the files locally or disable autosave (may require a restart of Excel).

**Comment by kuaijishi** [comment]
thanks，The error is Chinese character encoding issue.When it's convenient in the future, hope  help us fix 。
I
