### ISSUE TITLE
how to call async udf with sheet as parameter?

### ISSUE THREAD

**Issue by jerronl** [xlwings/xlwings#2420]
#### OS (e.g. Windows 10 or macOS Sierra)
win10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.30.13
office pro plus 2016 version 2402
python 3.11.5

#### Describe your issue (incl. Traceback!)

```python
@xw.func  # (async_mode="threading")
@xw.arg("sheet1", vba="Sheet1")
def test1(sheet1):
    print("test1", sheet1.Name)


@xw.func(async_mode="threading")
@xw.arg("sheet1", vba="Sheet1")
def test2(sheet1):
    print("test2", sheet1.Name)


test1 test
async_thread failed
Traceback (most recent call last):
  File "d:\ProgramData\miniconda3\envs\s1\Lib\site-packages\xlwings\udfs.py", line 67, in async_thread_nocaller
    await loop.run_in_executor(com_executor, functools.partial(func, *args))
  File "d:\ProgramData\miniconda3\envs\s1\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mydoc\git\trade\optai2.py", line 308, in test2
    print("test2", sheet1.Name)
                   ^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\s1\Lib\site-packages\win32com\client\__init__.py", line 583, in __getattr__
    return self._ApplyTypes_(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\s1\Lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147417842, 'The application called an interface that was marshalled for a different thread.', None, None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```vba
# Your code here
Sub test()
    XLPy.CallUDF "test", "test1", Array(shtTest)
    XLPy.CallUDF "test", "test2", Array(shtTest)
End Sub
```

**Comment by sdementen** [comment]
see https://github.com/xlwings/xlwings/issues/2218

**Comment by fzumstein** [comment]
thx, @sdementen!
