### ISSUE TITLE
Support legacy chart sheets for printing to pdf

### ISSUE THREAD

**Issue by Tokarzewski** [xlwings/xlwings#2517]
#### Describe your issue (incl. Traceback!)

Can't specify precisely which sheets should be printed as workbook contains "legacy" chart sheets.

```python
Traceback (most recent call last):
  File "C:\GitHub\db-ashrae140\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 199, in __getattr__
    v = getattr(self._inner, item)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\db-ashrae140\.venv\Lib\site-packages\win32com\client\__init__.py", line 582, in __getattr__
    raise AttributeError(
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Chart instance at 0x1704525008912>' object has no attribute 'to_pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\GitHub\db-ashrae140\step4.py", line 14, in <module>
    generate_workbook_pdf(workbook_path, include_sheets)
  File "c:\GitHub\db-ashrae140\step4.py", line 6, in generate_workbook_pdf
    wb.api.Sheets(23).to_pdf()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\db-ashrae140\.venv\Lib\site-packages\xlwings\_xlwindows.py", line 221, in __getattr__
    self._oleobj_.GetIDsOfNames(0, item)
pywintypes.com_error: (-2147352570, 'Unknown name.', None, None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
with xw.Book(workbook_path) as wb:
        wb.api.Sheets(23).to_pdf()
```

**Comment by Tokarzewski** [comment]
@fzumstein this worked, thank you very much for the help! 

I will just share my small def below, maybe someone else will need this too.

```python
import xlwings as xw
from xlwings.constants import FixedFormatType

def export_chartsheet_to_pdf(excel_filepath, sheet_index, pdf_filepath, quality='standard'):
    quality_types = {"minimum": 1, "standard": 0}
    
    with xw.Book(excel_filepath) as wb:
        wb.api.Sheets(sheet_index).ExportAsFixedFormat(
            Type=FixedFormatType.xlTypePDF,
            Filename=pdf_filepath,
            Quality=quality_types[quality],
            IncludeDocProperties=True,
            IgnorePrintAreas=False,
            OpenAfterPublish=False
        )
```

**Comment by fzumstein** [comment]
thanks!
