### ISSUE TITLE
Failed To RunPython from VBA

### ISSUE THREAD

**Issue by aliyudin21** [xlwings/xlwings#677]
Hello. 

I'm just trying to use xlwings and followed all of the instructions.

I've installed the xlwings-0.10.4 and also imported xlwings.bas on my VBA.

I tried to run the "hello.py". 
I run it on Eclipse and I'm using Windows 32-bit.

But, when I tired to run VBA the msg box showed 

```
---------------------------
Error
---------------------------
'python' is not recognized as an internal or external command,

operable program or batch file.



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```

In addition, when I tried to run the code on Eclipse, I got error message like this one

```
Traceback (most recent call last):
  File "C:\Users\aliyudin\workspace\Ali\hello.py", line 8, in <module>
    import xlwings as xw
  File "C:\Python27\lib\site-packages\xlwings\__init__.py", line 22, in <module>
    from . import _xlwindows as xlplatform
  File "C:\Python27\lib\site-packages\xlwings\_xlwindows.py", line 10, in <module>
    import win32api
ImportError: No module named win32api
```
Ok, so what should I do to fix it ? 

Thankyou :)

**Comment by fzumstein** [comment]
You either need to add python to your PATH so that you can start it by typing `python` on the command prompt or you need to set the full path to the `python.exe` in your xlwings settings in Excel.

**Comment by aliyudin21** [comment]
I think I should start from the scratch. I don't even know how to install the xlwings add in via command line. Can you suggest me how to install it via command line ?

**Comment by fzumstein** [comment]
We will work on making the process better in the future, for now this might help: http://docs.xlwings.org/en/stable/migrate_to_0.11.html

**Comment by QGB** [comment]
> We will work on making the process better in the future, for now this might help: http://docs.xlwings.org/en/stable/migrate_to_0.11.html

_xlwindows.accessible_object_from_window

In [10]: xw._xlwindows.accessible_object_from_window(137170)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-0226bbb15da6> in <module>
----> 1 xw._xlwindows.accessible_object_from_window(137170)

C:\QGB\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in accessible_object_from_window(hwnd)
    191     res = oledll.oleacc.AccessibleObjectFromWindow(
    192         hwnd, OBJID_NATIVEOM,
--> 193         byref(IDispatch._iid_), byref(ptr))
    194
    195     # U.msgbox([hwnd,res,OBJID_NATIVEOM,IDispatch._iid_,ptr ])

_ctypes/callproc.c in GetResult()

OSError: [WinError -2147467259] 未指定的错误

**Comment by fzumstein** [comment]
closing this due to inactivity
