### ISSUE TITLE
Changing colors error

### ISSUE THREAD

**Issue by Bypus** [xlwings/xlwings#926]
Hello, when trying to change color of a cell in a cell I get this error:

```
> Traceback (most recent call last):
>   File "C:\Users\Me\Documents\SomeFolder\try.py", line 66, in <module>
>     wsGeneral.range('D35').color = RgbColor.rgbRed
>   File "C:\Python27\lib\site-packages\xlwings\main.py", line 1426, in color
>     self.impl.color = color_or_rgb
>   File "C:\Python27\lib\site-packages\xlwings\_xlwindows.py", line 877, in color
>     self.xl.Interior.Color = color_or_rgb
>   File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
>     self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
> pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
> 
```

Any idea why ?

**Comment by fzumstein** [comment]
the code looks ok. is this the only that doesn't work?

**Comment by Bypus** [comment]
Yes, only when I try to assign a new color to a cell

**Comment by fzumstein** [comment]
deleting `%appdata%\gen_py` could be worth a try
