### ISSUE TITLE
wb.save() on macOS causes confirmation prompt

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#957]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Sierra
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.12.1, Office 16.19, Python 3.7
#### Describe your issue (incl. Traceback!)

wb.save() on macOS causes confirmation prompt

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Run the followin 2x on from within a new Excel instance.

```python
import xlwings as xw
wb = xw.Book()
wb.save()
```

**Comment by eric1397** [comment]
**I have the same problem.**
The code and error hints are as follows

`import xlwings as xw
app = xw.App(visible=True, add_book=False)
wb = app.books.add()
wb.save()
wb.close()` 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 482, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The object you are trying to access does not exist (-1728)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlwings/main.py", line 682, in close
    self.impl.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlwings/_xlmac.py", line 224, in close
    self.xl.close(saving=kw.no)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 518, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1728
		MESSAGE: The object you are trying to access does not exist
		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 5907874)).workbooks['工作簿1'].close(saving=k.no)`

**Comment by eric1397** [comment]
> 123
> 1234

**Comment by eric1397** [comment]
`1231231231231
123123123123123
123123123`

**Comment by michaelobr** [comment]
I am having the same issue as @jeckun , was anybody able to resolve this?
